POST {{host}}/api/oauth/token
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache
Content-Type: application/json


{
  "grant_type": "client_credentials",
  "client_id": "{{clientId}}",
  "client_secret": "{{clientSecret}}"
}

> {%
client.global.set("auth_token", response.body.access_token);
client.global.set("token_type", response.body.token_type);
%}

###

GET {{host}}/api/_action/cache_info
Accept: application/json
Content-Type: application/json
Authorization: {{token_type}} {{auth_token}}

###

DELETE {{host}}/api/_action/cache
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache
Authorization: {{token_type}} {{auth_token}}

###
