// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    DataTable: typeof import('./src/components/layout/DataTable.vue')['default']
    FormGroup: typeof import('./src/components/layout/FormGroup.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    'IconFa6Regular:circle': typeof import('~icons/fa6-regular/circle')['default']
    'IconFa6Regular:star': typeof import('~icons/fa6-regular/star')['default']
    'IconFa6Solid:arrowDown': typeof import('~icons/fa6-solid/arrow-down')['default']
    'IconFa6Solid:arrowDownLong': typeof import('~icons/fa6-solid/arrow-down-long')['default']
    'IconFa6Solid:arrowUpLong': typeof import('~icons/fa6-solid/arrow-up-long')['default']
    'IconFa6Solid:barsStaggered': typeof import('~icons/fa6-solid/bars-staggered')['default']
    'IconFa6Solid:bell': typeof import('~icons/fa6-solid/bell')['default']
    'IconFa6Solid:cartShopping': typeof import('~icons/fa6-solid/cart-shopping')['default']
    'IconFa6Solid:chevronDown': typeof import('~icons/fa6-solid/chevron-down')['default']
    'IconFa6Solid:chevronUp': typeof import('~icons/fa6-solid/chevron-up')['default']
    'IconFa6Solid:chevronUpLong': typeof import('~icons/fa6-solid/chevron-up-long')['default']
    'IconFa6Solid:chUpLong': typeof import('~icons/fa6-solid/ch-up-long')['default']
    'IconFa6Solid:circleCheck': typeof import('~icons/fa6-solid/circle-check')['default']
    'IconFa6Solid:circleInfo': typeof import('~icons/fa6-solid/circle-info')['default']
    'IconFa6Solid:circleXmark': typeof import('~icons/fa6-solid/circle-xmark')['default']
    'IconFa6Solid:envelope': typeof import('~icons/fa6-solid/envelope')['default']
    'IconFa6Solid:eye': typeof import('~icons/fa6-solid/eye')['default']
    'IconFa6Solid:eyeSlash': typeof import('~icons/fa6-solid/eye-slash')['default']
    'IconFa6Solid:faBell': typeof import('~icons/fa6-solid/fa-bell')['default']
    'IconFa6Solid:floppyDisk': typeof import('~icons/fa6-solid/floppy-disk')['default']
    'IconFa6Solid:inbox': typeof import('~icons/fa6-solid/inbox')['default']
    'IconFa6Solid:key': typeof import('~icons/fa6-solid/key')['default']
    'IconFa6Solid:pencil': typeof import('~icons/fa6-solid/pencil')['default']
    'IconFa6Solid:peopleGroup': typeof import('~icons/fa6-solid/people-group')['default']
    'IconFa6Solid:plus': typeof import('~icons/fa6-solid/plus')['default']
    'IconFa6Solid:rightToBracket': typeof import('~icons/fa6-solid/right-to-bracket')['default']
    'IconFa6Solid:rotate': typeof import('~icons/fa6-solid/rotate')['default']
    'IconFa6Solid:star': typeof import('~icons/fa6-solid/star')['default']
    'IconFa6Solid:starHalfStroke': typeof import('~icons/fa6-solid/star-half-stroke')['default']
    'IconFa6Solid:trash': typeof import('~icons/fa6-solid/trash')['default']
    'IconFa6Solid:triangleExclamation': typeof import('~icons/fa6-solid/triangle-exclamation')['default']
    'IconFa6Solid:upRightFromSquare': typeof import('~icons/fa6-solid/up-right-from-square')['default']
    'IconFa6Solid:xmark': typeof import('~icons/fa6-solid/xmark')['default']
    'IconLineMd:loadingTwotoneLoop': typeof import('~icons/line-md/loading-twotone-loop')['default']
    LoginContainer: typeof import('./src/components/layout/LoginContainer.vue')['default']
    Logo: typeof import('./src/components/layout/Logo.vue')['default']
    MainContainer: typeof import('./src/components/layout/MainContainer.vue')['default']
    Modal: typeof import('./src/components/layout/Modal.vue')['default']
    Nav: typeof import('./src/components/layout/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/layout/Tabs.vue')['default']
  }
}
