ports:
  - name: Frontend
    port: 3000
    onOpen: open-preview
  - name: API
    port: 5789
    onOpen: ignore

vscode:
  extensions:
    - lukashass.volar
    - johnsoncodehk.vscode-typescript-vue-plugin
    - redhat.vscode-xml