x-env: &env
  MAIL_FROM: "Shopmon <noreply@fos.gg>"
  APP_FILES_DIR: /app/uploads
  APP_DATABASE_PATH: /app/db/shopmon.db
  APP_OAUTH_GITHUB_CLIENT_ID: ${APP_OAUTH_GITHUB_CLIENT_ID}
  APP_OAUTH_GITHUB_CLIENT_SECRET: ${APP_OAUTH_GITHUB_CLIENT_SECRET}
  # From 1password
  FRONTEND_URL: ${FRONTEND_URL}
  APP_SECRET: ${APP_SECRET}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_SECURE: ${SMTP_SECURE}
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
  SMTP_REPLY_TO: ${SMTP_REPLY_TO}
  APP_SITESPEED_ENDPOINT: https://sitespeed.fos.gg
  APP_SITESPEED_PREFIX: ${ENVIRONMENT}-
  APP_SITESPEED_API_KEY: ${APP_SITESPEED_API_KEY}
  SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
  SENTRY_DSN: ${SENTRY_DSN}

services:
  migrate:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    environment:
      <<: *env
    command: "migrate.ts"
    volumes:
      - db:/app/db
      - uploads:/app/uploads

  frontend:
    image: ghcr.io/friendsofshopware/shopmon/frontend:${ENVIRONMENT}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.shopmon-${ENVIRONMENT}.entrypoints=websecure
      - traefik.http.routers.shopmon-${ENVIRONMENT}.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls=true
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.certresolver=cloudflare
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.domains[0].main=fos.gg
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.domains[0].sans=*.fos.gg

      - traefik.http.middlewares.shopmon-${ENVIRONMENT}.compress=true
      - traefik.http.middlewares.shopmon-${ENVIRONMENT}.compress.encodings=zstd,gzip
      - traefik.http.routers.shopmon-${ENVIRONMENT}.middlewares=shopmon-${ENVIRONMENT}

  api:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    networks:
      - shopmon
      - traefik
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      <<: *env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.entrypoints=websecure
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.rule=Host(`${APP_DOMAIN}`) && (PathPrefix(`/trpc`) || PathPrefix(`/auth`))
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls=true
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.certresolver=cloudflare
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.domains[0].main=fos.gg
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.domains[0].sans=*.fos.gg

      - traefik.http.middlewares.shopmon-api-${ENVIRONMENT}.compress=true
      - traefik.http.middlewares.shopmon-api-${ENVIRONMENT}.compress.encodings=zstd,gzip
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.middlewares=shopmon-api-${ENVIRONMENT}
    volumes:
      - db:/app/db
      - uploads:/app/api/files

  backup:
    image: offen/docker-volume-backup:latest
    volumes:
      - db:/backup
    environment:
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_PATH: db/${ENVIRONMENT}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      BACKUP_RETENTION_DAYS: 14
      BACKUP_CRON_EXPRESSION: "@hourly"

networks:
  traefik:
    name: traefik_default
    external: true
  shopmon:

volumes:
  db:
  uploads:
