x-env: &env
  MAIL_FROM: "Shopmon <contact@fos.gg>"
  APP_FILES_DIR: /app/uploads
  APP_DATABASE_PATH: /app/db/shopmon.db
  # From 1password
  FRONTEND_URL: ${FRONTEND_URL}
  APP_SECRET: ${APP_SECRET}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_SECURE: ${SMTP_SECURE}
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
  SMTP_REPLY_TO: ${SMTP_REPLY_TO}
  PAGESPEED_API_KEY: ${PAGESPEED_API_KEY}
  SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
  SENTRY_DSN: ${SENTRY_DSN}

services:
  migrate:
    image: ${IMAGE}
    environment:
      <<: *env
    command: "migrate.ts"
    volumes:
      - db:/app/db
      - uploads:/app/uploads

  app:
    image: ${IMAGE}
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      <<: *env
    ports:
      - "127.0.0.1:${LOCAL_PORT}:3000"
    volumes:
      - db:/app/db
      - uploads:/app/uploads

  backup:
    image: litestream/litestream
    volumes:
      - db:/data
    command: ["replicate", "--config", "/etc/litestream.yml"]
    configs:
      - source: litestream
        target: /etc/litestream.yml
    environment:
      LITESTREAM_ACCESS_KEY_ID: ${LITESTREAM_ACCESS_KEY_ID}
      LITESTREAM_SECRET_ACCESS_KEY: ${LITESTREAM_SECRET_ACCESS_KEY}
      ENVIRONMENT: ${ENVIRONMENT}
  
volumes:
  db:
  uploads:

configs:
  litestream:
    content: |
      dbs:
        - path: /data/shopmon.db
          replicas:
            - type: s3
              bucket: shopmon-backups
              path: db/$ENVIRONMENT/
              endpoint: s3.eu-central-003.backblazeb2.com
              force-path-style: true
