x-env: &env
  MAIL_FROM: "Shopmon <noreply@fos.gg>"
  APP_FILES_DIR: /app/uploads
  DATABASE_URL: postgresql://shopmon:${POSTGRES_PASSWORD}@postgres:5432/shopmon
  APP_OAUTH_GITHUB_CLIENT_ID: ${APP_OAUTH_GITHUB_CLIENT_ID}
  APP_OAUTH_GITHUB_CLIENT_SECRET: ${APP_OAUTH_GITHUB_CLIENT_SECRET}
  # From 1password
  FRONTEND_URL: ${FRONTEND_URL}
  APP_SECRET: ${APP_SECRET}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_SECURE: ${SMTP_SECURE}
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
  SMTP_REPLY_TO: ${SMTP_REPLY_TO}
  APP_SITESPEED_ENDPOINT: https://sitespeed.fos.gg
  APP_SITESPEED_PREFIX: shopmon-${ENVIRONMENT}-
  APP_SITESPEED_API_KEY: ${APP_SITESPEED_API_KEY}
  SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
  SENTRY_DSN: ${SENTRY_DSN}

services:
  postgres:
    image: postgres:16-alpine
    networks:
      - shopmon
    environment:
      POSTGRES_USER: shopmon
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: shopmon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopmon"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    networks:
      - shopmon
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *env
    command: "migrate.ts"
    volumes:
      - uploads:/app/uploads

  frontend:
    image: ghcr.io/friendsofshopware/shopmon/frontend:${ENVIRONMENT}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.shopmon-${ENVIRONMENT}.entrypoints=websecure
      - traefik.http.routers.shopmon-${ENVIRONMENT}.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls=true
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.certresolver=cloudflare
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.domains[0].main=fos.gg
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.domains[0].sans=*.fos.gg

      - traefik.http.middlewares.shopmon-${ENVIRONMENT}.compress=true
      - traefik.http.middlewares.shopmon-${ENVIRONMENT}.compress.encodings=zstd,gzip
      - traefik.http.routers.shopmon-${ENVIRONMENT}.middlewares=shopmon-${ENVIRONMENT}

  api:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    networks:
      - shopmon
      - traefik
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      <<: *env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.entrypoints=websecure
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.rule=Host(`${APP_DOMAIN}`) && (PathPrefix(`/trpc`) || PathPrefix(`/auth`))
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls=true
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.certresolver=cloudflare
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.domains[0].main=fos.gg
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.domains[0].sans=*.fos.gg

      - traefik.http.middlewares.shopmon-api-${ENVIRONMENT}.compress=true
      - traefik.http.middlewares.shopmon-api-${ENVIRONMENT}.compress.encodings=zstd,gzip
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.middlewares=shopmon-api-${ENVIRONMENT}
    volumes:
      - uploads:/app/api/files

  cron:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    networks:
      - shopmon
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *env
    volumes_from:
      - api
    command: "cron.js"

  backup:
    image: prodrigestivill/postgres-backup-local:16-alpine
    networks:
      - shopmon
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: shopmon
      POSTGRES_USER: shopmon
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: "@hourly"
      BACKUP_KEEP_DAYS: 14
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
    volumes:
      - postgres_backups:/backups

networks:
  traefik:
    name: traefik_default
    external: true
  shopmon:

volumes:
  postgres_data:
  postgres_backups:
  uploads:
