x-env: &env
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  MAIL_FROM: "Shopmon <noreply@fos.gg>"
  APP_OAUTH_GITHUB_CLIENT_ID: ${APP_OAUTH_GITHUB_CLIENT_ID}
  APP_OAUTH_GITHUB_CLIENT_SECRET: ${APP_OAUTH_GITHUB_CLIENT_SECRET}
  # From 1password
  FRONTEND_URL: ${FRONTEND_URL}
  APP_SECRET: ${APP_SECRET}
  SMTP_HOST: ${SMTP_HOST}
  SMTP_PORT: ${SMTP_PORT}
  SMTP_SECURE: ${SMTP_SECURE}
  SMTP_USER: ${SMTP_USER}
  SMTP_PASS: ${SMTP_PASS}
  SMTP_REPLY_TO: ${SMTP_REPLY_TO}
  APP_SITESPEED_ENDPOINT: https://sitespeed.fos.gg
  APP_SITESPEED_PREFIX: shopmon-${ENVIRONMENT}-
  APP_SITESPEED_API_KEY: ${APP_SITESPEED_API_KEY}
  SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
  SENTRY_DSN: ${SENTRY_DSN}
  APP_S3_ENDPOINT: ${APP_S3_ENDPOINT}
  APP_S3_ACCESS_KEY_ID: ${APP_S3_ACCESS_KEY_ID}
  APP_S3_SECRET_ACCESS_KEY: ${APP_S3_SECRET_ACCESS_KEY}
  APP_S3_BUCKET: ${APP_S3_BUCKET}
  APP_S3_REGION: ${APP_S3_REGION}

services:
  migrate:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    networks:
      - shopmon
    depends_on:
      - db
    environment:
      <<: *env
    command: "migrate.js"

  frontend:
    image: ghcr.io/friendsofshopware/shopmon/frontend:${ENVIRONMENT}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.shopmon-${ENVIRONMENT}.entrypoints=websecure
      - traefik.http.routers.shopmon-${ENVIRONMENT}.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls=true
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.certresolver=cloudflare
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.domains[0].main=fos.gg
      - traefik.http.routers.shopmon-${ENVIRONMENT}.tls.domains[0].sans=*.fos.gg

      - traefik.http.middlewares.shopmon-${ENVIRONMENT}.compress=true
      - traefik.http.middlewares.shopmon-${ENVIRONMENT}.compress.encodings=zstd,gzip
      - traefik.http.routers.shopmon-${ENVIRONMENT}.middlewares=shopmon-${ENVIRONMENT}

  api:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    networks:
      - shopmon
      - traefik
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - db:/app/db
    environment:
      <<: *env
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.entrypoints=websecure
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.rule=Host(`${APP_DOMAIN}`) && (PathPrefix(`/trpc`) || PathPrefix(`/auth`))
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls=true
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.certresolver=cloudflare
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.domains[0].main=fos.gg
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.tls.domains[0].sans=*.fos.gg

      - traefik.http.middlewares.shopmon-api-${ENVIRONMENT}.compress=true
      - traefik.http.middlewares.shopmon-api-${ENVIRONMENT}.compress.encodings=zstd,gzip
      - traefik.http.routers.shopmon-api-${ENVIRONMENT}.middlewares=shopmon-api-${ENVIRONMENT}

  cron:
    image: ghcr.io/friendsofshopware/shopmon/api:${ENVIRONMENT}
    networks:
      - shopmon
    depends_on:
      - db
    environment:
      <<: *env
    command: "cron.js"

  db:
    image: postgres:18.2
    labels:
      - docker-backup.enable=true
      - docker-backup.shopmon-${ENVIRONMENT}-db-hourly.type=postgres
      - docker-backup.shopmon-${ENVIRONMENT}-db-hourly.schedule=0 * * * *
      - docker-backup.shopmon-${ENVIRONMENT}-db-hourly.retention=12
      - docker-backup.shopmon-${ENVIRONMENT}-db-daily.type=postgres
      - docker-backup.shopmon-${ENVIRONMENT}-db-daily.schedule=0 3 * * *
      - docker-backup.shopmon-${ENVIRONMENT}-db-daily.retention=7
    networks:
      - shopmon
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql

networks:
  traefik:
    name: traefik_default
    external: true
  shopmon:

volumes:
  # Old SQLITE DB
  db:
  db-data:
