FROM oven/bun:1 AS build

COPY . /app

WORKDIR /app
RUN bun install --production
WORKDIR /app/api
RUN bun build --target bun --production --bytecode --outdir=dist --sourcemap=external app.ts
RUN bun build --target bun --production --bytecode --outdir=dist --sourcemap=external cron.ts

FROM oven/bun:1

ARG SENTRY_RELEASE="unknown"
ENV SENTRY_RELEASE=${SENTRY_RELEASE}

COPY --from=build /app/api/dist /app/

WORKDIR /app
ENV NODE_ENV=production
EXPOSE 3000
ENTRYPOINT [ "bun" ]

CMD [ "app.js" ]
