packages:
  - api
  - frontend
  - sitespeed-service

catalog:
  typescript: 5.9.3
  better-auth: 1.3.34

ignoredBuiltDependencies:
  - 'better-sqlite3'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

onlyBuiltDependencies:
  - '@biomejs/biome'
  - bcrypt
  - esbuild
