packages:
  - api
  - frontend

catalog:
  typescript: 5.9.3
  better-auth: 1.4.1
  '@better-auth/passkey': 1.4.1
  '@better-auth/sso': 1.4.1

ignoredBuiltDependencies:
  - 'better-sqlite3'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

onlyBuiltDependencies:
  - '@biomejs/biome'
  - bcrypt
  - esbuild
