packages:
  - api
  - frontend
  - sitespeed-service

catalog:
  typescript: 5.9.2
  better-auth: 1.3.23

ignoredBuiltDependencies:
  - 'better-sqlite3'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

onlyBuiltDependencies:
  - '@biomejs/biome'
  - bcrypt
  - esbuild
