packages:
  - api
  - frontend
  - sitespeed-service

catalog:
  typescript: 5.8.3
  better-auth: 1.2.8

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma

onlyBuiltDependencies:
  - '@biomejs/biome'
  - bcrypt
  - better-sqlite3
  - esbuild
  - protobufjs
  - sharp

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  better-sqlite3: '12.0.0'
