// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountOrganizations = `-- name: AdminCountOrganizations :one
SELECT COUNT(*)::int FROM organization
`

func (q *Queries) AdminCountOrganizations(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountOrganizations)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminCountShops = `-- name: AdminCountShops :one
SELECT COUNT(*)::int FROM shop
`

func (q *Queries) AdminCountShops(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountShops)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminGetGrowthShops = `-- name: AdminGetGrowthShops :many
SELECT to_char(created_at, 'YYYY-MM') AS month, COUNT(*)::int AS count
FROM shop GROUP BY month ORDER BY month
`

type AdminGetGrowthShopsRow struct {
	Month string `json:"month"`
	Count int32  `json:"count"`
}

func (q *Queries) AdminGetGrowthShops(ctx context.Context) ([]AdminGetGrowthShopsRow, error) {
	rows, err := q.db.Query(ctx, adminGetGrowthShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetGrowthShopsRow{}
	for rows.Next() {
		var i AdminGetGrowthShopsRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetGrowthUsers = `-- name: AdminGetGrowthUsers :many
SELECT to_char(created_at, 'YYYY-MM') AS month, COUNT(*)::int AS count
FROM "user" GROUP BY month ORDER BY month
`

type AdminGetGrowthUsersRow struct {
	Month string `json:"month"`
	Count int32  `json:"count"`
}

func (q *Queries) AdminGetGrowthUsers(ctx context.Context) ([]AdminGetGrowthUsersRow, error) {
	rows, err := q.db.Query(ctx, adminGetGrowthUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetGrowthUsersRow{}
	for rows.Next() {
		var i AdminGetGrowthUsersRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetRecentShops = `-- name: AdminGetRecentShops :many
SELECT s.id, s.name, s.url, o.name AS organization_name, s.created_at
FROM shop s
JOIN organization o ON o.id = s.organization_id
ORDER BY s.created_at DESC LIMIT 10
`

type AdminGetRecentShopsRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Url              string           `json:"url"`
	OrganizationName string           `json:"organization_name"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) AdminGetRecentShops(ctx context.Context) ([]AdminGetRecentShopsRow, error) {
	rows, err := q.db.Query(ctx, adminGetRecentShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetRecentShopsRow{}
	for rows.Next() {
		var i AdminGetRecentShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.OrganizationName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetRecentUsers = `-- name: AdminGetRecentUsers :many
SELECT id, name, email, created_at FROM "user" ORDER BY created_at DESC LIMIT 10
`

type AdminGetRecentUsersRow struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) AdminGetRecentUsers(ctx context.Context) ([]AdminGetRecentUsersRow, error) {
	rows, err := q.db.Query(ctx, adminGetRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetRecentUsersRow{}
	for rows.Next() {
		var i AdminGetRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetShopwareVersions = `-- name: AdminGetShopwareVersions :many
SELECT shopware_version AS version, COUNT(*)::int AS count
FROM shop GROUP BY shopware_version ORDER BY count DESC
`

type AdminGetShopwareVersionsRow struct {
	Version string `json:"version"`
	Count   int32  `json:"count"`
}

func (q *Queries) AdminGetShopwareVersions(ctx context.Context) ([]AdminGetShopwareVersionsRow, error) {
	rows, err := q.db.Query(ctx, adminGetShopwareVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetShopwareVersionsRow{}
	for rows.Next() {
		var i AdminGetShopwareVersionsRow
		if err := rows.Scan(&i.Version, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetStats = `-- name: AdminGetStats :one
SELECT
  (SELECT COUNT(*) FROM "user")::int AS total_users,
  (SELECT COUNT(*) FROM organization)::int AS total_organizations,
  (SELECT COUNT(*) FROM shop)::int AS total_shops,
  (SELECT COUNT(*) FROM shop WHERE status = 'green')::int AS shops_green,
  (SELECT COUNT(*) FROM shop WHERE status = 'yellow')::int AS shops_yellow,
  (SELECT COUNT(*) FROM shop WHERE status = 'red')::int AS shops_red
`

type AdminGetStatsRow struct {
	TotalUsers         int32 `json:"total_users"`
	TotalOrganizations int32 `json:"total_organizations"`
	TotalShops         int32 `json:"total_shops"`
	ShopsGreen         int32 `json:"shops_green"`
	ShopsYellow        int32 `json:"shops_yellow"`
	ShopsRed           int32 `json:"shops_red"`
}

func (q *Queries) AdminGetStats(ctx context.Context) (AdminGetStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetStats)
	var i AdminGetStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.TotalOrganizations,
		&i.TotalShops,
		&i.ShopsGreen,
		&i.ShopsYellow,
		&i.ShopsRed,
	)
	return i, err
}

const adminListOrganizations = `-- name: AdminListOrganizations :many
SELECT o.id, o.name, o.slug, o.logo, o.created_at,
       (SELECT COUNT(*) FROM shop WHERE organization_id = o.id)::int AS shop_count,
       (SELECT COUNT(*) FROM member WHERE organization_id = o.id)::int AS member_count
FROM organization o
ORDER BY o.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListOrganizationsRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Slug        string           `json:"slug"`
	Logo        *string          `json:"logo"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ShopCount   int32            `json:"shop_count"`
	MemberCount int32            `json:"member_count"`
}

func (q *Queries) AdminListOrganizations(ctx context.Context, arg AdminListOrganizationsParams) ([]AdminListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, adminListOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrganizationsRow{}
	for rows.Next() {
		var i AdminListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.ShopCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListShops = `-- name: AdminListShops :many
SELECT s.id, s.name, s.url, s.status, s.shopware_version, s.last_scraped_at, s.created_at,
       s.organization_id, o.name AS organization_name
FROM shop s
JOIN organization o ON o.id = s.organization_id
ORDER BY s.name
LIMIT $1 OFFSET $2
`

type AdminListShopsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type AdminListShopsRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Url              string           `json:"url"`
	Status           string           `json:"status"`
	ShopwareVersion  string           `json:"shopware_version"`
	LastScrapedAt    pgtype.Timestamp `json:"last_scraped_at"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	OrganizationID   string           `json:"organization_id"`
	OrganizationName string           `json:"organization_name"`
}

func (q *Queries) AdminListShops(ctx context.Context, arg AdminListShopsParams) ([]AdminListShopsRow, error) {
	rows, err := q.db.Query(ctx, adminListShops, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListShopsRow{}
	for rows.Next() {
		var i AdminListShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Status,
			&i.ShopwareVersion,
			&i.LastScrapedAt,
			&i.CreatedAt,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
