// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advisory_suppression.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdvisorySuppression = `-- name: CreateAdvisorySuppression :one

INSERT INTO advisory_suppression (
  organization_id, shop_id, environment_id, advisory_id,
  reason, expires_at, created_by, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, organization_id, shop_id, environment_id, advisory_id, reason, expires_at, created_by, created_at, revoked_at, revoked_by
`

type CreateAdvisorySuppressionParams struct {
	OrganizationID string           `json:"organization_id"`
	ShopID         int32            `json:"shop_id"`
	EnvironmentID  *int32           `json:"environment_id"`
	AdvisoryID     string           `json:"advisory_id"`
	Reason         string           `json:"reason"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	CreatedBy      *string          `json:"created_by"`
}

// Advisory suppressions: a shop owner's recorded decision that an advisory is
// accepted or mitigated outside Shopmon.
//
// "Active" is always (revoked_at IS NULL AND (expires_at IS NULL OR expires_at
// > NOW())). Expiry is enforced at read time rather than by a cleanup job, so
// there is no window in which an expired suppression still silences an alert.
// The same predicate must be used everywhere or the scope tab counts will
// disagree with the list.
func (q *Queries) CreateAdvisorySuppression(ctx context.Context, arg CreateAdvisorySuppressionParams) (AdvisorySuppression, error) {
	row := q.db.QueryRow(ctx, createAdvisorySuppression,
		arg.OrganizationID,
		arg.ShopID,
		arg.EnvironmentID,
		arg.AdvisoryID,
		arg.Reason,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i AdvisorySuppression
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.EnvironmentID,
		&i.AdvisoryID,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getAdvisorySuppressionInOrgs = `-- name: GetAdvisorySuppressionInOrgs :one
SELECT id, organization_id, shop_id, environment_id, advisory_id, reason, expires_at, created_by, created_at, revoked_at, revoked_by FROM advisory_suppression
WHERE id = $1 AND organization_id = ANY($2::text[])
`

type GetAdvisorySuppressionInOrgsParams struct {
	ID              int64    `json:"id"`
	OrganizationIds []string `json:"organization_ids"`
}

// Loaded before a revoke so the same role policy that governed creation can be
// applied: the scope (shop-wide vs environment) decides which roles may act.
func (q *Queries) GetAdvisorySuppressionInOrgs(ctx context.Context, arg GetAdvisorySuppressionInOrgsParams) (AdvisorySuppression, error) {
	row := q.db.QueryRow(ctx, getAdvisorySuppressionInOrgs, arg.ID, arg.OrganizationIds)
	var i AdvisorySuppression
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.EnvironmentID,
		&i.AdvisoryID,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const listActiveSuppressionsForEnvironment = `-- name: ListActiveSuppressionsForEnvironment :many
SELECT s.id, s.organization_id, s.shop_id, s.environment_id, s.advisory_id, s.reason, s.expires_at, s.created_by, s.created_at, s.revoked_at, s.revoked_by
FROM advisory_suppression s
JOIN environment e ON e.id = $1::int
WHERE s.shop_id = e.shop_id
  AND (s.environment_id IS NULL OR s.environment_id = e.id)
  AND s.revoked_at IS NULL
  AND (s.expires_at IS NULL OR s.expires_at > NOW())
ORDER BY s.advisory_id
`

// Active suppressions covering one environment: shop-wide rows plus rows
// narrowed to this environment.
func (q *Queries) ListActiveSuppressionsForEnvironment(ctx context.Context, environmentID int32) ([]AdvisorySuppression, error) {
	rows, err := q.db.Query(ctx, listActiveSuppressionsForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdvisorySuppression{}
	for rows.Next() {
		var i AdvisorySuppression
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.EnvironmentID,
			&i.AdvisoryID,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressedAdvisoriesForEnvironment = `-- name: ListSuppressedAdvisoriesForEnvironment :many
SELECT a.advisory_id, a.cve, a.ghsa_id
FROM advisory_suppression s
JOIN environment e ON e.id = $1::int
JOIN composer_advisory a ON a.advisory_id = s.advisory_id
WHERE s.shop_id = e.shop_id
  AND (s.environment_id IS NULL OR s.environment_id = e.id)
  AND s.revoked_at IS NULL
  AND (s.expires_at IS NULL OR s.expires_at > NOW())
ORDER BY a.advisory_id
`

type ListSuppressedAdvisoriesForEnvironmentRow struct {
	AdvisoryID string  `json:"advisory_id"`
	Cve        *string `json:"cve"`
	GhsaID     *string `json:"ghsa_id"`
}

// Advisories actively suppressed for one environment, with the identifiers the
// checker uses to build a check id. Consumed by the scrape so a suppressed
// advisory neither escalates status nor triggers an alert.
func (q *Queries) ListSuppressedAdvisoriesForEnvironment(ctx context.Context, environmentID int32) ([]ListSuppressedAdvisoriesForEnvironmentRow, error) {
	rows, err := q.db.Query(ctx, listSuppressedAdvisoriesForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuppressedAdvisoriesForEnvironmentRow{}
	for rows.Next() {
		var i ListSuppressedAdvisoriesForEnvironmentRow
		if err := rows.Scan(&i.AdvisoryID, &i.Cve, &i.GhsaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressionsForOrganizations = `-- name: ListSuppressionsForOrganizations :many
SELECT s.id, s.organization_id, s.shop_id, s.environment_id, s.advisory_id, s.reason, s.expires_at, s.created_by, s.created_at, s.revoked_at, s.revoked_by,
       a.title AS advisory_title,
       a.cve AS advisory_cve,
       a.severity AS advisory_severity,
       a.severity_override AS advisory_severity_override,
       sh.name AS shop_name,
       e.name AS environment_name,
       u.name AS created_by_name
FROM advisory_suppression s
JOIN composer_advisory a ON a.advisory_id = s.advisory_id
JOIN shop sh ON sh.id = s.shop_id
LEFT JOIN environment e ON e.id = s.environment_id
LEFT JOIN "user" u ON u.id = s.created_by
WHERE s.organization_id = ANY($1::text[])
  AND (
    $2::boolean
    OR (s.revoked_at IS NULL AND (s.expires_at IS NULL OR s.expires_at > NOW()))
  )
ORDER BY s.created_at DESC
`

type ListSuppressionsForOrganizationsParams struct {
	OrganizationIds []string `json:"organization_ids"`
	IncludeInactive bool     `json:"include_inactive"`
}

type ListSuppressionsForOrganizationsRow struct {
	ID                       int64            `json:"id"`
	OrganizationID           string           `json:"organization_id"`
	ShopID                   int32            `json:"shop_id"`
	EnvironmentID            *int32           `json:"environment_id"`
	AdvisoryID               string           `json:"advisory_id"`
	Reason                   string           `json:"reason"`
	ExpiresAt                pgtype.Timestamp `json:"expires_at"`
	CreatedBy                *string          `json:"created_by"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	RevokedAt                pgtype.Timestamp `json:"revoked_at"`
	RevokedBy                *string          `json:"revoked_by"`
	AdvisoryTitle            string           `json:"advisory_title"`
	AdvisoryCve              *string          `json:"advisory_cve"`
	AdvisorySeverity         *string          `json:"advisory_severity"`
	AdvisorySeverityOverride *string          `json:"advisory_severity_override"`
	ShopName                 string           `json:"shop_name"`
	EnvironmentName          *string          `json:"environment_name"`
	CreatedByName            *string          `json:"created_by_name"`
}

func (q *Queries) ListSuppressionsForOrganizations(ctx context.Context, arg ListSuppressionsForOrganizationsParams) ([]ListSuppressionsForOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listSuppressionsForOrganizations, arg.OrganizationIds, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSuppressionsForOrganizationsRow{}
	for rows.Next() {
		var i ListSuppressionsForOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ShopID,
			&i.EnvironmentID,
			&i.AdvisoryID,
			&i.Reason,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
			&i.AdvisoryTitle,
			&i.AdvisoryCve,
			&i.AdvisorySeverity,
			&i.AdvisorySeverityOverride,
			&i.ShopName,
			&i.EnvironmentName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdvisorySuppression = `-- name: RevokeAdvisorySuppression :one
UPDATE advisory_suppression
SET revoked_at = NOW(), revoked_by = $2
WHERE id = $1 AND revoked_at IS NULL
  AND organization_id = ANY($3::text[])
RETURNING id, organization_id, shop_id, environment_id, advisory_id, reason, expires_at, created_by, created_at, revoked_at, revoked_by
`

type RevokeAdvisorySuppressionParams struct {
	ID              int64    `json:"id"`
	RevokedBy       *string  `json:"revoked_by"`
	OrganizationIds []string `json:"organization_ids"`
}

func (q *Queries) RevokeAdvisorySuppression(ctx context.Context, arg RevokeAdvisorySuppressionParams) (AdvisorySuppression, error) {
	row := q.db.QueryRow(ctx, revokeAdvisorySuppression, arg.ID, arg.RevokedBy, arg.OrganizationIds)
	var i AdvisorySuppression
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.EnvironmentID,
		&i.AdvisoryID,
		&i.Reason,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const revokeExpiredAdvisorySuppressions = `-- name: RevokeExpiredAdvisorySuppressions :execrows
UPDATE advisory_suppression
SET revoked_at = NOW(), revoked_by = $3
WHERE shop_id = $1
  AND advisory_id = $2
  AND (
    ($4::int IS NULL AND environment_id IS NULL)
    OR environment_id = $4::int
  )
  AND revoked_at IS NULL
  AND expires_at IS NOT NULL AND expires_at <= NOW()
`

type RevokeExpiredAdvisorySuppressionsParams struct {
	ShopID        int32   `json:"shop_id"`
	AdvisoryID    string  `json:"advisory_id"`
	RevokedBy     *string `json:"revoked_by"`
	EnvironmentID *int32  `json:"environment_id"`
}

// The partial unique indexes only exclude revoked rows (an "active" predicate
// cannot use NOW() in an index), so an expired-but-unrevoked row still blocks a
// new suppression for the same scope. Retiring it on conflict keeps the audit
// trail and lets the scope be suppressed again.
func (q *Queries) RevokeExpiredAdvisorySuppressions(ctx context.Context, arg RevokeExpiredAdvisorySuppressionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeExpiredAdvisorySuppressions,
		arg.ShopID,
		arg.AdvisoryID,
		arg.RevokedBy,
		arg.EnvironmentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
