// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO project_api_key (id, project_id, name, token, scopes, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id
`

type CreateApiKeyParams struct {
	ID        string          `json:"id"`
	ProjectID int32           `json:"project_id"`
	Name      string          `json:"name"`
	Token     string          `json:"token"`
	Scopes    json.RawMessage `json:"scopes"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Token,
		arg.Scopes,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM project_api_key WHERE id = $1 AND project_id = $2
`

type DeleteApiKeyParams struct {
	ID        string `json:"id"`
	ProjectID int32  `json:"project_id"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error {
	_, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.ProjectID)
	return err
}

const getApiKeyByToken = `-- name: GetApiKeyByToken :one
SELECT pak.id, pak.project_id, pak.name, pak.token, pak.scopes, pak.created_at, pak.last_used_at,
       p.organization_id
FROM project_api_key pak
JOIN project p ON p.id = pak.project_id
WHERE pak.token = $1
`

type GetApiKeyByTokenRow struct {
	ID             string           `json:"id"`
	ProjectID      int32            `json:"project_id"`
	Name           string           `json:"name"`
	Token          string           `json:"token"`
	Scopes         json.RawMessage  `json:"scopes"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastUsedAt     pgtype.Timestamp `json:"last_used_at"`
	OrganizationID string           `json:"organization_id"`
}

func (q *Queries) GetApiKeyByToken(ctx context.Context, token string) (GetApiKeyByTokenRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyByToken, token)
	var i GetApiKeyByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Token,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listApiKeysByProject = `-- name: ListApiKeysByProject :many
SELECT id, project_id, name, scopes, created_at, last_used_at
FROM project_api_key WHERE project_id = $1 ORDER BY created_at DESC
`

type ListApiKeysByProjectRow struct {
	ID         string           `json:"id"`
	ProjectID  int32            `json:"project_id"`
	Name       string           `json:"name"`
	Scopes     json.RawMessage  `json:"scopes"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

func (q *Queries) ListApiKeysByProject(ctx context.Context, projectID int32) ([]ListApiKeysByProjectRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysByProjectRow{}
	for rows.Next() {
		var i ListApiKeysByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE project_api_key SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsed, id)
	return err
}
