// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO shop_api_key (id, shop_id, name, token, scopes, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id
`

type CreateApiKeyParams struct {
	ID     string          `json:"id"`
	ShopID int32           `json:"shop_id"`
	Name   string          `json:"name"`
	Token  string          `json:"token"`
	Scopes json.RawMessage `json:"scopes"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.Token,
		arg.Scopes,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM shop_api_key WHERE id = $1 AND shop_id = $2
`

type DeleteApiKeyParams struct {
	ID     string `json:"id"`
	ShopID int32  `json:"shop_id"`
}

func (q *Queries) DeleteApiKey(ctx context.Context, arg DeleteApiKeyParams) error {
	_, err := q.db.Exec(ctx, deleteApiKey, arg.ID, arg.ShopID)
	return err
}

const getApiKeyByToken = `-- name: GetApiKeyByToken :one
SELECT sak.id, sak.shop_id, sak.name, sak.token, sak.scopes, sak.created_at, sak.last_used_at,
       s.organization_id
FROM shop_api_key sak
JOIN shop s ON s.id = sak.shop_id
WHERE sak.token = $1
`

type GetApiKeyByTokenRow struct {
	ID             string           `json:"id"`
	ShopID         int32            `json:"shop_id"`
	Name           string           `json:"name"`
	Token          string           `json:"token"`
	Scopes         json.RawMessage  `json:"scopes"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastUsedAt     pgtype.Timestamp `json:"last_used_at"`
	OrganizationID string           `json:"organization_id"`
}

func (q *Queries) GetApiKeyByToken(ctx context.Context, token string) (GetApiKeyByTokenRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyByToken, token)
	var i GetApiKeyByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Token,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listApiKeysByShop = `-- name: ListApiKeysByShop :many
SELECT id, shop_id, name, scopes, created_at, last_used_at
FROM shop_api_key WHERE shop_id = $1 ORDER BY created_at DESC
`

type ListApiKeysByShopRow struct {
	ID         string           `json:"id"`
	ShopID     int32            `json:"shop_id"`
	Name       string           `json:"name"`
	Scopes     json.RawMessage  `json:"scopes"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

func (q *Queries) ListApiKeysByShop(ctx context.Context, shopID int32) ([]ListApiKeysByShopRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysByShopRow{}
	for rows.Next() {
		var i ListApiKeysByShopRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiKeyLastUsed = `-- name: UpdateApiKeyLastUsed :exec
UPDATE shop_api_key SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateApiKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateApiKeyLastUsed, id)
	return err
}
