// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package queries

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log (actor_user_id, action, target_user_id, detail, ip_address)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuditLogParams struct {
	ActorUserID  *string `json:"actor_user_id"`
	Action       string  `json:"action"`
	TargetUserID *string `json:"target_user_id"`
	Detail       *string `json:"detail"`
	IpAddress    *string `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ActorUserID,
		arg.Action,
		arg.TargetUserID,
		arg.Detail,
		arg.IpAddress,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_user_id, action, target_user_id, detail, ip_address, created_at
FROM audit_log
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetUserID,
			&i.Detail,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
