// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cleanup.sql

package queries

import (
	"context"
)

const cleanupExpiredBans = `-- name: CleanupExpiredBans :exec
UPDATE "user" SET banned = false, ban_reason = NULL, ban_expires = NULL
WHERE banned = true AND ban_expires IS NOT NULL AND ban_expires < NOW()
`

func (q *Queries) CleanupExpiredBans(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredBans)
	return err
}

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM session WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const cleanupOldChangelogData = `-- name: CleanupOldChangelogData :exec
DELETE FROM environment_changelog WHERE date < NOW() - interval '180 days'
`

func (q *Queries) CleanupOldChangelogData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldChangelogData)
	return err
}

const cleanupOldNotifications = `-- name: CleanupOldNotifications :exec
DELETE FROM user_notification WHERE read = true AND created_at < NOW() - interval '90 days'
`

func (q *Queries) CleanupOldNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldNotifications)
	return err
}

const cleanupOldSitespeedData = `-- name: CleanupOldSitespeedData :exec
DELETE FROM environment_sitespeed WHERE created_at < NOW() - interval '90 days'
`

func (q *Queries) CleanupOldSitespeedData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldSitespeedData)
	return err
}
