// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: composer_advisory.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countComposerAdvisories = `-- name: CountComposerAdvisories :one
SELECT COUNT(*)::int
FROM composer_advisory a
WHERE
  ($1::boolean IS NULL OR a.is_visible = $1)
  AND (
    $2::text IS NULL
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id AND p.package_name = $2
    )
  )
  AND (
    $3::text IS NULL
    OR lower(COALESCE(a.severity_override, a.severity, '')) = lower($3)
  )
  AND (
    $4::text IS NULL
    OR $4 = ANY(a.tags)
  )
  AND (
    $5::text IS NULL
    OR a.title ILIKE '%' || $5 || '%'
    OR COALESCE(a.cve, '') ILIKE '%' || $5 || '%'
    OR COALESCE(a.ghsa_id, '') ILIKE '%' || $5 || '%'
    OR a.advisory_id ILIKE '%' || $5 || '%'
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id
        AND (
          p.package_name ILIKE '%' || $5 || '%'
          OR p.packagist_advisory_id ILIKE '%' || $5 || '%'
        )
    )
  )
`

type CountComposerAdvisoriesParams struct {
	IsVisible   *bool   `json:"is_visible"`
	PackageName *string `json:"package_name"`
	Severity    *string `json:"severity"`
	Tag         *string `json:"tag"`
	Search      *string `json:"search"`
}

func (q *Queries) CountComposerAdvisories(ctx context.Context, arg CountComposerAdvisoriesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countComposerAdvisories,
		arg.IsVisible,
		arg.PackageName,
		arg.Severity,
		arg.Tag,
		arg.Search,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getComposerAdvisory = `-- name: GetComposerAdvisory :one
SELECT advisory_id, title, link, cve, ghsa_id, severity, sources, reported_at, composer_repository, synced_at, created_at, updated_at, summary, description, cvss_score, cvss_vector, cwes, external_references, details_source, details_synced_at, github_synced_at, details_attempted_at, severity_override, is_visible, notes_public, notes_internal, remediation_summary, remediation_url, recommended_upgrade, shopware_impact_summary, affected_components, tags, enriched_at, enriched_by, first_patched_versions FROM composer_advisory WHERE advisory_id = $1
`

func (q *Queries) GetComposerAdvisory(ctx context.Context, advisoryID string) (ComposerAdvisory, error) {
	row := q.db.QueryRow(ctx, getComposerAdvisory, advisoryID)
	var i ComposerAdvisory
	err := row.Scan(
		&i.AdvisoryID,
		&i.Title,
		&i.Link,
		&i.Cve,
		&i.GhsaID,
		&i.Severity,
		&i.Sources,
		&i.ReportedAt,
		&i.ComposerRepository,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.Description,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwes,
		&i.ExternalReferences,
		&i.DetailsSource,
		&i.DetailsSyncedAt,
		&i.GithubSyncedAt,
		&i.DetailsAttemptedAt,
		&i.SeverityOverride,
		&i.IsVisible,
		&i.NotesPublic,
		&i.NotesInternal,
		&i.RemediationSummary,
		&i.RemediationUrl,
		&i.RecommendedUpgrade,
		&i.ShopwareImpactSummary,
		&i.AffectedComponents,
		&i.Tags,
		&i.EnrichedAt,
		&i.EnrichedBy,
		&i.FirstPatchedVersions,
	)
	return i, err
}

const getComposerAdvisoryByPackagistID = `-- name: GetComposerAdvisoryByPackagistID :one
SELECT a.advisory_id, a.title, a.link, a.cve, a.ghsa_id, a.severity, a.sources, a.reported_at, a.composer_repository, a.synced_at, a.created_at, a.updated_at, a.summary, a.description, a.cvss_score, a.cvss_vector, a.cwes, a.external_references, a.details_source, a.details_synced_at, a.github_synced_at, a.details_attempted_at, a.severity_override, a.is_visible, a.notes_public, a.notes_internal, a.remediation_summary, a.remediation_url, a.recommended_upgrade, a.shopware_impact_summary, a.affected_components, a.tags, a.enriched_at, a.enriched_by, a.first_patched_versions
FROM composer_advisory a
JOIN composer_advisory_package p ON p.advisory_id = a.advisory_id
WHERE p.packagist_advisory_id = $1
LIMIT 1
`

func (q *Queries) GetComposerAdvisoryByPackagistID(ctx context.Context, packagistAdvisoryID string) (ComposerAdvisory, error) {
	row := q.db.QueryRow(ctx, getComposerAdvisoryByPackagistID, packagistAdvisoryID)
	var i ComposerAdvisory
	err := row.Scan(
		&i.AdvisoryID,
		&i.Title,
		&i.Link,
		&i.Cve,
		&i.GhsaID,
		&i.Severity,
		&i.Sources,
		&i.ReportedAt,
		&i.ComposerRepository,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.Description,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwes,
		&i.ExternalReferences,
		&i.DetailsSource,
		&i.DetailsSyncedAt,
		&i.GithubSyncedAt,
		&i.DetailsAttemptedAt,
		&i.SeverityOverride,
		&i.IsVisible,
		&i.NotesPublic,
		&i.NotesInternal,
		&i.RemediationSummary,
		&i.RemediationUrl,
		&i.RecommendedUpgrade,
		&i.ShopwareImpactSummary,
		&i.AffectedComponents,
		&i.Tags,
		&i.EnrichedAt,
		&i.EnrichedBy,
		&i.FirstPatchedVersions,
	)
	return i, err
}

const getComposerAdvisorySyncState = `-- name: GetComposerAdvisorySyncState :one
SELECT id, last_updated_since, last_full_sync_at, last_incremental_sync_at, last_error, updated_at FROM composer_advisory_sync_state WHERE id = 1
`

func (q *Queries) GetComposerAdvisorySyncState(ctx context.Context) (ComposerAdvisorySyncState, error) {
	row := q.db.QueryRow(ctx, getComposerAdvisorySyncState)
	var i ComposerAdvisorySyncState
	err := row.Scan(
		&i.ID,
		&i.LastUpdatedSince,
		&i.LastFullSyncAt,
		&i.LastIncrementalSyncAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const listComposerAdvisories = `-- name: ListComposerAdvisories :many
SELECT a.advisory_id, a.title, a.link, a.cve, a.ghsa_id, a.severity, a.sources, a.reported_at, a.composer_repository, a.synced_at, a.created_at, a.updated_at, a.summary, a.description, a.cvss_score, a.cvss_vector, a.cwes, a.external_references, a.details_source, a.details_synced_at, a.github_synced_at, a.details_attempted_at, a.severity_override, a.is_visible, a.notes_public, a.notes_internal, a.remediation_summary, a.remediation_url, a.recommended_upgrade, a.shopware_impact_summary, a.affected_components, a.tags, a.enriched_at, a.enriched_by, a.first_patched_versions
FROM composer_advisory a
WHERE
  ($3::boolean IS NULL OR a.is_visible = $3)
  AND (
    $4::text IS NULL
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id AND p.package_name = $4
    )
  )
  AND (
    $5::text IS NULL
    OR lower(COALESCE(a.severity_override, a.severity, '')) = lower($5)
  )
  AND (
    $6::text IS NULL
    OR $6 = ANY(a.tags)
  )
  AND (
    $7::text IS NULL
    OR a.title ILIKE '%' || $7 || '%'
    OR COALESCE(a.cve, '') ILIKE '%' || $7 || '%'
    OR COALESCE(a.ghsa_id, '') ILIKE '%' || $7 || '%'
    OR a.advisory_id ILIKE '%' || $7 || '%'
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id
        AND (
          p.package_name ILIKE '%' || $7 || '%'
          OR p.packagist_advisory_id ILIKE '%' || $7 || '%'
        )
    )
  )
ORDER BY a.reported_at DESC NULLS LAST, a.advisory_id DESC
LIMIT $1 OFFSET $2
`

type ListComposerAdvisoriesParams struct {
	Limit       int32   `json:"limit"`
	Offset      int32   `json:"offset"`
	IsVisible   *bool   `json:"is_visible"`
	PackageName *string `json:"package_name"`
	Severity    *string `json:"severity"`
	Tag         *string `json:"tag"`
	Search      *string `json:"search"`
}

func (q *Queries) ListComposerAdvisories(ctx context.Context, arg ListComposerAdvisoriesParams) ([]ComposerAdvisory, error) {
	rows, err := q.db.Query(ctx, listComposerAdvisories,
		arg.Limit,
		arg.Offset,
		arg.IsVisible,
		arg.PackageName,
		arg.Severity,
		arg.Tag,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComposerAdvisory{}
	for rows.Next() {
		var i ComposerAdvisory
		if err := rows.Scan(
			&i.AdvisoryID,
			&i.Title,
			&i.Link,
			&i.Cve,
			&i.GhsaID,
			&i.Severity,
			&i.Sources,
			&i.ReportedAt,
			&i.ComposerRepository,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Summary,
			&i.Description,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwes,
			&i.ExternalReferences,
			&i.DetailsSource,
			&i.DetailsSyncedAt,
			&i.GithubSyncedAt,
			&i.DetailsAttemptedAt,
			&i.SeverityOverride,
			&i.IsVisible,
			&i.NotesPublic,
			&i.NotesInternal,
			&i.RemediationSummary,
			&i.RemediationUrl,
			&i.RecommendedUpgrade,
			&i.ShopwareImpactSummary,
			&i.AffectedComponents,
			&i.Tags,
			&i.EnrichedAt,
			&i.EnrichedBy,
			&i.FirstPatchedVersions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposerAdvisoryCvePendingDetails = `-- name: ListComposerAdvisoryCvePendingDetails :many
SELECT cve
FROM composer_advisory
WHERE cve IS NOT NULL AND cve <> ''
  AND details_synced_at IS NULL
GROUP BY cve
ORDER BY MIN(details_attempted_at) ASC NULLS FIRST, cve
LIMIT $1
`

// Least-recently-attempted first: a fetch that keeps failing drifts to the
// back of the queue instead of occupying the whole batch every run.
func (q *Queries) ListComposerAdvisoryCvePendingDetails(ctx context.Context, limit int32) ([]*string, error) {
	rows, err := q.db.Query(ctx, listComposerAdvisoryCvePendingDetails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var cve *string
		if err := rows.Scan(&cve); err != nil {
			return nil, err
		}
		items = append(items, cve)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposerAdvisoryGhsaPendingDetails = `-- name: ListComposerAdvisoryGhsaPendingDetails :many
SELECT ghsa_id,
       BOOL_OR(details_synced_at IS NULL) AS needs_details,
       COALESCE(MIN(link) FILTER (
         WHERE link ~ '^https://github\.com/[A-Za-z0-9._-]+/[A-Za-z0-9._-]+/security/advisories/GHSA-'
       ), '')::text AS link
FROM composer_advisory
WHERE ghsa_id IS NOT NULL AND ghsa_id <> ''
  AND (details_synced_at IS NULL OR github_synced_at IS NULL)
GROUP BY ghsa_id
ORDER BY MIN(details_attempted_at) ASC NULLS FIRST, ghsa_id
LIMIT $1
`

type ListComposerAdvisoryGhsaPendingDetailsRow struct {
	GhsaID       *string `json:"ghsa_id"`
	NeedsDetails bool    `json:"needs_details"`
	Link         string  `json:"link"`
}

// The GitHub pass serves two needs: details for rows nothing else enriched,
// and first_patched_versions for every GHSA-bearing row — including those NVD
// already enriched, hence the separate github_synced_at marker.
// link is carried along so a GHSA missing from the global advisory database can
// still be fetched from the repository that published it. Only a
// repository-scoped link serves that purpose, so siblings sharing the GHSA are
// filtered to that shape rather than picked by sort order: a global
// github.com/advisories link sorts first but names no repository, and would
// leave the advisory unenriched forever.
func (q *Queries) ListComposerAdvisoryGhsaPendingDetails(ctx context.Context, limit int32) ([]ListComposerAdvisoryGhsaPendingDetailsRow, error) {
	rows, err := q.db.Query(ctx, listComposerAdvisoryGhsaPendingDetails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComposerAdvisoryGhsaPendingDetailsRow{}
	for rows.Next() {
		var i ListComposerAdvisoryGhsaPendingDetailsRow
		if err := rows.Scan(&i.GhsaID, &i.NeedsDetails, &i.Link); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposerAdvisoryPackages = `-- name: ListComposerAdvisoryPackages :many
SELECT DISTINCT p.package_name
FROM composer_advisory_package p
JOIN composer_advisory a ON a.advisory_id = p.advisory_id
WHERE ($1::boolean IS NULL OR a.is_visible = $1)
ORDER BY p.package_name
`

func (q *Queries) ListComposerAdvisoryPackages(ctx context.Context, isVisible *bool) ([]string, error) {
	rows, err := q.db.Query(ctx, listComposerAdvisoryPackages, isVisible)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var package_name string
		if err := rows.Scan(&package_name); err != nil {
			return nil, err
		}
		items = append(items, package_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposerAdvisoryPackagesForAdvisories = `-- name: ListComposerAdvisoryPackagesForAdvisories :many
SELECT advisory_id, package_name, packagist_advisory_id, affected_versions, synced_at
FROM composer_advisory_package
WHERE advisory_id = ANY($1::text[])
ORDER BY advisory_id, package_name
`

func (q *Queries) ListComposerAdvisoryPackagesForAdvisories(ctx context.Context, dollar_1 []string) ([]ComposerAdvisoryPackage, error) {
	rows, err := q.db.Query(ctx, listComposerAdvisoryPackagesForAdvisories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComposerAdvisoryPackage{}
	for rows.Next() {
		var i ComposerAdvisoryPackage
		if err := rows.Scan(
			&i.AdvisoryID,
			&i.PackageName,
			&i.PackagistAdvisoryID,
			&i.AffectedVersions,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposerAdvisoryPackagesForAdvisory = `-- name: ListComposerAdvisoryPackagesForAdvisory :many
SELECT package_name, packagist_advisory_id, affected_versions, synced_at
FROM composer_advisory_package
WHERE advisory_id = $1
ORDER BY package_name
`

type ListComposerAdvisoryPackagesForAdvisoryRow struct {
	PackageName         string           `json:"package_name"`
	PackagistAdvisoryID string           `json:"packagist_advisory_id"`
	AffectedVersions    string           `json:"affected_versions"`
	SyncedAt            pgtype.Timestamp `json:"synced_at"`
}

func (q *Queries) ListComposerAdvisoryPackagesForAdvisory(ctx context.Context, advisoryID string) ([]ListComposerAdvisoryPackagesForAdvisoryRow, error) {
	rows, err := q.db.Query(ctx, listComposerAdvisoryPackagesForAdvisory, advisoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComposerAdvisoryPackagesForAdvisoryRow{}
	for rows.Next() {
		var i ListComposerAdvisoryPackagesForAdvisoryRow
		if err := rows.Scan(
			&i.PackageName,
			&i.PackagistAdvisoryID,
			&i.AffectedVersions,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleComposerAdvisories = `-- name: ListVisibleComposerAdvisories :many
SELECT advisory_id, title, link, cve, ghsa_id, severity, sources, reported_at, composer_repository, synced_at, created_at, updated_at, summary, description, cvss_score, cvss_vector, cwes, external_references, details_source, details_synced_at, github_synced_at, details_attempted_at, severity_override, is_visible, notes_public, notes_internal, remediation_summary, remediation_url, recommended_upgrade, shopware_impact_summary, affected_components, tags, enriched_at, enriched_by, first_patched_versions
FROM composer_advisory
WHERE is_visible = true
ORDER BY reported_at DESC NULLS LAST, advisory_id DESC
`

func (q *Queries) ListVisibleComposerAdvisories(ctx context.Context) ([]ComposerAdvisory, error) {
	rows, err := q.db.Query(ctx, listVisibleComposerAdvisories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComposerAdvisory{}
	for rows.Next() {
		var i ComposerAdvisory
		if err := rows.Scan(
			&i.AdvisoryID,
			&i.Title,
			&i.Link,
			&i.Cve,
			&i.GhsaID,
			&i.Severity,
			&i.Sources,
			&i.ReportedAt,
			&i.ComposerRepository,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Summary,
			&i.Description,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwes,
			&i.ExternalReferences,
			&i.DetailsSource,
			&i.DetailsSyncedAt,
			&i.GithubSyncedAt,
			&i.DetailsAttemptedAt,
			&i.SeverityOverride,
			&i.IsVisible,
			&i.NotesPublic,
			&i.NotesInternal,
			&i.RemediationSummary,
			&i.RemediationUrl,
			&i.RecommendedUpgrade,
			&i.ShopwareImpactSummary,
			&i.AffectedComponents,
			&i.Tags,
			&i.EnrichedAt,
			&i.EnrichedBy,
			&i.FirstPatchedVersions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markComposerAdvisoryDetailsAttemptedByCve = `-- name: MarkComposerAdvisoryDetailsAttemptedByCve :exec
UPDATE composer_advisory SET details_attempted_at = NOW()
WHERE cve = $1
`

func (q *Queries) MarkComposerAdvisoryDetailsAttemptedByCve(ctx context.Context, cve *string) error {
	_, err := q.db.Exec(ctx, markComposerAdvisoryDetailsAttemptedByCve, cve)
	return err
}

const markComposerAdvisoryDetailsAttemptedByGhsa = `-- name: MarkComposerAdvisoryDetailsAttemptedByGhsa :exec
UPDATE composer_advisory SET details_attempted_at = NOW()
WHERE ghsa_id = $1
`

func (q *Queries) MarkComposerAdvisoryDetailsAttemptedByGhsa(ctx context.Context, ghsaID *string) error {
	_, err := q.db.Exec(ctx, markComposerAdvisoryDetailsAttemptedByGhsa, ghsaID)
	return err
}

const markComposerAdvisoryGithubSyncedByGhsa = `-- name: MarkComposerAdvisoryGithubSyncedByGhsa :exec
UPDATE composer_advisory SET github_synced_at = NOW()
WHERE ghsa_id = $1
`

func (q *Queries) MarkComposerAdvisoryGithubSyncedByGhsa(ctx context.Context, ghsaID *string) error {
	_, err := q.db.Exec(ctx, markComposerAdvisoryGithubSyncedByGhsa, ghsaID)
	return err
}

const updateComposerAdvisoryDetailsByCve = `-- name: UpdateComposerAdvisoryDetailsByCve :exec
UPDATE composer_advisory SET
  summary = $2,
  description = $3,
  cvss_score = $4,
  cvss_vector = $5,
  cwes = $6,
  external_references = $7,
  details_source = $8,
  details_synced_at = NOW(),
  updated_at = NOW()
WHERE cve = $1
  AND (details_synced_at IS NULL OR details_source = $8)
`

type UpdateComposerAdvisoryDetailsByCveParams struct {
	Cve                *string         `json:"cve"`
	Summary            *string         `json:"summary"`
	Description        *string         `json:"description"`
	CvssScore          *float64        `json:"cvss_score"`
	CvssVector         *string         `json:"cvss_vector"`
	Cwes               json.RawMessage `json:"cwes"`
	ExternalReferences json.RawMessage `json:"external_references"`
	DetailsSource      *string         `json:"details_source"`
}

// The WHERE guards stop one identifier's fetch from clobbering sibling rows
// that share the cve/ghsa but were already enriched from another source.
func (q *Queries) UpdateComposerAdvisoryDetailsByCve(ctx context.Context, arg UpdateComposerAdvisoryDetailsByCveParams) error {
	_, err := q.db.Exec(ctx, updateComposerAdvisoryDetailsByCve,
		arg.Cve,
		arg.Summary,
		arg.Description,
		arg.CvssScore,
		arg.CvssVector,
		arg.Cwes,
		arg.ExternalReferences,
		arg.DetailsSource,
	)
	return err
}

const updateComposerAdvisoryDetailsByGhsa = `-- name: UpdateComposerAdvisoryDetailsByGhsa :exec
UPDATE composer_advisory SET
  summary = $2,
  description = $3,
  cvss_score = $4,
  cvss_vector = $5,
  cwes = $6,
  external_references = $7,
  details_source = $8,
  details_synced_at = NOW(),
  updated_at = NOW()
WHERE ghsa_id = $1
  AND (details_synced_at IS NULL OR details_source = $8)
`

type UpdateComposerAdvisoryDetailsByGhsaParams struct {
	GhsaID             *string         `json:"ghsa_id"`
	Summary            *string         `json:"summary"`
	Description        *string         `json:"description"`
	CvssScore          *float64        `json:"cvss_score"`
	CvssVector         *string         `json:"cvss_vector"`
	Cwes               json.RawMessage `json:"cwes"`
	ExternalReferences json.RawMessage `json:"external_references"`
	DetailsSource      *string         `json:"details_source"`
}

func (q *Queries) UpdateComposerAdvisoryDetailsByGhsa(ctx context.Context, arg UpdateComposerAdvisoryDetailsByGhsaParams) error {
	_, err := q.db.Exec(ctx, updateComposerAdvisoryDetailsByGhsa,
		arg.GhsaID,
		arg.Summary,
		arg.Description,
		arg.CvssScore,
		arg.CvssVector,
		arg.Cwes,
		arg.ExternalReferences,
		arg.DetailsSource,
	)
	return err
}

const updateComposerAdvisoryEnrichment = `-- name: UpdateComposerAdvisoryEnrichment :one
UPDATE composer_advisory SET
  severity_override = $2,
  is_visible = $3,
  notes_public = $4,
  notes_internal = $5,
  remediation_summary = $6,
  remediation_url = $7,
  recommended_upgrade = $8,
  shopware_impact_summary = $9,
  affected_components = $10,
  tags = $11,
  enriched_at = NOW(),
  enriched_by = $12,
  updated_at = NOW()
WHERE advisory_id = $1
RETURNING advisory_id, title, link, cve, ghsa_id, severity, sources, reported_at, composer_repository, synced_at, created_at, updated_at, summary, description, cvss_score, cvss_vector, cwes, external_references, details_source, details_synced_at, github_synced_at, details_attempted_at, severity_override, is_visible, notes_public, notes_internal, remediation_summary, remediation_url, recommended_upgrade, shopware_impact_summary, affected_components, tags, enriched_at, enriched_by, first_patched_versions
`

type UpdateComposerAdvisoryEnrichmentParams struct {
	AdvisoryID            string   `json:"advisory_id"`
	SeverityOverride      *string  `json:"severity_override"`
	IsVisible             bool     `json:"is_visible"`
	NotesPublic           *string  `json:"notes_public"`
	NotesInternal         *string  `json:"notes_internal"`
	RemediationSummary    *string  `json:"remediation_summary"`
	RemediationUrl        *string  `json:"remediation_url"`
	RecommendedUpgrade    *string  `json:"recommended_upgrade"`
	ShopwareImpactSummary *string  `json:"shopware_impact_summary"`
	AffectedComponents    []string `json:"affected_components"`
	Tags                  []string `json:"tags"`
	EnrichedBy            *string  `json:"enriched_by"`
}

func (q *Queries) UpdateComposerAdvisoryEnrichment(ctx context.Context, arg UpdateComposerAdvisoryEnrichmentParams) (ComposerAdvisory, error) {
	row := q.db.QueryRow(ctx, updateComposerAdvisoryEnrichment,
		arg.AdvisoryID,
		arg.SeverityOverride,
		arg.IsVisible,
		arg.NotesPublic,
		arg.NotesInternal,
		arg.RemediationSummary,
		arg.RemediationUrl,
		arg.RecommendedUpgrade,
		arg.ShopwareImpactSummary,
		arg.AffectedComponents,
		arg.Tags,
		arg.EnrichedBy,
	)
	var i ComposerAdvisory
	err := row.Scan(
		&i.AdvisoryID,
		&i.Title,
		&i.Link,
		&i.Cve,
		&i.GhsaID,
		&i.Severity,
		&i.Sources,
		&i.ReportedAt,
		&i.ComposerRepository,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
		&i.Description,
		&i.CvssScore,
		&i.CvssVector,
		&i.Cwes,
		&i.ExternalReferences,
		&i.DetailsSource,
		&i.DetailsSyncedAt,
		&i.GithubSyncedAt,
		&i.DetailsAttemptedAt,
		&i.SeverityOverride,
		&i.IsVisible,
		&i.NotesPublic,
		&i.NotesInternal,
		&i.RemediationSummary,
		&i.RemediationUrl,
		&i.RecommendedUpgrade,
		&i.ShopwareImpactSummary,
		&i.AffectedComponents,
		&i.Tags,
		&i.EnrichedAt,
		&i.EnrichedBy,
		&i.FirstPatchedVersions,
	)
	return i, err
}

const updateComposerAdvisoryFirstPatchedByGhsa = `-- name: UpdateComposerAdvisoryFirstPatchedByGhsa :exec
UPDATE composer_advisory SET
  first_patched_versions = $2,
  updated_at = NOW()
WHERE ghsa_id = $1 AND first_patched_versions IS DISTINCT FROM $2
`

type UpdateComposerAdvisoryFirstPatchedByGhsaParams struct {
	GhsaID               *string         `json:"ghsa_id"`
	FirstPatchedVersions json.RawMessage `json:"first_patched_versions"`
}

// Written only by the GitHub enrichment, which is the sole source of patched
// versions. Kept separate from the details updates because the NVD path shares
// those and has no equivalent field.
func (q *Queries) UpdateComposerAdvisoryFirstPatchedByGhsa(ctx context.Context, arg UpdateComposerAdvisoryFirstPatchedByGhsaParams) error {
	_, err := q.db.Exec(ctx, updateComposerAdvisoryFirstPatchedByGhsa, arg.GhsaID, arg.FirstPatchedVersions)
	return err
}

const upsertComposerAdvisory = `-- name: UpsertComposerAdvisory :exec
INSERT INTO composer_advisory (
  advisory_id, title, link, cve, ghsa_id,
  severity, sources, reported_at, composer_repository,
  synced_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9,
  NOW(), NOW()
)
ON CONFLICT (advisory_id) DO UPDATE SET
  title = EXCLUDED.title,
  link = COALESCE(EXCLUDED.link, composer_advisory.link),
  cve = COALESCE(EXCLUDED.cve, composer_advisory.cve),
  ghsa_id = COALESCE(EXCLUDED.ghsa_id, composer_advisory.ghsa_id),
  severity = COALESCE(EXCLUDED.severity, composer_advisory.severity),
  sources = EXCLUDED.sources,
  reported_at = COALESCE(EXCLUDED.reported_at, composer_advisory.reported_at),
  composer_repository = COALESCE(EXCLUDED.composer_repository, composer_advisory.composer_repository),
  synced_at = NOW(),
  updated_at = NOW()
`

type UpsertComposerAdvisoryParams struct {
	AdvisoryID         string           `json:"advisory_id"`
	Title              string           `json:"title"`
	Link               *string          `json:"link"`
	Cve                *string          `json:"cve"`
	GhsaID             *string          `json:"ghsa_id"`
	Severity           *string          `json:"severity"`
	Sources            json.RawMessage  `json:"sources"`
	ReportedAt         pgtype.Timestamp `json:"reported_at"`
	ComposerRepository *string          `json:"composer_repository"`
}

func (q *Queries) UpsertComposerAdvisory(ctx context.Context, arg UpsertComposerAdvisoryParams) error {
	_, err := q.db.Exec(ctx, upsertComposerAdvisory,
		arg.AdvisoryID,
		arg.Title,
		arg.Link,
		arg.Cve,
		arg.GhsaID,
		arg.Severity,
		arg.Sources,
		arg.ReportedAt,
		arg.ComposerRepository,
	)
	return err
}

const upsertComposerAdvisoryPackage = `-- name: UpsertComposerAdvisoryPackage :exec
INSERT INTO composer_advisory_package (
  advisory_id, package_name, packagist_advisory_id, affected_versions, synced_at
) VALUES (
  $1, $2, $3, $4, NOW()
)
ON CONFLICT (advisory_id, package_name) DO UPDATE SET
  packagist_advisory_id = EXCLUDED.packagist_advisory_id,
  affected_versions = EXCLUDED.affected_versions,
  synced_at = NOW()
`

type UpsertComposerAdvisoryPackageParams struct {
	AdvisoryID          string `json:"advisory_id"`
	PackageName         string `json:"package_name"`
	PackagistAdvisoryID string `json:"packagist_advisory_id"`
	AffectedVersions    string `json:"affected_versions"`
}

func (q *Queries) UpsertComposerAdvisoryPackage(ctx context.Context, arg UpsertComposerAdvisoryPackageParams) error {
	_, err := q.db.Exec(ctx, upsertComposerAdvisoryPackage,
		arg.AdvisoryID,
		arg.PackageName,
		arg.PackagistAdvisoryID,
		arg.AffectedVersions,
	)
	return err
}

const upsertComposerAdvisorySyncState = `-- name: UpsertComposerAdvisorySyncState :exec
INSERT INTO composer_advisory_sync_state (
  id, last_updated_since, last_full_sync_at, last_incremental_sync_at, last_error, updated_at
) VALUES (
  1, $1, $2, $3, $4, NOW()
)
ON CONFLICT (id) DO UPDATE SET
  last_updated_since = EXCLUDED.last_updated_since,
  last_full_sync_at = COALESCE(EXCLUDED.last_full_sync_at, composer_advisory_sync_state.last_full_sync_at),
  last_incremental_sync_at = COALESCE(EXCLUDED.last_incremental_sync_at, composer_advisory_sync_state.last_incremental_sync_at),
  last_error = EXCLUDED.last_error,
  updated_at = NOW()
`

type UpsertComposerAdvisorySyncStateParams struct {
	LastUpdatedSince      *int64           `json:"last_updated_since"`
	LastFullSyncAt        pgtype.Timestamp `json:"last_full_sync_at"`
	LastIncrementalSyncAt pgtype.Timestamp `json:"last_incremental_sync_at"`
	LastError             *string          `json:"last_error"`
}

func (q *Queries) UpsertComposerAdvisorySyncState(ctx context.Context, arg UpsertComposerAdvisorySyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertComposerAdvisorySyncState,
		arg.LastUpdatedSince,
		arg.LastFullSyncAt,
		arg.LastIncrementalSyncAt,
		arg.LastError,
	)
	return err
}
