// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployment (shop_id, name, command, return_code, start_date, end_date, execution_time, composer, reference, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id
`

type CreateDeploymentParams struct {
	ShopID        int32            `json:"shop_id"`
	Name          string           `json:"name"`
	Command       string           `json:"command"`
	ReturnCode    int32            `json:"return_code"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	ExecutionTime float32          `json:"execution_time"`
	Composer      []byte           `json:"composer"`
	Reference     *string          `json:"reference"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (int32, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ShopID,
		arg.Name,
		arg.Command,
		arg.ReturnCode,
		arg.StartDate,
		arg.EndDate,
		arg.ExecutionTime,
		arg.Composer,
		arg.Reference,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployment WHERE id = $1 AND shop_id = $2
`

type DeleteDeploymentParams struct {
	ID     int32 `json:"id"`
	ShopID int32 `json:"shop_id"`
}

func (q *Queries) DeleteDeployment(ctx context.Context, arg DeleteDeploymentParams) error {
	_, err := q.db.Exec(ctx, deleteDeployment, arg.ID, arg.ShopID)
	return err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, shop_id, name, command, return_code, start_date, end_date, execution_time, composer, reference, created_at
FROM deployment WHERE id = $1 AND shop_id = $2
`

type GetDeploymentByIDParams struct {
	ID     int32 `json:"id"`
	ShopID int32 `json:"shop_id"`
}

func (q *Queries) GetDeploymentByID(ctx context.Context, arg GetDeploymentByIDParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, arg.ID, arg.ShopID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Command,
		&i.ReturnCode,
		&i.StartDate,
		&i.EndDate,
		&i.ExecutionTime,
		&i.Composer,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, shop_id, name, command, return_code, start_date, end_date, execution_time, reference, created_at
FROM deployment WHERE shop_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListDeploymentsParams struct {
	ShopID int32 `json:"shop_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDeploymentsRow struct {
	ID            int32            `json:"id"`
	ShopID        int32            `json:"shop_id"`
	Name          string           `json:"name"`
	Command       string           `json:"command"`
	ReturnCode    int32            `json:"return_code"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	ExecutionTime float32          `json:"execution_time"`
	Reference     *string          `json:"reference"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]ListDeploymentsRow, error) {
	rows, err := q.db.Query(ctx, listDeployments, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsRow{}
	for rows.Next() {
		var i ListDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Command,
			&i.ReturnCode,
			&i.StartDate,
			&i.EndDate,
			&i.ExecutionTime,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
