// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnvironmentDeployments = `-- name: CountEnvironmentDeployments :one
SELECT COUNT(*)::int FROM deployment WHERE environment_id = $1
`

func (q *Queries) CountEnvironmentDeployments(ctx context.Context, environmentID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countEnvironmentDeployments, environmentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environment (organization_id, shop_id, name, url, client_id, client_secret, shopware_version, environment_token, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id
`

type CreateEnvironmentParams struct {
	OrganizationID   string `json:"organization_id"`
	ShopID           int32  `json:"shop_id"`
	Name             string `json:"name"`
	Url              string `json:"url"`
	ClientID         string `json:"client_id"`
	ClientSecret     string `json:"client_secret"`
	ShopwareVersion  string `json:"shopware_version"`
	EnvironmentToken string `json:"environment_token"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (int32, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.OrganizationID,
		arg.ShopID,
		arg.Name,
		arg.Url,
		arg.ClientID,
		arg.ClientSecret,
		arg.ShopwareVersion,
		arg.EnvironmentToken,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environment WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const deleteEnvironmentChecks = `-- name: DeleteEnvironmentChecks :exec
DELETE FROM environment_check WHERE environment_id = $1
`

func (q *Queries) DeleteEnvironmentChecks(ctx context.Context, environmentID int32) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentChecks, environmentID)
	return err
}

const deleteEnvironmentExtensionsNotIn = `-- name: DeleteEnvironmentExtensionsNotIn :exec
DELETE FROM environment_extension WHERE environment_id = $1 AND name != ALL($2::text[])
`

type DeleteEnvironmentExtensionsNotInParams struct {
	EnvironmentID int32    `json:"environment_id"`
	Column2       []string `json:"column_2"`
}

func (q *Queries) DeleteEnvironmentExtensionsNotIn(ctx context.Context, arg DeleteEnvironmentExtensionsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentExtensionsNotIn, arg.EnvironmentID, arg.Column2)
	return err
}

const deleteEnvironmentQueuesNotIn = `-- name: DeleteEnvironmentQueuesNotIn :exec
DELETE FROM environment_queue WHERE environment_id = $1 AND name != ALL($2::text[])
`

type DeleteEnvironmentQueuesNotInParams struct {
	EnvironmentID int32    `json:"environment_id"`
	Column2       []string `json:"column_2"`
}

func (q *Queries) DeleteEnvironmentQueuesNotIn(ctx context.Context, arg DeleteEnvironmentQueuesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentQueuesNotIn, arg.EnvironmentID, arg.Column2)
	return err
}

const deleteEnvironmentScheduledTasksNotIn = `-- name: DeleteEnvironmentScheduledTasksNotIn :exec
DELETE FROM environment_scheduled_task WHERE environment_id = $1 AND task_id != ALL($2::text[])
`

type DeleteEnvironmentScheduledTasksNotInParams struct {
	EnvironmentID int32    `json:"environment_id"`
	Column2       []string `json:"column_2"`
}

func (q *Queries) DeleteEnvironmentScheduledTasksNotIn(ctx context.Context, arg DeleteEnvironmentScheduledTasksNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentScheduledTasksNotIn, arg.EnvironmentID, arg.Column2)
	return err
}

const getAllEnvironments = `-- name: GetAllEnvironments :many
SELECT e.id, e.name, e.url, e.client_id, e.client_secret, e.shopware_version,
       e.organization_id, e.ignores, e.last_scraped_at, e.last_scraped_error,
       e.connection_issue_count, e.environment_token, e.sitespeed_enabled, e.sitespeed_urls
FROM environment e
`

type GetAllEnvironmentsRow struct {
	ID                   int32            `json:"id"`
	Name                 string           `json:"name"`
	Url                  string           `json:"url"`
	ClientID             string           `json:"client_id"`
	ClientSecret         string           `json:"client_secret"`
	ShopwareVersion      string           `json:"shopware_version"`
	OrganizationID       string           `json:"organization_id"`
	Ignores              json.RawMessage  `json:"ignores"`
	LastScrapedAt        pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError     *string          `json:"last_scraped_error"`
	ConnectionIssueCount int32            `json:"connection_issue_count"`
	EnvironmentToken     string           `json:"environment_token"`
	SitespeedEnabled     bool             `json:"sitespeed_enabled"`
	SitespeedUrls        json.RawMessage  `json:"sitespeed_urls"`
}

func (q *Queries) GetAllEnvironments(ctx context.Context) ([]GetAllEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, getAllEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllEnvironmentsRow{}
	for rows.Next() {
		var i GetAllEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.ClientID,
			&i.ClientSecret,
			&i.ShopwareVersion,
			&i.OrganizationID,
			&i.Ignores,
			&i.LastScrapedAt,
			&i.LastScrapedError,
			&i.ConnectionIssueCount,
			&i.EnvironmentToken,
			&i.SitespeedEnabled,
			&i.SitespeedUrls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT e.id, e.organization_id, e.shop_id, e.name, e.status, e.url, e.favicon, e.client_id, e.client_secret, e.shopware_version, e.last_scraped_at, e.last_scraped_error, e.ignores, e.environment_image, e.last_changelog, e.active_deployment_id, e.connection_issue_count, e.sitespeed_enabled, e.sitespeed_urls, e.environment_token, e.created_at, o.name AS organization_name, s.name AS shop_name, s.description AS shop_description
FROM environment e
JOIN organization o ON o.id = e.organization_id
LEFT JOIN shop s ON s.id = e.shop_id
WHERE e.id = $1
`

type GetEnvironmentByIDRow struct {
	ID                   int32            `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	ShopID               int32            `json:"shop_id"`
	Name                 string           `json:"name"`
	Status               string           `json:"status"`
	Url                  string           `json:"url"`
	Favicon              *string          `json:"favicon"`
	ClientID             string           `json:"client_id"`
	ClientSecret         string           `json:"client_secret"`
	ShopwareVersion      string           `json:"shopware_version"`
	LastScrapedAt        pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError     *string          `json:"last_scraped_error"`
	Ignores              json.RawMessage  `json:"ignores"`
	EnvironmentImage     *string          `json:"environment_image"`
	LastChangelog        []byte           `json:"last_changelog"`
	ActiveDeploymentID   *int32           `json:"active_deployment_id"`
	ConnectionIssueCount int32            `json:"connection_issue_count"`
	SitespeedEnabled     bool             `json:"sitespeed_enabled"`
	SitespeedUrls        json.RawMessage  `json:"sitespeed_urls"`
	EnvironmentToken     string           `json:"environment_token"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	OrganizationName     string           `json:"organization_name"`
	ShopName             *string          `json:"shop_name"`
	ShopDescription      *string          `json:"shop_description"`
}

func (q *Queries) GetEnvironmentByID(ctx context.Context, id int32) (GetEnvironmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i GetEnvironmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ShopID,
		&i.Name,
		&i.Status,
		&i.Url,
		&i.Favicon,
		&i.ClientID,
		&i.ClientSecret,
		&i.ShopwareVersion,
		&i.LastScrapedAt,
		&i.LastScrapedError,
		&i.Ignores,
		&i.EnvironmentImage,
		&i.LastChangelog,
		&i.ActiveDeploymentID,
		&i.ConnectionIssueCount,
		&i.SitespeedEnabled,
		&i.SitespeedUrls,
		&i.EnvironmentToken,
		&i.CreatedAt,
		&i.OrganizationName,
		&i.ShopName,
		&i.ShopDescription,
	)
	return i, err
}

const getEnvironmentCache = `-- name: GetEnvironmentCache :one
SELECT id, environment_id, environment, http_cache, cache_adapter FROM environment_cache WHERE environment_id = $1
`

func (q *Queries) GetEnvironmentCache(ctx context.Context, environmentID int32) (EnvironmentCache, error) {
	row := q.db.QueryRow(ctx, getEnvironmentCache, environmentID)
	var i EnvironmentCache
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Environment,
		&i.HttpCache,
		&i.CacheAdapter,
	)
	return i, err
}

const getEnvironmentChangelogs = `-- name: GetEnvironmentChangelogs :many
SELECT id, environment_id, extensions, old_shopware_version, new_shopware_version, date
FROM environment_changelog WHERE environment_id = $1 ORDER BY date DESC LIMIT 10
`

func (q *Queries) GetEnvironmentChangelogs(ctx context.Context, environmentID *int32) ([]EnvironmentChangelog, error) {
	rows, err := q.db.Query(ctx, getEnvironmentChangelogs, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentChangelog{}
	for rows.Next() {
		var i EnvironmentChangelog
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Extensions,
			&i.OldShopwareVersion,
			&i.NewShopwareVersion,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentChecks = `-- name: GetEnvironmentChecks :many
SELECT id, environment_id, check_id, level, message, source, link FROM environment_check WHERE environment_id = $1
`

func (q *Queries) GetEnvironmentChecks(ctx context.Context, environmentID int32) ([]EnvironmentCheck, error) {
	rows, err := q.db.Query(ctx, getEnvironmentChecks, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentCheck{}
	for rows.Next() {
		var i EnvironmentCheck
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.CheckID,
			&i.Level,
			&i.Message,
			&i.Source,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentCredentials = `-- name: GetEnvironmentCredentials :one
SELECT id, url, client_id, client_secret, environment_token FROM environment WHERE id = $1
`

type GetEnvironmentCredentialsRow struct {
	ID               int32  `json:"id"`
	Url              string `json:"url"`
	ClientID         string `json:"client_id"`
	ClientSecret     string `json:"client_secret"`
	EnvironmentToken string `json:"environment_token"`
}

func (q *Queries) GetEnvironmentCredentials(ctx context.Context, id int32) (GetEnvironmentCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentCredentials, id)
	var i GetEnvironmentCredentialsRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.ClientID,
		&i.ClientSecret,
		&i.EnvironmentToken,
	)
	return i, err
}

const getEnvironmentExtensions = `-- name: GetEnvironmentExtensions :many
SELECT id, environment_id, name, label, active, version, latest_version, installed, rating_average, store_link, changelog, installed_at
FROM environment_extension WHERE environment_id = $1 ORDER BY name
`

func (q *Queries) GetEnvironmentExtensions(ctx context.Context, environmentID int32) ([]EnvironmentExtension, error) {
	rows, err := q.db.Query(ctx, getEnvironmentExtensions, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentExtension{}
	for rows.Next() {
		var i EnvironmentExtension
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Label,
			&i.Active,
			&i.Version,
			&i.LatestVersion,
			&i.Installed,
			&i.RatingAverage,
			&i.StoreLink,
			&i.Changelog,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentForScrape = `-- name: GetEnvironmentForScrape :one
SELECT e.id, e.name, e.url, e.client_id, e.client_secret, e.shopware_version,
       e.organization_id, e.ignores, e.last_scraped_at, e.last_scraped_error,
       e.connection_issue_count, e.environment_token, e.sitespeed_enabled, e.sitespeed_urls
FROM environment e WHERE e.id = $1
`

type GetEnvironmentForScrapeRow struct {
	ID                   int32            `json:"id"`
	Name                 string           `json:"name"`
	Url                  string           `json:"url"`
	ClientID             string           `json:"client_id"`
	ClientSecret         string           `json:"client_secret"`
	ShopwareVersion      string           `json:"shopware_version"`
	OrganizationID       string           `json:"organization_id"`
	Ignores              json.RawMessage  `json:"ignores"`
	LastScrapedAt        pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError     *string          `json:"last_scraped_error"`
	ConnectionIssueCount int32            `json:"connection_issue_count"`
	EnvironmentToken     string           `json:"environment_token"`
	SitespeedEnabled     bool             `json:"sitespeed_enabled"`
	SitespeedUrls        json.RawMessage  `json:"sitespeed_urls"`
}

func (q *Queries) GetEnvironmentForScrape(ctx context.Context, id int32) (GetEnvironmentForScrapeRow, error) {
	row := q.db.QueryRow(ctx, getEnvironmentForScrape, id)
	var i GetEnvironmentForScrapeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ClientID,
		&i.ClientSecret,
		&i.ShopwareVersion,
		&i.OrganizationID,
		&i.Ignores,
		&i.LastScrapedAt,
		&i.LastScrapedError,
		&i.ConnectionIssueCount,
		&i.EnvironmentToken,
		&i.SitespeedEnabled,
		&i.SitespeedUrls,
	)
	return i, err
}

const getEnvironmentNotificationSubscribers = `-- name: GetEnvironmentNotificationSubscribers :many
SELECT u.id, u.name, u.email
FROM "user" u
JOIN member m ON m.user_id = u.id
WHERE m.organization_id = $1
  AND u.notifications @> to_jsonb(ARRAY['environment-' || $2::text])::jsonb
`

type GetEnvironmentNotificationSubscribersParams struct {
	OrganizationID string `json:"organization_id"`
	EnvironmentID  string `json:"environment_id"`
}

type GetEnvironmentNotificationSubscribersRow struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) GetEnvironmentNotificationSubscribers(ctx context.Context, arg GetEnvironmentNotificationSubscribersParams) ([]GetEnvironmentNotificationSubscribersRow, error) {
	rows, err := q.db.Query(ctx, getEnvironmentNotificationSubscribers, arg.OrganizationID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnvironmentNotificationSubscribersRow{}
	for rows.Next() {
		var i GetEnvironmentNotificationSubscribersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentQueues = `-- name: GetEnvironmentQueues :many
SELECT id, environment_id, name, size FROM environment_queue WHERE environment_id = $1 ORDER BY name
`

func (q *Queries) GetEnvironmentQueues(ctx context.Context, environmentID int32) ([]EnvironmentQueue, error) {
	rows, err := q.db.Query(ctx, getEnvironmentQueues, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentQueue{}
	for rows.Next() {
		var i EnvironmentQueue
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentScheduledTasks = `-- name: GetEnvironmentScheduledTasks :many
SELECT id, environment_id, task_id, name, status, interval, overdue, last_execution_time, next_execution_time
FROM environment_scheduled_task WHERE environment_id = $1 ORDER BY name
`

func (q *Queries) GetEnvironmentScheduledTasks(ctx context.Context, environmentID int32) ([]EnvironmentScheduledTask, error) {
	rows, err := q.db.Query(ctx, getEnvironmentScheduledTasks, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentScheduledTask{}
	for rows.Next() {
		var i EnvironmentScheduledTask
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.TaskID,
			&i.Name,
			&i.Status,
			&i.Interval,
			&i.Overdue,
			&i.LastExecutionTime,
			&i.NextExecutionTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentSitespeeds = `-- name: GetEnvironmentSitespeeds :many
SELECT id, environment_id, deployment_id, created_at, ttfb, fully_loaded, largest_contentful_paint, first_contentful_paint, cumulative_layout_shift, transfer_size
FROM environment_sitespeed WHERE environment_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) GetEnvironmentSitespeeds(ctx context.Context, environmentID *int32) ([]EnvironmentSitespeed, error) {
	rows, err := q.db.Query(ctx, getEnvironmentSitespeeds, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentSitespeed{}
	for rows.Next() {
		var i EnvironmentSitespeed
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.DeploymentID,
			&i.CreatedAt,
			&i.Ttfb,
			&i.FullyLoaded,
			&i.LargestContentfulPaint,
			&i.FirstContentfulPaint,
			&i.CumulativeLayoutShift,
			&i.TransferSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentsWithSitespeedEnabled = `-- name: GetEnvironmentsWithSitespeedEnabled :many
SELECT e.id, e.url, e.sitespeed_urls, e.active_deployment_id, e.environment_token FROM environment e WHERE e.sitespeed_enabled = true
`

type GetEnvironmentsWithSitespeedEnabledRow struct {
	ID                 int32           `json:"id"`
	Url                string          `json:"url"`
	SitespeedUrls      json.RawMessage `json:"sitespeed_urls"`
	ActiveDeploymentID *int32          `json:"active_deployment_id"`
	EnvironmentToken   string          `json:"environment_token"`
}

func (q *Queries) GetEnvironmentsWithSitespeedEnabled(ctx context.Context) ([]GetEnvironmentsWithSitespeedEnabledRow, error) {
	rows, err := q.db.Query(ctx, getEnvironmentsWithSitespeedEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnvironmentsWithSitespeedEnabledRow{}
	for rows.Next() {
		var i GetEnvironmentsWithSitespeedEnabledRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.SitespeedUrls,
			&i.ActiveDeploymentID,
			&i.EnvironmentToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEnvironmentChangelog = `-- name: InsertEnvironmentChangelog :exec
INSERT INTO environment_changelog (environment_id, extensions, old_shopware_version, new_shopware_version, date)
VALUES ($1, $2, $3, $4, NOW())
`

type InsertEnvironmentChangelogParams struct {
	EnvironmentID      *int32          `json:"environment_id"`
	Extensions         json.RawMessage `json:"extensions"`
	OldShopwareVersion *string         `json:"old_shopware_version"`
	NewShopwareVersion *string         `json:"new_shopware_version"`
}

func (q *Queries) InsertEnvironmentChangelog(ctx context.Context, arg InsertEnvironmentChangelogParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentChangelog,
		arg.EnvironmentID,
		arg.Extensions,
		arg.OldShopwareVersion,
		arg.NewShopwareVersion,
	)
	return err
}

const insertEnvironmentCheck = `-- name: InsertEnvironmentCheck :exec
INSERT INTO environment_check (environment_id, check_id, level, message, source, link)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (environment_id, check_id) DO UPDATE SET level = $3, message = $4, source = $5, link = $6
`

type InsertEnvironmentCheckParams struct {
	EnvironmentID int32   `json:"environment_id"`
	CheckID       string  `json:"check_id"`
	Level         string  `json:"level"`
	Message       string  `json:"message"`
	Source        string  `json:"source"`
	Link          *string `json:"link"`
}

func (q *Queries) InsertEnvironmentCheck(ctx context.Context, arg InsertEnvironmentCheckParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentCheck,
		arg.EnvironmentID,
		arg.CheckID,
		arg.Level,
		arg.Message,
		arg.Source,
		arg.Link,
	)
	return err
}

const insertEnvironmentSitespeed = `-- name: InsertEnvironmentSitespeed :exec
INSERT INTO environment_sitespeed (environment_id, deployment_id, created_at, ttfb, fully_loaded, largest_contentful_paint, first_contentful_paint, cumulative_layout_shift, transfer_size)
VALUES ($1, $2, NOW(), $3, $4, $5, $6, $7, $8)
`

type InsertEnvironmentSitespeedParams struct {
	EnvironmentID          *int32   `json:"environment_id"`
	DeploymentID           *int32   `json:"deployment_id"`
	Ttfb                   *int32   `json:"ttfb"`
	FullyLoaded            *int32   `json:"fully_loaded"`
	LargestContentfulPaint *int32   `json:"largest_contentful_paint"`
	FirstContentfulPaint   *int32   `json:"first_contentful_paint"`
	CumulativeLayoutShift  *float32 `json:"cumulative_layout_shift"`
	TransferSize           *int32   `json:"transfer_size"`
}

func (q *Queries) InsertEnvironmentSitespeed(ctx context.Context, arg InsertEnvironmentSitespeedParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentSitespeed,
		arg.EnvironmentID,
		arg.DeploymentID,
		arg.Ttfb,
		arg.FullyLoaded,
		arg.LargestContentfulPaint,
		arg.FirstContentfulPaint,
		arg.CumulativeLayoutShift,
		arg.TransferSize,
	)
	return err
}

const listEnvironmentsByOrganization = `-- name: ListEnvironmentsByOrganization :many
SELECT e.id, e.name, e.url, e.favicon, e.status, e.shopware_version,
       e.last_scraped_at, e.last_scraped_error, e.created_at, e.shop_id, e.organization_id,
       o.name AS organization_name,
       s.name AS shop_name, s.description AS shop_description
FROM environment e
JOIN organization o ON o.id = e.organization_id
LEFT JOIN shop s ON s.id = e.shop_id
WHERE e.organization_id = $1
ORDER BY e.name
`

type ListEnvironmentsByOrganizationRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Url              string           `json:"url"`
	Favicon          *string          `json:"favicon"`
	Status           string           `json:"status"`
	ShopwareVersion  string           `json:"shopware_version"`
	LastScrapedAt    pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError *string          `json:"last_scraped_error"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	ShopID           int32            `json:"shop_id"`
	OrganizationID   string           `json:"organization_id"`
	OrganizationName string           `json:"organization_name"`
	ShopName         *string          `json:"shop_name"`
	ShopDescription  *string          `json:"shop_description"`
}

func (q *Queries) ListEnvironmentsByOrganization(ctx context.Context, organizationID string) ([]ListEnvironmentsByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsByOrganizationRow{}
	for rows.Next() {
		var i ListEnvironmentsByOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Favicon,
			&i.Status,
			&i.ShopwareVersion,
			&i.LastScrapedAt,
			&i.LastScrapedError,
			&i.CreatedAt,
			&i.ShopID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.ShopName,
			&i.ShopDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :exec
UPDATE environment SET name = $1, url = $2, client_id = $3, client_secret = $4, ignores = $5, shop_id = $6 WHERE id = $7
`

type UpdateEnvironmentParams struct {
	Name         string          `json:"name"`
	Url          string          `json:"url"`
	ClientID     string          `json:"client_id"`
	ClientSecret string          `json:"client_secret"`
	Ignores      json.RawMessage `json:"ignores"`
	ShopID       int32           `json:"shop_id"`
	ID           int32           `json:"id"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) error {
	_, err := q.db.Exec(ctx, updateEnvironment,
		arg.Name,
		arg.Url,
		arg.ClientID,
		arg.ClientSecret,
		arg.Ignores,
		arg.ShopID,
		arg.ID,
	)
	return err
}

const updateEnvironmentActiveDeployment = `-- name: UpdateEnvironmentActiveDeployment :exec
UPDATE environment SET active_deployment_id = $1 WHERE id = $2
`

type UpdateEnvironmentActiveDeploymentParams struct {
	ActiveDeploymentID *int32 `json:"active_deployment_id"`
	ID                 int32  `json:"id"`
}

func (q *Queries) UpdateEnvironmentActiveDeployment(ctx context.Context, arg UpdateEnvironmentActiveDeploymentParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentActiveDeployment, arg.ActiveDeploymentID, arg.ID)
	return err
}

const updateEnvironmentAfterScrape = `-- name: UpdateEnvironmentAfterScrape :exec
UPDATE environment SET status = $1, shopware_version = $2, last_scraped_at = NOW(), last_scraped_error = $3,
       favicon = $4, environment_image = $5, last_changelog = $6, connection_issue_count = 0
WHERE id = $7
`

type UpdateEnvironmentAfterScrapeParams struct {
	Status           string  `json:"status"`
	ShopwareVersion  string  `json:"shopware_version"`
	LastScrapedError *string `json:"last_scraped_error"`
	Favicon          *string `json:"favicon"`
	EnvironmentImage *string `json:"environment_image"`
	LastChangelog    []byte  `json:"last_changelog"`
	ID               int32   `json:"id"`
}

func (q *Queries) UpdateEnvironmentAfterScrape(ctx context.Context, arg UpdateEnvironmentAfterScrapeParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentAfterScrape,
		arg.Status,
		arg.ShopwareVersion,
		arg.LastScrapedError,
		arg.Favicon,
		arg.EnvironmentImage,
		arg.LastChangelog,
		arg.ID,
	)
	return err
}

const updateEnvironmentImage = `-- name: UpdateEnvironmentImage :exec
UPDATE environment SET environment_image = $1 WHERE id = $2
`

type UpdateEnvironmentImageParams struct {
	EnvironmentImage *string `json:"environment_image"`
	ID               int32   `json:"id"`
}

func (q *Queries) UpdateEnvironmentImage(ctx context.Context, arg UpdateEnvironmentImageParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentImage, arg.EnvironmentImage, arg.ID)
	return err
}

const updateEnvironmentName = `-- name: UpdateEnvironmentName :exec
UPDATE environment SET name = $1 WHERE id = $2
`

type UpdateEnvironmentNameParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateEnvironmentName(ctx context.Context, arg UpdateEnvironmentNameParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentName, arg.Name, arg.ID)
	return err
}

const updateEnvironmentScrapeError = `-- name: UpdateEnvironmentScrapeError :exec
UPDATE environment SET last_scraped_error = $1, last_scraped_at = NOW(), connection_issue_count = connection_issue_count + 1 WHERE id = $2
`

type UpdateEnvironmentScrapeErrorParams struct {
	LastScrapedError *string `json:"last_scraped_error"`
	ID               int32   `json:"id"`
}

func (q *Queries) UpdateEnvironmentScrapeError(ctx context.Context, arg UpdateEnvironmentScrapeErrorParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentScrapeError, arg.LastScrapedError, arg.ID)
	return err
}

const updateEnvironmentSitespeedSettings = `-- name: UpdateEnvironmentSitespeedSettings :exec
UPDATE environment SET sitespeed_enabled = $1, sitespeed_urls = $2 WHERE id = $3
`

type UpdateEnvironmentSitespeedSettingsParams struct {
	SitespeedEnabled bool            `json:"sitespeed_enabled"`
	SitespeedUrls    json.RawMessage `json:"sitespeed_urls"`
	ID               int32           `json:"id"`
}

func (q *Queries) UpdateEnvironmentSitespeedSettings(ctx context.Context, arg UpdateEnvironmentSitespeedSettingsParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentSitespeedSettings, arg.SitespeedEnabled, arg.SitespeedUrls, arg.ID)
	return err
}

const upsertEnvironmentCache = `-- name: UpsertEnvironmentCache :exec
INSERT INTO environment_cache (environment_id, environment, http_cache, cache_adapter)
VALUES ($1, $2, $3, $4)
ON CONFLICT (environment_id) DO UPDATE SET environment = $2, http_cache = $3, cache_adapter = $4
`

type UpsertEnvironmentCacheParams struct {
	EnvironmentID int32  `json:"environment_id"`
	Environment   string `json:"environment"`
	HttpCache     bool   `json:"http_cache"`
	CacheAdapter  string `json:"cache_adapter"`
}

func (q *Queries) UpsertEnvironmentCache(ctx context.Context, arg UpsertEnvironmentCacheParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentCache,
		arg.EnvironmentID,
		arg.Environment,
		arg.HttpCache,
		arg.CacheAdapter,
	)
	return err
}

const upsertEnvironmentExtension = `-- name: UpsertEnvironmentExtension :exec
INSERT INTO environment_extension (environment_id, name, label, active, version, latest_version, installed, rating_average, store_link, changelog, installed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (environment_id, name) DO UPDATE SET label = $3, active = $4, version = $5, latest_version = $6, installed = $7, rating_average = $8, store_link = $9, changelog = $10, installed_at = $11
`

type UpsertEnvironmentExtensionParams struct {
	EnvironmentID int32   `json:"environment_id"`
	Name          string  `json:"name"`
	Label         string  `json:"label"`
	Active        bool    `json:"active"`
	Version       string  `json:"version"`
	LatestVersion *string `json:"latest_version"`
	Installed     bool    `json:"installed"`
	RatingAverage *int32  `json:"rating_average"`
	StoreLink     *string `json:"store_link"`
	Changelog     []byte  `json:"changelog"`
	InstalledAt   *string `json:"installed_at"`
}

func (q *Queries) UpsertEnvironmentExtension(ctx context.Context, arg UpsertEnvironmentExtensionParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentExtension,
		arg.EnvironmentID,
		arg.Name,
		arg.Label,
		arg.Active,
		arg.Version,
		arg.LatestVersion,
		arg.Installed,
		arg.RatingAverage,
		arg.StoreLink,
		arg.Changelog,
		arg.InstalledAt,
	)
	return err
}

const upsertEnvironmentQueue = `-- name: UpsertEnvironmentQueue :exec
INSERT INTO environment_queue (environment_id, name, size) VALUES ($1, $2, $3)
ON CONFLICT (environment_id, name) DO UPDATE SET size = $3
`

type UpsertEnvironmentQueueParams struct {
	EnvironmentID int32  `json:"environment_id"`
	Name          string `json:"name"`
	Size          int32  `json:"size"`
}

func (q *Queries) UpsertEnvironmentQueue(ctx context.Context, arg UpsertEnvironmentQueueParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentQueue, arg.EnvironmentID, arg.Name, arg.Size)
	return err
}

const upsertEnvironmentScheduledTask = `-- name: UpsertEnvironmentScheduledTask :exec
INSERT INTO environment_scheduled_task (environment_id, task_id, name, status, interval, overdue, last_execution_time, next_execution_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (environment_id, task_id) DO UPDATE SET name = $3, status = $4, interval = $5, overdue = $6, last_execution_time = $7, next_execution_time = $8
`

type UpsertEnvironmentScheduledTaskParams struct {
	EnvironmentID     int32   `json:"environment_id"`
	TaskID            string  `json:"task_id"`
	Name              string  `json:"name"`
	Status            string  `json:"status"`
	Interval          int32   `json:"interval"`
	Overdue           bool    `json:"overdue"`
	LastExecutionTime *string `json:"last_execution_time"`
	NextExecutionTime *string `json:"next_execution_time"`
}

func (q *Queries) UpsertEnvironmentScheduledTask(ctx context.Context, arg UpsertEnvironmentScheduledTaskParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentScheduledTask,
		arg.EnvironmentID,
		arg.TaskID,
		arg.Name,
		arg.Status,
		arg.Interval,
		arg.Overdue,
		arg.LastExecutionTime,
		arg.NextExecutionTime,
	)
	return err
}
