// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment_sbom.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAffectedEnvironmentsForAdvisories = `-- name: CountAffectedEnvironmentsForAdvisories :many
SELECT advisory_id, COUNT(DISTINCT environment_id)::bigint AS environment_count
FROM environment_advisory_match
WHERE advisory_id = ANY($1::text[])
GROUP BY advisory_id
`

type CountAffectedEnvironmentsForAdvisoriesRow struct {
	AdvisoryID       string `json:"advisory_id"`
	EnvironmentCount int64  `json:"environment_count"`
}

// Global impact counts for admins (all tenants). Deliberately counts
// suppressed environments too: a suppression acknowledges exposure, it does
// not remove it, and the fleet-wide blast radius must not shrink because a
// tenant acknowledged an advisory.
func (q *Queries) CountAffectedEnvironmentsForAdvisories(ctx context.Context, dollar_1 []string) ([]CountAffectedEnvironmentsForAdvisoriesRow, error) {
	rows, err := q.db.Query(ctx, countAffectedEnvironmentsForAdvisories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAffectedEnvironmentsForAdvisoriesRow{}
	for rows.Next() {
		var i CountAffectedEnvironmentsForAdvisoriesRow
		if err := rows.Scan(&i.AdvisoryID, &i.EnvironmentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAffectedEnvironmentsForAdvisoriesInOrgs = `-- name: CountAffectedEnvironmentsForAdvisoriesInOrgs :many
SELECT m.advisory_id, COUNT(DISTINCT m.environment_id)::bigint AS environment_count
FROM environment_advisory_match m
JOIN environment e ON e.id = m.environment_id
WHERE m.advisory_id = ANY($1::text[]) AND e.organization_id = ANY($2::text[])
  AND NOT EXISTS (
    SELECT 1 FROM advisory_suppression s
    WHERE s.advisory_id = m.advisory_id
      AND s.shop_id = e.shop_id
      AND (s.environment_id IS NULL OR s.environment_id = e.id)
      AND s.revoked_at IS NULL
      AND (s.expires_at IS NULL OR s.expires_at > NOW())
  )
GROUP BY m.advisory_id
`

type CountAffectedEnvironmentsForAdvisoriesInOrgsParams struct {
	Column1 []string `json:"column_1"`
	Column2 []string `json:"column_2"`
}

type CountAffectedEnvironmentsForAdvisoriesInOrgsRow struct {
	AdvisoryID       string `json:"advisory_id"`
	EnvironmentCount int64  `json:"environment_count"`
}

// Per-advisory counts limited to the caller's organizations. Excludes
// suppressed environments with the same predicate as the scoped list queries,
// so the detail page's count agrees with the list badge it was opened from.
func (q *Queries) CountAffectedEnvironmentsForAdvisoriesInOrgs(ctx context.Context, arg CountAffectedEnvironmentsForAdvisoriesInOrgsParams) ([]CountAffectedEnvironmentsForAdvisoriesInOrgsRow, error) {
	rows, err := q.db.Query(ctx, countAffectedEnvironmentsForAdvisoriesInOrgs, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAffectedEnvironmentsForAdvisoriesInOrgsRow{}
	for rows.Next() {
		var i CountAffectedEnvironmentsForAdvisoriesInOrgsRow
		if err := rows.Scan(&i.AdvisoryID, &i.EnvironmentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countComposerAdvisoriesScoped = `-- name: CountComposerAdvisoriesScoped :one
SELECT
  COUNT(*)::int AS all_count,
  COUNT(*) FILTER (WHERE COALESCE(m.affected_count, 0) > 0)::int AS affected_count,
  COUNT(*) FILTER (WHERE COALESCE(m.suppressed_count, 0) > 0)::int AS suppressed_count
FROM composer_advisory a
LEFT JOIN LATERAL (
  SELECT
    COUNT(DISTINCT em.environment_id) FILTER (WHERE NOT em.is_suppressed) AS affected_count,
    COUNT(DISTINCT em.environment_id) FILTER (WHERE em.is_suppressed) AS suppressed_count
  FROM (
    SELECT
      em.environment_id,
      EXISTS (
        SELECT 1 FROM advisory_suppression s
        WHERE s.advisory_id = em.advisory_id
          AND s.shop_id = e.shop_id
          AND (s.environment_id IS NULL OR s.environment_id = e.id)
          AND s.revoked_at IS NULL
          AND (s.expires_at IS NULL OR s.expires_at > NOW())
      ) AS is_suppressed
    FROM environment_advisory_match em
    JOIN environment e ON e.id = em.environment_id
    WHERE em.advisory_id = a.advisory_id
      AND e.organization_id = ANY($1::text[])
  ) em
) m ON true
WHERE
  a.is_visible = true
  AND (
    $2::text IS NULL
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id AND p.package_name = $2
    )
  )
  AND (
    $3::text IS NULL
    OR lower(COALESCE(a.severity_override, a.severity, '')) = lower($3)
  )
  AND (
    $4::text IS NULL
    OR $4 = ANY(a.tags)
  )
  AND (
    $5::text IS NULL
    OR a.title ILIKE '%' || $5 || '%'
    OR COALESCE(a.cve, '') ILIKE '%' || $5 || '%'
    OR COALESCE(a.ghsa_id, '') ILIKE '%' || $5 || '%'
    OR a.advisory_id ILIKE '%' || $5 || '%'
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id
        AND (
          p.package_name ILIKE '%' || $5 || '%'
          OR p.packagist_advisory_id ILIKE '%' || $5 || '%'
        )
    )
  )
`

type CountComposerAdvisoriesScopedParams struct {
	OrganizationIds []string `json:"organization_ids"`
	PackageName     *string  `json:"package_name"`
	Severity        *string  `json:"severity"`
	Tag             *string  `json:"tag"`
	Search          *string  `json:"search"`
}

type CountComposerAdvisoriesScopedRow struct {
	AllCount        int32 `json:"all_count"`
	AffectedCount   int32 `json:"affected_count"`
	SuppressedCount int32 `json:"suppressed_count"`
}

// Scope tab badges: total matching the non-scope filters, how many of those
// affect the caller's environments, and how many are suppressed. All from one
// scan. The LATERAL below is intentionally identical to the one in
// ListComposerAdvisoriesScoped -- if they drift, the badge lies about the list.
func (q *Queries) CountComposerAdvisoriesScoped(ctx context.Context, arg CountComposerAdvisoriesScopedParams) (CountComposerAdvisoriesScopedRow, error) {
	row := q.db.QueryRow(ctx, countComposerAdvisoriesScoped,
		arg.OrganizationIds,
		arg.PackageName,
		arg.Severity,
		arg.Tag,
		arg.Search,
	)
	var i CountComposerAdvisoriesScopedRow
	err := row.Scan(&i.AllCount, &i.AffectedCount, &i.SuppressedCount)
	return i, err
}

const deleteEnvironmentAdvisoryMatches = `-- name: DeleteEnvironmentAdvisoryMatches :exec
DELETE FROM environment_advisory_match WHERE environment_id = $1
`

func (q *Queries) DeleteEnvironmentAdvisoryMatches(ctx context.Context, environmentID int32) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentAdvisoryMatches, environmentID)
	return err
}

const deleteEnvironmentSbomComponentsNotIn = `-- name: DeleteEnvironmentSbomComponentsNotIn :exec
DELETE FROM environment_sbom_component
WHERE environment_id = $1 AND package_name != ALL($2::text[])
`

type DeleteEnvironmentSbomComponentsNotInParams struct {
	EnvironmentID int32    `json:"environment_id"`
	Column2       []string `json:"column_2"`
}

func (q *Queries) DeleteEnvironmentSbomComponentsNotIn(ctx context.Context, arg DeleteEnvironmentSbomComponentsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentSbomComponentsNotIn, arg.EnvironmentID, arg.Column2)
	return err
}

const deleteStaleEnvironmentAdvisoryNotifications = `-- name: DeleteStaleEnvironmentAdvisoryNotifications :exec
DELETE FROM environment_advisory_notified n
WHERE n.environment_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM environment_advisory_match m
    WHERE m.environment_id = n.environment_id AND m.advisory_id = n.advisory_id
  )
`

// Drops markers for advisories the environment no longer matches, so an
// advisory that reappears later (package downgraded, range widened) alerts
// again instead of being silently treated as already-seen.
func (q *Queries) DeleteStaleEnvironmentAdvisoryNotifications(ctx context.Context, environmentID int32) error {
	_, err := q.db.Exec(ctx, deleteStaleEnvironmentAdvisoryNotifications, environmentID)
	return err
}

const getEnvironmentAdvisoryMatches = `-- name: GetEnvironmentAdvisoryMatches :many
SELECT m.advisory_id, m.package_name, m.installed_version, m.affected_versions, m.matched_at,
       a.title, a.cve, a.ghsa_id, a.severity, a.severity_override, a.link, a.remediation_url,
       a.cvss_score, a.recommended_upgrade
FROM environment_advisory_match m
JOIN composer_advisory a ON a.advisory_id = m.advisory_id
WHERE m.environment_id = $1 AND a.is_visible = true
ORDER BY a.cvss_score DESC NULLS LAST, m.advisory_id, m.package_name
`

type GetEnvironmentAdvisoryMatchesRow struct {
	AdvisoryID         string           `json:"advisory_id"`
	PackageName        string           `json:"package_name"`
	InstalledVersion   string           `json:"installed_version"`
	AffectedVersions   string           `json:"affected_versions"`
	MatchedAt          pgtype.Timestamp `json:"matched_at"`
	Title              string           `json:"title"`
	Cve                *string          `json:"cve"`
	GhsaID             *string          `json:"ghsa_id"`
	Severity           *string          `json:"severity"`
	SeverityOverride   *string          `json:"severity_override"`
	Link               *string          `json:"link"`
	RemediationUrl     *string          `json:"remediation_url"`
	CvssScore          *float64         `json:"cvss_score"`
	RecommendedUpgrade *string          `json:"recommended_upgrade"`
}

// Consumed by the rematch pass as its "already known" snapshot for
// notification dedup. Deliberately ignores suppressions (notify filters those
// itself); anything user-facing must add the suppression predicate the
// affected-environment queries below carry.
func (q *Queries) GetEnvironmentAdvisoryMatches(ctx context.Context, environmentID int32) ([]GetEnvironmentAdvisoryMatchesRow, error) {
	rows, err := q.db.Query(ctx, getEnvironmentAdvisoryMatches, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnvironmentAdvisoryMatchesRow{}
	for rows.Next() {
		var i GetEnvironmentAdvisoryMatchesRow
		if err := rows.Scan(
			&i.AdvisoryID,
			&i.PackageName,
			&i.InstalledVersion,
			&i.AffectedVersions,
			&i.MatchedAt,
			&i.Title,
			&i.Cve,
			&i.GhsaID,
			&i.Severity,
			&i.SeverityOverride,
			&i.Link,
			&i.RemediationUrl,
			&i.CvssScore,
			&i.RecommendedUpgrade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentSbomComponents = `-- name: GetEnvironmentSbomComponents :many
SELECT package_name, version, package_type, purl, is_dev, synced_at
FROM environment_sbom_component
WHERE environment_id = $1
ORDER BY package_name
`

type GetEnvironmentSbomComponentsRow struct {
	PackageName string           `json:"package_name"`
	Version     string           `json:"version"`
	PackageType *string          `json:"package_type"`
	Purl        *string          `json:"purl"`
	IsDev       bool             `json:"is_dev"`
	SyncedAt    pgtype.Timestamp `json:"synced_at"`
}

func (q *Queries) GetEnvironmentSbomComponents(ctx context.Context, environmentID int32) ([]GetEnvironmentSbomComponentsRow, error) {
	rows, err := q.db.Query(ctx, getEnvironmentSbomComponents, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnvironmentSbomComponentsRow{}
	for rows.Next() {
		var i GetEnvironmentSbomComponentsRow
		if err := rows.Scan(
			&i.PackageName,
			&i.Version,
			&i.PackageType,
			&i.Purl,
			&i.IsDev,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentSbomState = `-- name: GetEnvironmentSbomState :one
SELECT environment_id, supported, component_count, spec_version, serial_number, generated_at, last_synced_at, last_error FROM environment_sbom_state WHERE environment_id = $1
`

func (q *Queries) GetEnvironmentSbomState(ctx context.Context, environmentID int32) (EnvironmentSbomState, error) {
	row := q.db.QueryRow(ctx, getEnvironmentSbomState, environmentID)
	var i EnvironmentSbomState
	err := row.Scan(
		&i.EnvironmentID,
		&i.Supported,
		&i.ComponentCount,
		&i.SpecVersion,
		&i.SerialNumber,
		&i.GeneratedAt,
		&i.LastSyncedAt,
		&i.LastError,
	)
	return i, err
}

const listAffectedEnvironmentsForAdvisory = `-- name: ListAffectedEnvironmentsForAdvisory :many
SELECT m.environment_id, m.package_name, m.installed_version, m.affected_versions, m.matched_at,
       e.name AS environment_name, e.status AS environment_status,
       e.shopware_version, e.organization_id,
       s.id AS shop_id, s.name AS shop_name,
       o.name AS organization_name,
       EXISTS (
         SELECT 1 FROM advisory_suppression sup
         WHERE sup.advisory_id = m.advisory_id
           AND sup.shop_id = e.shop_id
           AND (sup.environment_id IS NULL OR sup.environment_id = e.id)
           AND sup.revoked_at IS NULL
           AND (sup.expires_at IS NULL OR sup.expires_at > NOW())
       ) AS suppressed
FROM environment_advisory_match m
JOIN environment e ON e.id = m.environment_id
JOIN shop s ON s.id = e.shop_id
JOIN organization o ON o.id = e.organization_id
WHERE m.advisory_id = $1 AND e.organization_id = ANY($2::text[])
ORDER BY o.name, s.name, e.name, m.package_name
`

type ListAffectedEnvironmentsForAdvisoryParams struct {
	AdvisoryID string   `json:"advisory_id"`
	Column2    []string `json:"column_2"`
}

type ListAffectedEnvironmentsForAdvisoryRow struct {
	EnvironmentID     int32            `json:"environment_id"`
	PackageName       string           `json:"package_name"`
	InstalledVersion  string           `json:"installed_version"`
	AffectedVersions  string           `json:"affected_versions"`
	MatchedAt         pgtype.Timestamp `json:"matched_at"`
	EnvironmentName   string           `json:"environment_name"`
	EnvironmentStatus string           `json:"environment_status"`
	ShopwareVersion   string           `json:"shopware_version"`
	OrganizationID    string           `json:"organization_id"`
	ShopID            int32            `json:"shop_id"`
	ShopName          string           `json:"shop_name"`
	OrganizationName  string           `json:"organization_name"`
	Suppressed        bool             `json:"suppressed"`
}

// Environments affected by one advisory, restricted to the caller's
// organizations. Advisories are global but shop exposure is tenant-scoped.
func (q *Queries) ListAffectedEnvironmentsForAdvisory(ctx context.Context, arg ListAffectedEnvironmentsForAdvisoryParams) ([]ListAffectedEnvironmentsForAdvisoryRow, error) {
	rows, err := q.db.Query(ctx, listAffectedEnvironmentsForAdvisory, arg.AdvisoryID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAffectedEnvironmentsForAdvisoryRow{}
	for rows.Next() {
		var i ListAffectedEnvironmentsForAdvisoryRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.PackageName,
			&i.InstalledVersion,
			&i.AffectedVersions,
			&i.MatchedAt,
			&i.EnvironmentName,
			&i.EnvironmentStatus,
			&i.ShopwareVersion,
			&i.OrganizationID,
			&i.ShopID,
			&i.ShopName,
			&i.OrganizationName,
			&i.Suppressed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComposerAdvisoriesScoped = `-- name: ListComposerAdvisoriesScoped :many
SELECT a.advisory_id, a.title, a.link, a.cve, a.ghsa_id, a.severity, a.sources, a.reported_at, a.composer_repository, a.synced_at, a.created_at, a.updated_at, a.summary, a.description, a.cvss_score, a.cvss_vector, a.cwes, a.external_references, a.details_source, a.details_synced_at, a.github_synced_at, a.details_attempted_at, a.severity_override, a.is_visible, a.notes_public, a.notes_internal, a.remediation_summary, a.remediation_url, a.recommended_upgrade, a.shopware_impact_summary, a.affected_components, a.tags, a.enriched_at, a.enriched_by, a.first_patched_versions,
       COALESCE(m.affected_count, 0)::int AS affected_count,
       COALESCE(m.suppressed_count, 0)::int AS suppressed_count
FROM composer_advisory a
LEFT JOIN LATERAL (
  SELECT
    COUNT(DISTINCT em.environment_id) FILTER (WHERE NOT em.is_suppressed) AS affected_count,
    COUNT(DISTINCT em.environment_id) FILTER (WHERE em.is_suppressed) AS suppressed_count
  FROM (
    SELECT
      em.environment_id,
      EXISTS (
        SELECT 1 FROM advisory_suppression s
        WHERE s.advisory_id = em.advisory_id
          AND s.shop_id = e.shop_id
          AND (s.environment_id IS NULL OR s.environment_id = e.id)
          AND s.revoked_at IS NULL
          AND (s.expires_at IS NULL OR s.expires_at > NOW())
      ) AS is_suppressed
    FROM environment_advisory_match em
    JOIN environment e ON e.id = em.environment_id
    WHERE em.advisory_id = a.advisory_id
      AND e.organization_id = ANY($1::text[])
  ) em
) m ON true
WHERE
  a.is_visible = true
  AND (NOT $2::boolean OR COALESCE(m.affected_count, 0) > 0)
  AND (NOT $3::boolean OR COALESCE(m.suppressed_count, 0) > 0)
  AND (
    $4::text IS NULL
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id AND p.package_name = $4
    )
  )
  AND (
    $5::text IS NULL
    OR lower(COALESCE(a.severity_override, a.severity, '')) = lower($5)
  )
  AND (
    $6::text IS NULL
    OR $6 = ANY(a.tags)
  )
  AND (
    $7::text IS NULL
    OR a.title ILIKE '%' || $7 || '%'
    OR COALESCE(a.cve, '') ILIKE '%' || $7 || '%'
    OR COALESCE(a.ghsa_id, '') ILIKE '%' || $7 || '%'
    OR a.advisory_id ILIKE '%' || $7 || '%'
    OR EXISTS (
      SELECT 1 FROM composer_advisory_package p
      WHERE p.advisory_id = a.advisory_id
        AND (
          p.package_name ILIKE '%' || $7 || '%'
          OR p.packagist_advisory_id ILIKE '%' || $7 || '%'
        )
    )
  )
ORDER BY
  -- Severity is stored as text, so map it to a rank rather than sorting
  -- alphabetically (which would put "critical" after "high").
  CASE WHEN $8::text = 'severity' THEN
    CASE lower(COALESCE(a.severity_override, a.severity, ''))
      WHEN 'critical' THEN 5
      WHEN 'high' THEN 4
      WHEN 'medium' THEN 3
      WHEN 'low' THEN 2
      WHEN 'none' THEN 1
      ELSE 0
    END
  END DESC NULLS LAST,
  CASE WHEN $8::text = 'affected' THEN COALESCE(m.affected_count, 0) END DESC NULLS LAST,
  CASE WHEN $8::text = 'cvss' THEN a.cvss_score END DESC NULLS LAST,
  a.reported_at DESC NULLS LAST,
  a.advisory_id DESC
LIMIT $10 OFFSET $9
`

type ListComposerAdvisoriesScopedParams struct {
	OrganizationIds []string `json:"organization_ids"`
	OnlyAffected    bool     `json:"only_affected"`
	OnlySuppressed  bool     `json:"only_suppressed"`
	PackageName     *string  `json:"package_name"`
	Severity        *string  `json:"severity"`
	Tag             *string  `json:"tag"`
	Search          *string  `json:"search"`
	Sort            string   `json:"sort"`
	Offset          int32    `json:"offset_"`
	Limit           int32    `json:"limit_"`
}

type ListComposerAdvisoriesScopedRow struct {
	AdvisoryID            string           `json:"advisory_id"`
	Title                 string           `json:"title"`
	Link                  *string          `json:"link"`
	Cve                   *string          `json:"cve"`
	GhsaID                *string          `json:"ghsa_id"`
	Severity              *string          `json:"severity"`
	Sources               json.RawMessage  `json:"sources"`
	ReportedAt            pgtype.Timestamp `json:"reported_at"`
	ComposerRepository    *string          `json:"composer_repository"`
	SyncedAt              pgtype.Timestamp `json:"synced_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	Summary               *string          `json:"summary"`
	Description           *string          `json:"description"`
	CvssScore             *float64         `json:"cvss_score"`
	CvssVector            *string          `json:"cvss_vector"`
	Cwes                  json.RawMessage  `json:"cwes"`
	ExternalReferences    json.RawMessage  `json:"external_references"`
	DetailsSource         *string          `json:"details_source"`
	DetailsSyncedAt       pgtype.Timestamp `json:"details_synced_at"`
	GithubSyncedAt        pgtype.Timestamp `json:"github_synced_at"`
	DetailsAttemptedAt    pgtype.Timestamp `json:"details_attempted_at"`
	SeverityOverride      *string          `json:"severity_override"`
	IsVisible             bool             `json:"is_visible"`
	NotesPublic           *string          `json:"notes_public"`
	NotesInternal         *string          `json:"notes_internal"`
	RemediationSummary    *string          `json:"remediation_summary"`
	RemediationUrl        *string          `json:"remediation_url"`
	RecommendedUpgrade    *string          `json:"recommended_upgrade"`
	ShopwareImpactSummary *string          `json:"shopware_impact_summary"`
	AffectedComponents    []string         `json:"affected_components"`
	Tags                  []string         `json:"tags"`
	EnrichedAt            pgtype.Timestamp `json:"enriched_at"`
	EnrichedBy            *string          `json:"enriched_by"`
	FirstPatchedVersions  json.RawMessage  `json:"first_patched_versions"`
	AffectedCount         int32            `json:"affected_count"`
	SuppressedCount       int32            `json:"suppressed_count"`
}

// User-facing advisory listing with an "affects my shops" scope, sorting, and
// a per-row affected-environment count.
//
// affected_count is computed once here (LEFT JOIN LATERAL) so the list can both
// sort by blast radius and render the count per row without an N+1. When
// only_affected is true the count doubles as the scope filter.
//
// Suppressed environments are excluded from affected_count, and suppressed_count
// counts them separately, so an acknowledged advisory leaves the "affecting my
// shops" to-do list without disappearing. The suppression predicate here MUST
// stay identical to the one in CountComposerAdvisoriesScoped, otherwise the
// scope tab badge disagrees with the list it labels.
func (q *Queries) ListComposerAdvisoriesScoped(ctx context.Context, arg ListComposerAdvisoriesScopedParams) ([]ListComposerAdvisoriesScopedRow, error) {
	rows, err := q.db.Query(ctx, listComposerAdvisoriesScoped,
		arg.OrganizationIds,
		arg.OnlyAffected,
		arg.OnlySuppressed,
		arg.PackageName,
		arg.Severity,
		arg.Tag,
		arg.Search,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComposerAdvisoriesScopedRow{}
	for rows.Next() {
		var i ListComposerAdvisoriesScopedRow
		if err := rows.Scan(
			&i.AdvisoryID,
			&i.Title,
			&i.Link,
			&i.Cve,
			&i.GhsaID,
			&i.Severity,
			&i.Sources,
			&i.ReportedAt,
			&i.ComposerRepository,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Summary,
			&i.Description,
			&i.CvssScore,
			&i.CvssVector,
			&i.Cwes,
			&i.ExternalReferences,
			&i.DetailsSource,
			&i.DetailsSyncedAt,
			&i.GithubSyncedAt,
			&i.DetailsAttemptedAt,
			&i.SeverityOverride,
			&i.IsVisible,
			&i.NotesPublic,
			&i.NotesInternal,
			&i.RemediationSummary,
			&i.RemediationUrl,
			&i.RecommendedUpgrade,
			&i.ShopwareImpactSummary,
			&i.AffectedComponents,
			&i.Tags,
			&i.EnrichedAt,
			&i.EnrichedBy,
			&i.FirstPatchedVersions,
			&i.AffectedCount,
			&i.SuppressedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSbomPackageNames = `-- name: ListDistinctSbomPackageNames :many
SELECT DISTINCT package_name FROM environment_sbom_component ORDER BY package_name
`

// Distinct package names across all environments: the input set for widening
// the Packagist advisory sync beyond shopware/*.
func (q *Queries) ListDistinctSbomPackageNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctSbomPackageNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var package_name string
		if err := rows.Scan(&package_name); err != nil {
			return nil, err
		}
		items = append(items, package_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentIDsWithSbom = `-- name: ListEnvironmentIDsWithSbom :many
SELECT DISTINCT environment_id FROM environment_sbom_component ORDER BY environment_id
`

// Every environment that has SBOM components, for the post-advisory-sync
// rematch pass.
func (q *Queries) ListEnvironmentIDsWithSbom(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, listEnvironmentIDsWithSbom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var environment_id int32
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifiedAdvisoryIDsForEnvironment = `-- name: ListNotifiedAdvisoryIDsForEnvironment :many
SELECT advisory_id FROM environment_advisory_notified WHERE environment_id = $1
`

// Advisories this environment's subscribers have already been alerted about.
// The rematch uses this — not the presence of a match row — to decide what is
// new, so an alert that failed to dispatch is retried on the next pass.
func (q *Queries) ListNotifiedAdvisoryIDsForEnvironment(ctx context.Context, environmentID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listNotifiedAdvisoryIDsForEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var advisory_id string
		if err := rows.Scan(&advisory_id); err != nil {
			return nil, err
		}
		items = append(items, advisory_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEnvironmentAdvisoriesNotified = `-- name: MarkEnvironmentAdvisoriesNotified :exec
INSERT INTO environment_advisory_notified (environment_id, advisory_id, notified_at)
SELECT $1, unnest($2::text[]), NOW()
ON CONFLICT (environment_id, advisory_id) DO NOTHING
`

type MarkEnvironmentAdvisoriesNotifiedParams struct {
	EnvironmentID int32    `json:"environment_id"`
	Column2       []string `json:"column_2"`
}

func (q *Queries) MarkEnvironmentAdvisoriesNotified(ctx context.Context, arg MarkEnvironmentAdvisoriesNotifiedParams) error {
	_, err := q.db.Exec(ctx, markEnvironmentAdvisoriesNotified, arg.EnvironmentID, arg.Column2)
	return err
}

const upsertEnvironmentAdvisoryMatch = `-- name: UpsertEnvironmentAdvisoryMatch :exec
INSERT INTO environment_advisory_match (
  environment_id, advisory_id, package_name, installed_version, affected_versions, matched_at
) VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (environment_id, advisory_id, package_name) DO UPDATE SET
  installed_version = $4, affected_versions = $5
WHERE (environment_advisory_match.installed_version, environment_advisory_match.affected_versions)
  IS DISTINCT FROM ($4, $5)
`

type UpsertEnvironmentAdvisoryMatchParams struct {
	EnvironmentID    int32  `json:"environment_id"`
	AdvisoryID       string `json:"advisory_id"`
	PackageName      string `json:"package_name"`
	InstalledVersion string `json:"installed_version"`
	AffectedVersions string `json:"affected_versions"`
}

func (q *Queries) UpsertEnvironmentAdvisoryMatch(ctx context.Context, arg UpsertEnvironmentAdvisoryMatchParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentAdvisoryMatch,
		arg.EnvironmentID,
		arg.AdvisoryID,
		arg.PackageName,
		arg.InstalledVersion,
		arg.AffectedVersions,
	)
	return err
}

const upsertEnvironmentSbomComponent = `-- name: UpsertEnvironmentSbomComponent :exec

INSERT INTO environment_sbom_component (
  environment_id, package_name, version, package_type, purl, is_dev, synced_at
) VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (environment_id, package_name) DO UPDATE SET
  version = $3, package_type = $4, purl = $5, is_dev = $6, synced_at = NOW()
WHERE (environment_sbom_component.version, environment_sbom_component.package_type,
       environment_sbom_component.purl, environment_sbom_component.is_dev)
  IS DISTINCT FROM ($3, $4, $5, $6)
`

type UpsertEnvironmentSbomComponentParams struct {
	EnvironmentID int32   `json:"environment_id"`
	PackageName   string  `json:"package_name"`
	Version       string  `json:"version"`
	PackageType   *string `json:"package_type"`
	Purl          *string `json:"purl"`
	IsDev         bool    `json:"is_dev"`
}

// Per-environment Composer SBOM inventory and the advisory matches derived
// from it. Like the extension upserts, the component upsert carries a
// WHERE ... IS DISTINCT FROM guard so unchanged rows produce no WAL churn on
// every scrape (a full composer.lock is ~200 rows per environment).
func (q *Queries) UpsertEnvironmentSbomComponent(ctx context.Context, arg UpsertEnvironmentSbomComponentParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentSbomComponent,
		arg.EnvironmentID,
		arg.PackageName,
		arg.Version,
		arg.PackageType,
		arg.Purl,
		arg.IsDev,
	)
	return err
}

const upsertEnvironmentSbomState = `-- name: UpsertEnvironmentSbomState :exec
INSERT INTO environment_sbom_state (
  environment_id, supported, component_count, spec_version, serial_number,
  generated_at, last_synced_at, last_error
) VALUES ($1, $2, $3, $4, $5, $6, NOW(), $7)
ON CONFLICT (environment_id) DO UPDATE SET
  supported = $2, component_count = $3, spec_version = $4, serial_number = $5,
  generated_at = $6, last_synced_at = NOW(), last_error = $7
`

type UpsertEnvironmentSbomStateParams struct {
	EnvironmentID  int32            `json:"environment_id"`
	Supported      bool             `json:"supported"`
	ComponentCount int32            `json:"component_count"`
	SpecVersion    *string          `json:"spec_version"`
	SerialNumber   *string          `json:"serial_number"`
	GeneratedAt    pgtype.Timestamp `json:"generated_at"`
	LastError      *string          `json:"last_error"`
}

func (q *Queries) UpsertEnvironmentSbomState(ctx context.Context, arg UpsertEnvironmentSbomStateParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentSbomState,
		arg.EnvironmentID,
		arg.Supported,
		arg.ComponentCount,
		arg.SpecVersion,
		arg.SerialNumber,
		arg.GeneratedAt,
		arg.LastError,
	)
	return err
}

const upsertEnvironmentSbomStateStatus = `-- name: UpsertEnvironmentSbomStateStatus :exec
INSERT INTO environment_sbom_state (
  environment_id, supported, component_count, last_synced_at, last_error
) VALUES ($1, $2, 0, NOW(), $3)
ON CONFLICT (environment_id) DO UPDATE SET
  supported = $2, last_synced_at = NOW(), last_error = $3
`

type UpsertEnvironmentSbomStateStatusParams struct {
	EnvironmentID int32   `json:"environment_id"`
	Supported     bool    `json:"supported"`
	LastError     *string `json:"last_error"`
}

// Status-only upsert for scrapes that collected nothing (unsupported endpoint
// or fetch failure): the previously collected component_count and provenance
// (spec_version, serial_number, generated_at) are preserved, matching the
// component rows which are also kept.
func (q *Queries) UpsertEnvironmentSbomStateStatus(ctx context.Context, arg UpsertEnvironmentSbomStateStatusParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentSbomStateStatus, arg.EnvironmentID, arg.Supported, arg.LastError)
	return err
}
