// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment_status_event.sql

package queries

import (
	"context"
	"encoding/json"
)

const insertEnvironmentStatusEvent = `-- name: InsertEnvironmentStatusEvent :exec
INSERT INTO environment_status_event (environment_id, old_status, new_status, reasons)
VALUES ($1, $2, $3, $4)
`

type InsertEnvironmentStatusEventParams struct {
	EnvironmentID int32           `json:"environment_id"`
	OldStatus     string          `json:"old_status"`
	NewStatus     string          `json:"new_status"`
	Reasons       json.RawMessage `json:"reasons"`
}

func (q *Queries) InsertEnvironmentStatusEvent(ctx context.Context, arg InsertEnvironmentStatusEventParams) error {
	_, err := q.db.Exec(ctx, insertEnvironmentStatusEvent,
		arg.EnvironmentID,
		arg.OldStatus,
		arg.NewStatus,
		arg.Reasons,
	)
	return err
}

const listEnvironmentStatusEvents = `-- name: ListEnvironmentStatusEvents :many
SELECT id, environment_id, old_status, new_status, reasons, created_at
FROM environment_status_event
WHERE environment_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListEnvironmentStatusEvents(ctx context.Context, environmentID int32) ([]EnvironmentStatusEvent, error) {
	rows, err := q.db.Query(ctx, listEnvironmentStatusEvents, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentStatusEvent{}
	for rows.Next() {
		var i EnvironmentStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.OldStatus,
			&i.NewStatus,
			&i.Reasons,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
