// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extension_report.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountExtensionReports = `-- name: AdminCountExtensionReports :one
SELECT COUNT(*)::int FROM store_extension_report r
WHERE ($1::text IS NULL OR r.status = $1)
`

func (q *Queries) AdminCountExtensionReports(ctx context.Context, status *string) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountExtensionReports, status)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const adminListExtensionReports = `-- name: AdminListExtensionReports :many
SELECT r.id, r.extension_name, set_en.label AS extension_label, r.category, r.comment,
       r.status, r.created_at, r.reviewed_at,
       r.user_id AS reporter_id, reporter.name AS reporter_name, reporter.email AS reporter_email,
       r.reviewed_by, reviewer.name AS reviewer_name
FROM store_extension_report r
JOIN store_extension se ON se.name = r.extension_name
LEFT JOIN store_extension_translation set_en ON set_en.extension_name = r.extension_name AND set_en.language = 'en'
LEFT JOIN "user" reporter ON reporter.id = r.user_id
LEFT JOIN "user" reviewer ON reviewer.id = r.reviewed_by
WHERE ($3::text IS NULL OR r.status = $3)
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListExtensionReportsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
}

type AdminListExtensionReportsRow struct {
	ID             int32            `json:"id"`
	ExtensionName  string           `json:"extension_name"`
	ExtensionLabel *string          `json:"extension_label"`
	Category       string           `json:"category"`
	Comment        string           `json:"comment"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	ReviewedAt     pgtype.Timestamp `json:"reviewed_at"`
	ReporterID     *string          `json:"reporter_id"`
	ReporterName   *string          `json:"reporter_name"`
	ReporterEmail  *string          `json:"reporter_email"`
	ReviewedBy     *string          `json:"reviewed_by"`
	ReviewerName   *string          `json:"reviewer_name"`
}

func (q *Queries) AdminListExtensionReports(ctx context.Context, arg AdminListExtensionReportsParams) ([]AdminListExtensionReportsRow, error) {
	rows, err := q.db.Query(ctx, adminListExtensionReports, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListExtensionReportsRow{}
	for rows.Next() {
		var i AdminListExtensionReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExtensionName,
			&i.ExtensionLabel,
			&i.Category,
			&i.Comment,
			&i.Status,
			&i.CreatedAt,
			&i.ReviewedAt,
			&i.ReporterID,
			&i.ReporterName,
			&i.ReporterEmail,
			&i.ReviewedBy,
			&i.ReviewerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUserPendingReportsForExtension = `-- name: CountUserPendingReportsForExtension :one
SELECT COUNT(*)::int FROM store_extension_report
WHERE extension_name = $1 AND user_id = $2 AND status = 'pending'
`

type CountUserPendingReportsForExtensionParams struct {
	ExtensionName string  `json:"extension_name"`
	UserID        *string `json:"user_id"`
}

func (q *Queries) CountUserPendingReportsForExtension(ctx context.Context, arg CountUserPendingReportsForExtensionParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUserPendingReportsForExtension, arg.ExtensionName, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createStoreExtensionReport = `-- name: CreateStoreExtensionReport :one
INSERT INTO store_extension_report (extension_name, user_id, category, comment)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateStoreExtensionReportParams struct {
	ExtensionName string  `json:"extension_name"`
	UserID        *string `json:"user_id"`
	Category      string  `json:"category"`
	Comment       string  `json:"comment"`
}

func (q *Queries) CreateStoreExtensionReport(ctx context.Context, arg CreateStoreExtensionReportParams) (int32, error) {
	row := q.db.QueryRow(ctx, createStoreExtensionReport,
		arg.ExtensionName,
		arg.UserID,
		arg.Category,
		arg.Comment,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getApprovedExtensionReportSummary = `-- name: GetApprovedExtensionReportSummary :many
SELECT extension_name, category, COUNT(*)::int AS count
FROM store_extension_report
WHERE status = 'approved'
GROUP BY extension_name, category
ORDER BY extension_name, category
`

type GetApprovedExtensionReportSummaryRow struct {
	ExtensionName string `json:"extension_name"`
	Category      string `json:"category"`
	Count         int32  `json:"count"`
}

// GetApprovedExtensionReportSummary returns, per extension, the number of
// approved reports grouped by category. Used to surface community warnings on
// the extension lists.
func (q *Queries) GetApprovedExtensionReportSummary(ctx context.Context) ([]GetApprovedExtensionReportSummaryRow, error) {
	rows, err := q.db.Query(ctx, getApprovedExtensionReportSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetApprovedExtensionReportSummaryRow{}
	for rows.Next() {
		var i GetApprovedExtensionReportSummaryRow
		if err := rows.Scan(&i.ExtensionName, &i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreExtensionReportByID = `-- name: GetStoreExtensionReportByID :one
SELECT id, extension_name, user_id, category, comment, status, reviewed_by, reviewed_at, created_at
FROM store_extension_report WHERE id = $1
`

func (q *Queries) GetStoreExtensionReportByID(ctx context.Context, id int32) (StoreExtensionReport, error) {
	row := q.db.QueryRow(ctx, getStoreExtensionReportByID, id)
	var i StoreExtensionReport
	err := row.Scan(
		&i.ID,
		&i.ExtensionName,
		&i.UserID,
		&i.Category,
		&i.Comment,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setStoreExtensionReportStatus = `-- name: SetStoreExtensionReportStatus :exec
UPDATE store_extension_report
SET status = $2, reviewed_by = $3, reviewed_at = NOW()
WHERE id = $1
`

type SetStoreExtensionReportStatusParams struct {
	ID         int32   `json:"id"`
	Status     string  `json:"status"`
	ReviewedBy *string `json:"reviewed_by"`
}

func (q *Queries) SetStoreExtensionReportStatus(ctx context.Context, arg SetStoreExtensionReportStatusParams) error {
	_, err := q.db.Exec(ctx, setStoreExtensionReportStatus, arg.ID, arg.Status, arg.ReviewedBy)
	return err
}

const storeExtensionExists = `-- name: StoreExtensionExists :one
SELECT COUNT(*) > 0 AS exists FROM store_extension WHERE name = $1
`

func (q *Queries) StoreExtensionExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, storeExtensionExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
