// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lock.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLock = `-- name: AcquireLock :exec
INSERT INTO lock (key, expires, created_at) VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET expires = $2, created_at = NOW()
WHERE lock.expires < NOW()
`

type AcquireLockParams struct {
	Key     string           `json:"key"`
	Expires pgtype.Timestamp `json:"expires"`
}

func (q *Queries) AcquireLock(ctx context.Context, arg AcquireLockParams) error {
	_, err := q.db.Exec(ctx, acquireLock, arg.Key, arg.Expires)
	return err
}

const cleanupExpiredInvitations = `-- name: CleanupExpiredInvitations :exec
DELETE FROM invitation WHERE expires_at < NOW() AND status = 'pending'
`

func (q *Queries) CleanupExpiredInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredInvitations)
	return err
}

const cleanupExpiredLocks = `-- name: CleanupExpiredLocks :exec
DELETE FROM lock WHERE expires < NOW()
`

func (q *Queries) CleanupExpiredLocks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredLocks)
	return err
}

const isLocked = `-- name: IsLocked :one
SELECT COUNT(*) > 0 AS locked FROM lock WHERE key = $1 AND expires > NOW()
`

func (q *Queries) IsLocked(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRow(ctx, isLocked, key)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const releaseLock = `-- name: ReleaseLock :exec
DELETE FROM lock WHERE key = $1
`

func (q *Queries) ReleaseLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, releaseLock, key)
	return err
}
