// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                string           `json:"user_id"`
	AccessToken           *string          `json:"access_token"`
	RefreshToken          *string          `json:"refresh_token"`
	IDToken               *string          `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 *string          `json:"scope"`
	Password              *string          `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type AdvisorySuppression struct {
	ID             int64            `json:"id"`
	OrganizationID string           `json:"organization_id"`
	ShopID         int32            `json:"shop_id"`
	EnvironmentID  *int32           `json:"environment_id"`
	AdvisoryID     string           `json:"advisory_id"`
	Reason         string           `json:"reason"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	CreatedBy      *string          `json:"created_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	RevokedAt      pgtype.Timestamp `json:"revoked_at"`
	RevokedBy      *string          `json:"revoked_by"`
}

type AuditLog struct {
	ID           int64            `json:"id"`
	ActorUserID  *string          `json:"actor_user_id"`
	Action       string           `json:"action"`
	TargetUserID *string          `json:"target_user_id"`
	Detail       *string          `json:"detail"`
	IpAddress    *string          `json:"ip_address"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type ComposerAdvisory struct {
	AdvisoryID            string           `json:"advisory_id"`
	Title                 string           `json:"title"`
	Link                  *string          `json:"link"`
	Cve                   *string          `json:"cve"`
	GhsaID                *string          `json:"ghsa_id"`
	Severity              *string          `json:"severity"`
	Sources               json.RawMessage  `json:"sources"`
	ReportedAt            pgtype.Timestamp `json:"reported_at"`
	ComposerRepository    *string          `json:"composer_repository"`
	SyncedAt              pgtype.Timestamp `json:"synced_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	Summary               *string          `json:"summary"`
	Description           *string          `json:"description"`
	CvssScore             *float64         `json:"cvss_score"`
	CvssVector            *string          `json:"cvss_vector"`
	Cwes                  json.RawMessage  `json:"cwes"`
	ExternalReferences    json.RawMessage  `json:"external_references"`
	DetailsSource         *string          `json:"details_source"`
	DetailsSyncedAt       pgtype.Timestamp `json:"details_synced_at"`
	GithubSyncedAt        pgtype.Timestamp `json:"github_synced_at"`
	DetailsAttemptedAt    pgtype.Timestamp `json:"details_attempted_at"`
	SeverityOverride      *string          `json:"severity_override"`
	IsVisible             bool             `json:"is_visible"`
	NotesPublic           *string          `json:"notes_public"`
	NotesInternal         *string          `json:"notes_internal"`
	RemediationSummary    *string          `json:"remediation_summary"`
	RemediationUrl        *string          `json:"remediation_url"`
	RecommendedUpgrade    *string          `json:"recommended_upgrade"`
	ShopwareImpactSummary *string          `json:"shopware_impact_summary"`
	AffectedComponents    []string         `json:"affected_components"`
	Tags                  []string         `json:"tags"`
	EnrichedAt            pgtype.Timestamp `json:"enriched_at"`
	EnrichedBy            *string          `json:"enriched_by"`
	FirstPatchedVersions  json.RawMessage  `json:"first_patched_versions"`
}

type ComposerAdvisoryPackage struct {
	AdvisoryID          string           `json:"advisory_id"`
	PackageName         string           `json:"package_name"`
	PackagistAdvisoryID string           `json:"packagist_advisory_id"`
	AffectedVersions    string           `json:"affected_versions"`
	SyncedAt            pgtype.Timestamp `json:"synced_at"`
}

type ComposerAdvisorySyncState struct {
	ID                    int32            `json:"id"`
	LastUpdatedSince      *int64           `json:"last_updated_since"`
	LastFullSyncAt        pgtype.Timestamp `json:"last_full_sync_at"`
	LastIncrementalSyncAt pgtype.Timestamp `json:"last_incremental_sync_at"`
	LastError             *string          `json:"last_error"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Deployment struct {
	ID            int32            `json:"id"`
	EnvironmentID int32            `json:"environment_id"`
	Name          string           `json:"name"`
	Command       string           `json:"command"`
	ReturnCode    int32            `json:"return_code"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	ExecutionTime float32          `json:"execution_time"`
	Composer      []byte           `json:"composer"`
	Reference     *string          `json:"reference"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Environment struct {
	ID                   int32            `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	ShopID               int32            `json:"shop_id"`
	Name                 string           `json:"name"`
	Status               string           `json:"status"`
	Url                  string           `json:"url"`
	Favicon              *string          `json:"favicon"`
	ClientID             string           `json:"client_id"`
	ClientSecret         string           `json:"client_secret"`
	ShopwareVersion      string           `json:"shopware_version"`
	LastScrapedAt        pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError     *string          `json:"last_scraped_error"`
	Ignores              json.RawMessage  `json:"ignores"`
	EnvironmentImage     *string          `json:"environment_image"`
	LastChangelog        []byte           `json:"last_changelog"`
	ActiveDeploymentID   *int32           `json:"active_deployment_id"`
	ConnectionIssueCount int32            `json:"connection_issue_count"`
	SitespeedEnabled     bool             `json:"sitespeed_enabled"`
	SitespeedUrls        json.RawMessage  `json:"sitespeed_urls"`
	EnvironmentToken     string           `json:"environment_token"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type EnvironmentAdvisoryMatch struct {
	EnvironmentID    int32            `json:"environment_id"`
	AdvisoryID       string           `json:"advisory_id"`
	PackageName      string           `json:"package_name"`
	InstalledVersion string           `json:"installed_version"`
	AffectedVersions string           `json:"affected_versions"`
	MatchedAt        pgtype.Timestamp `json:"matched_at"`
}

type EnvironmentAdvisoryNotified struct {
	EnvironmentID int32            `json:"environment_id"`
	AdvisoryID    string           `json:"advisory_id"`
	NotifiedAt    pgtype.Timestamp `json:"notified_at"`
}

type EnvironmentCache struct {
	ID            int32  `json:"id"`
	EnvironmentID int32  `json:"environment_id"`
	Environment   string `json:"environment"`
	HttpCache     bool   `json:"http_cache"`
	CacheAdapter  string `json:"cache_adapter"`
}

type EnvironmentChangelog struct {
	ID                 int32            `json:"id"`
	EnvironmentID      *int32           `json:"environment_id"`
	Extensions         json.RawMessage  `json:"extensions"`
	OldShopwareVersion *string          `json:"old_shopware_version"`
	NewShopwareVersion *string          `json:"new_shopware_version"`
	Date               pgtype.Timestamp `json:"date"`
}

type EnvironmentCheck struct {
	ID            int32           `json:"id"`
	EnvironmentID int32           `json:"environment_id"`
	CheckID       string          `json:"check_id"`
	Level         string          `json:"level"`
	Message       string          `json:"message"`
	MessageKey    *string         `json:"message_key"`
	Params        json.RawMessage `json:"params"`
	Source        string          `json:"source"`
	Link          *string         `json:"link"`
}

type EnvironmentExtension struct {
	ID            int32   `json:"id"`
	EnvironmentID int32   `json:"environment_id"`
	Name          string  `json:"name"`
	Label         string  `json:"label"`
	Active        bool    `json:"active"`
	Version       string  `json:"version"`
	LatestVersion *string `json:"latest_version"`
	Installed     bool    `json:"installed"`
	InstalledAt   *string `json:"installed_at"`
}

type EnvironmentQueue struct {
	ID            int32  `json:"id"`
	EnvironmentID int32  `json:"environment_id"`
	Name          string `json:"name"`
	Size          int32  `json:"size"`
}

type EnvironmentSbomComponent struct {
	EnvironmentID int32            `json:"environment_id"`
	PackageName   string           `json:"package_name"`
	Version       string           `json:"version"`
	PackageType   *string          `json:"package_type"`
	Purl          *string          `json:"purl"`
	IsDev         bool             `json:"is_dev"`
	SyncedAt      pgtype.Timestamp `json:"synced_at"`
}

type EnvironmentSbomState struct {
	EnvironmentID  int32            `json:"environment_id"`
	Supported      bool             `json:"supported"`
	ComponentCount int32            `json:"component_count"`
	SpecVersion    *string          `json:"spec_version"`
	SerialNumber   *string          `json:"serial_number"`
	GeneratedAt    pgtype.Timestamp `json:"generated_at"`
	LastSyncedAt   pgtype.Timestamp `json:"last_synced_at"`
	LastError      *string          `json:"last_error"`
}

type EnvironmentScheduledTask struct {
	ID                int32   `json:"id"`
	EnvironmentID     int32   `json:"environment_id"`
	TaskID            string  `json:"task_id"`
	Name              string  `json:"name"`
	Status            string  `json:"status"`
	Interval          int32   `json:"interval"`
	Overdue           bool    `json:"overdue"`
	LastExecutionTime *string `json:"last_execution_time"`
	NextExecutionTime *string `json:"next_execution_time"`
}

type EnvironmentSitespeed struct {
	ID                     int32            `json:"id"`
	EnvironmentID          *int32           `json:"environment_id"`
	DeploymentID           *int32           `json:"deployment_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	Ttfb                   *int32           `json:"ttfb"`
	FullyLoaded            *int32           `json:"fully_loaded"`
	LargestContentfulPaint *int32           `json:"largest_contentful_paint"`
	FirstContentfulPaint   *int32           `json:"first_contentful_paint"`
	CumulativeLayoutShift  *float32         `json:"cumulative_layout_shift"`
	TransferSize           *int32           `json:"transfer_size"`
}

type EnvironmentStatusEvent struct {
	ID            int32            `json:"id"`
	EnvironmentID int32            `json:"environment_id"`
	OldStatus     string           `json:"old_status"`
	NewStatus     string           `json:"new_status"`
	Reasons       json.RawMessage  `json:"reasons"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type EnvironmentStoreExtension struct {
	ID            int32   `json:"id"`
	EnvironmentID int32   `json:"environment_id"`
	ExtensionName string  `json:"extension_name"`
	Label         string  `json:"label"`
	Version       string  `json:"version"`
	LatestVersion *string `json:"latest_version"`
	Active        bool    `json:"active"`
	Installed     bool    `json:"installed"`
	InstalledAt   *string `json:"installed_at"`
}

type EnvironmentUptime struct {
	EnvironmentID        int32            `json:"environment_id"`
	Enabled              bool             `json:"enabled"`
	Url                  *string          `json:"url"`
	IntervalSeconds      int32            `json:"interval_seconds"`
	ExpectedStatus       int32            `json:"expected_status"`
	ContentMatch         *string          `json:"content_match"`
	FailureThreshold     int32            `json:"failure_threshold"`
	RecoveryThreshold    int32            `json:"recovery_threshold"`
	Status               string           `json:"status"`
	ConsecutiveFailures  int32            `json:"consecutive_failures"`
	ConsecutiveSuccesses int32            `json:"consecutive_successes"`
	NextCheckAt          pgtype.Timestamp `json:"next_check_at"`
	LastCheckedAt        pgtype.Timestamp `json:"last_checked_at"`
	LastStatusCode       *int32           `json:"last_status_code"`
	LastLatencyMs        *int32           `json:"last_latency_ms"`
	LastError            *string          `json:"last_error"`
}

type EnvironmentUptimeEvent struct {
	ID            int32            `json:"id"`
	EnvironmentID int32            `json:"environment_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	ResolvedAt    pgtype.Timestamp `json:"resolved_at"`
	StatusCode    *int32           `json:"status_code"`
	LatencyMs     *int32           `json:"latency_ms"`
	Error         *string          `json:"error"`
}

type EnvironmentUptimeRollupDaily struct {
	EnvironmentID int32       `json:"environment_id"`
	Day           pgtype.Date `json:"day"`
	UpSeconds     int32       `json:"up_seconds"`
	DownSeconds   int32       `json:"down_seconds"`
	PausedSeconds int32       `json:"paused_seconds"`
	NodataSeconds int32       `json:"nodata_seconds"`
	LatencyAvgMs  *int32      `json:"latency_avg_ms"`
	LatencyP95Ms  *int32      `json:"latency_p95_ms"`
}

type EnvironmentUptimeRollupHourly struct {
	EnvironmentID  int32            `json:"environment_id"`
	Hour           pgtype.Timestamp `json:"hour"`
	ProbesExpected int32            `json:"probes_expected"`
	ProbesRun      int32            `json:"probes_run"`
	ProbesOk       int32            `json:"probes_ok"`
	PausedSeconds  int32            `json:"paused_seconds"`
	LatencyAvgMs   *int32           `json:"latency_avg_ms"`
	LatencyP95Ms   *int32           `json:"latency_p95_ms"`
}

type Invitation struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Email          string           `json:"email"`
	Role           *string          `json:"role"`
	Status         string           `json:"status"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	InviterID      string           `json:"inviter_id"`
}

type Lock struct {
	Key       string           `json:"key"`
	Expires   pgtype.Timestamp `json:"expires"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Member struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type NotificationPreference struct {
	ID        int32           `json:"id"`
	UserID    string          `json:"user_id"`
	ScopeType string          `json:"scope_type"`
	ScopeID   string          `json:"scope_id"`
	EventType string          `json:"event_type"`
	Channel   string          `json:"channel"`
	Enabled   bool            `json:"enabled"`
	Config    json.RawMessage `json:"config"`
}

type Organization struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Logo      *string          `json:"logo"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Passkey struct {
	ID           string           `json:"id"`
	Name         *string          `json:"name"`
	PublicKey    string           `json:"public_key"`
	UserID       string           `json:"user_id"`
	CredentialID string           `json:"credential_id"`
	Counter      int32            `json:"counter"`
	DeviceType   string           `json:"device_type"`
	BackedUp     bool             `json:"backed_up"`
	Transports   *string          `json:"transports"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Aaguid       *string          `json:"aaguid"`
}

type SecurityPluginCoverage struct {
	PluginBranch     string           `json:"plugin_branch"`
	MinParsedVersion string           `json:"min_parsed_version"`
	MaxParsedVersion string           `json:"max_parsed_version"`
	GhsaCount        int32            `json:"ghsa_count"`
	ParsedAt         pgtype.Timestamp `json:"parsed_at"`
	LastError        *string          `json:"last_error"`
}

type SecurityPluginFix struct {
	GhsaID         string           `json:"ghsa_id"`
	PluginBranch   string           `json:"plugin_branch"`
	PluginVersion  string           `json:"plugin_version"`
	ShopwareBranch string           `json:"shopware_branch"`
	ReleasedAt     pgtype.Timestamp `json:"released_at"`
	SyncedAt       pgtype.Timestamp `json:"synced_at"`
}

type Session struct {
	ID                   string           `json:"id"`
	ExpiresAt            pgtype.Timestamp `json:"expires_at"`
	Token                string           `json:"token"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	IpAddress            *string          `json:"ip_address"`
	UserAgent            *string          `json:"user_agent"`
	UserID               string           `json:"user_id"`
	ImpersonatedBy       *string          `json:"impersonated_by"`
	ActiveOrganizationID *string          `json:"active_organization_id"`
}

type Shop struct {
	ID                   int32            `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	Name                 string           `json:"name"`
	Description          *string          `json:"description"`
	GitUrl               *string          `json:"git_url"`
	DefaultEnvironmentID *int32           `json:"default_environment_id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type ShopApiKey struct {
	ID         string           `json:"id"`
	ShopID     int32            `json:"shop_id"`
	Name       string           `json:"name"`
	Token      string           `json:"token"`
	Scopes     json.RawMessage  `json:"scopes"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

type ShopwareVersion struct {
	Version     string           `json:"version"`
	ReleaseDate pgtype.Timestamp `json:"release_date"`
	Title       string           `json:"title"`
	Body        string           `json:"body"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type SsoProvider struct {
	ID             string  `json:"id"`
	Issuer         string  `json:"issuer"`
	OidcConfig     *string `json:"oidc_config"`
	ProviderID     string  `json:"provider_id"`
	OrganizationID *string `json:"organization_id"`
	Domain         string  `json:"domain"`
}

type StoreExtension struct {
	Name            string           `json:"name"`
	StoreID         *int32           `json:"store_id"`
	IconUrl         *string          `json:"icon_url"`
	ProducerName    *string          `json:"producer_name"`
	ProducerWebsite *string          `json:"producer_website"`
	RatingAverage   *int32           `json:"rating_average"`
	StoreLink       *string          `json:"store_link"`
	ReleaseDate     *string          `json:"release_date"`
	LatestVersion   *string          `json:"latest_version"`
	LastRefreshedAt pgtype.Timestamp `json:"last_refreshed_at"`
}

type StoreExtensionCompatibility struct {
	ExtensionName   string  `json:"extension_name"`
	ShopwareVersion string  `json:"shopware_version"`
	LatestVersion   *string `json:"latest_version"`
}

type StoreExtensionImage struct {
	ID            int32  `json:"id"`
	ExtensionName string `json:"extension_name"`
	Url           string `json:"url"`
	Preview       bool   `json:"preview"`
	Priority      int32  `json:"priority"`
}

type StoreExtensionSync struct {
	ExtensionName string           `json:"extension_name"`
	LastSyncedAt  pgtype.Timestamp `json:"last_synced_at"`
}

type StoreExtensionTranslation struct {
	ExtensionName      string  `json:"extension_name"`
	Language           string  `json:"language"`
	Label              *string `json:"label"`
	ShortDescription   *string `json:"short_description"`
	Description        *string `json:"description"`
	InstallationManual *string `json:"installation_manual"`
}

type StoreExtensionVersion struct {
	ID            int32   `json:"id"`
	ExtensionName string  `json:"extension_name"`
	Version       string  `json:"version"`
	ReleasedAt    *string `json:"released_at"`
}

type StoreExtensionVersionTranslation struct {
	ExtensionVersionID int32   `json:"extension_version_id"`
	Language           string  `json:"language"`
	Changelog          *string `json:"changelog"`
}

type User struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"email_verified"`
	Image         *string          `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Role          string           `json:"role"`
	Banned        *bool            `json:"banned"`
	BanReason     *string          `json:"ban_reason"`
	BanExpires    pgtype.Timestamp `json:"ban_expires"`
	Notifications []byte           `json:"notifications"`
	Locale        string           `json:"locale"`
}

type UserNotification struct {
	ID         int32            `json:"id"`
	UserID     string           `json:"user_id"`
	Key        string           `json:"key"`
	Level      string           `json:"level"`
	Title      string           `json:"title"`
	Message    string           `json:"message"`
	TitleKey   *string          `json:"title_key"`
	MessageKey *string          `json:"message_key"`
	Params     json.RawMessage  `json:"params"`
	Link       json.RawMessage  `json:"link"`
	Read       bool             `json:"read"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
