// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                string           `json:"user_id"`
	AccessToken           *string          `json:"access_token"`
	RefreshToken          *string          `json:"refresh_token"`
	IDToken               *string          `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 *string          `json:"scope"`
	Password              *string          `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Deployment struct {
	ID            int32            `json:"id"`
	EnvironmentID int32            `json:"environment_id"`
	Name          string           `json:"name"`
	Command       string           `json:"command"`
	ReturnCode    int32            `json:"return_code"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	ExecutionTime float32          `json:"execution_time"`
	Composer      []byte           `json:"composer"`
	Reference     *string          `json:"reference"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type Environment struct {
	ID                   int32            `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	ShopID               int32            `json:"shop_id"`
	Name                 string           `json:"name"`
	Status               string           `json:"status"`
	Url                  string           `json:"url"`
	Favicon              *string          `json:"favicon"`
	ClientID             string           `json:"client_id"`
	ClientSecret         string           `json:"client_secret"`
	ShopwareVersion      string           `json:"shopware_version"`
	LastScrapedAt        pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError     *string          `json:"last_scraped_error"`
	Ignores              json.RawMessage  `json:"ignores"`
	EnvironmentImage     *string          `json:"environment_image"`
	LastChangelog        []byte           `json:"last_changelog"`
	ActiveDeploymentID   *int32           `json:"active_deployment_id"`
	ConnectionIssueCount int32            `json:"connection_issue_count"`
	SitespeedEnabled     bool             `json:"sitespeed_enabled"`
	SitespeedUrls        json.RawMessage  `json:"sitespeed_urls"`
	EnvironmentToken     string           `json:"environment_token"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type EnvironmentCache struct {
	ID            int32  `json:"id"`
	EnvironmentID int32  `json:"environment_id"`
	Environment   string `json:"environment"`
	HttpCache     bool   `json:"http_cache"`
	CacheAdapter  string `json:"cache_adapter"`
}

type EnvironmentChangelog struct {
	ID                 int32            `json:"id"`
	EnvironmentID      *int32           `json:"environment_id"`
	Extensions         json.RawMessage  `json:"extensions"`
	OldShopwareVersion *string          `json:"old_shopware_version"`
	NewShopwareVersion *string          `json:"new_shopware_version"`
	Date               pgtype.Timestamp `json:"date"`
}

type EnvironmentCheck struct {
	ID            int32   `json:"id"`
	EnvironmentID int32   `json:"environment_id"`
	CheckID       string  `json:"check_id"`
	Level         string  `json:"level"`
	Message       string  `json:"message"`
	Source        string  `json:"source"`
	Link          *string `json:"link"`
}

type EnvironmentExtension struct {
	ID            int32   `json:"id"`
	EnvironmentID int32   `json:"environment_id"`
	Name          string  `json:"name"`
	Label         string  `json:"label"`
	Active        bool    `json:"active"`
	Version       string  `json:"version"`
	LatestVersion *string `json:"latest_version"`
	Installed     bool    `json:"installed"`
	RatingAverage *int32  `json:"rating_average"`
	StoreLink     *string `json:"store_link"`
	Changelog     []byte  `json:"changelog"`
	InstalledAt   *string `json:"installed_at"`
}

type EnvironmentQueue struct {
	ID            int32  `json:"id"`
	EnvironmentID int32  `json:"environment_id"`
	Name          string `json:"name"`
	Size          int32  `json:"size"`
}

type EnvironmentScheduledTask struct {
	ID                int32   `json:"id"`
	EnvironmentID     int32   `json:"environment_id"`
	TaskID            string  `json:"task_id"`
	Name              string  `json:"name"`
	Status            string  `json:"status"`
	Interval          int32   `json:"interval"`
	Overdue           bool    `json:"overdue"`
	LastExecutionTime *string `json:"last_execution_time"`
	NextExecutionTime *string `json:"next_execution_time"`
}

type EnvironmentSitespeed struct {
	ID                     int32            `json:"id"`
	EnvironmentID          *int32           `json:"environment_id"`
	DeploymentID           *int32           `json:"deployment_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	Ttfb                   *int32           `json:"ttfb"`
	FullyLoaded            *int32           `json:"fully_loaded"`
	LargestContentfulPaint *int32           `json:"largest_contentful_paint"`
	FirstContentfulPaint   *int32           `json:"first_contentful_paint"`
	CumulativeLayoutShift  *float32         `json:"cumulative_layout_shift"`
	TransferSize           *int32           `json:"transfer_size"`
}

type Invitation struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Email          string           `json:"email"`
	Role           *string          `json:"role"`
	Status         string           `json:"status"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	InviterID      string           `json:"inviter_id"`
}

type Lock struct {
	Key       string           `json:"key"`
	Expires   pgtype.Timestamp `json:"expires"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Member struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Organization struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Logo      *string          `json:"logo"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Metadata  *string          `json:"metadata"`
}

type Passkey struct {
	ID           string           `json:"id"`
	Name         *string          `json:"name"`
	PublicKey    string           `json:"public_key"`
	UserID       string           `json:"user_id"`
	CredentialID string           `json:"credential_id"`
	Counter      int32            `json:"counter"`
	DeviceType   string           `json:"device_type"`
	BackedUp     bool             `json:"backed_up"`
	Transports   *string          `json:"transports"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	Aaguid       *string          `json:"aaguid"`
}

type Session struct {
	ID                   string           `json:"id"`
	ExpiresAt            pgtype.Timestamp `json:"expires_at"`
	Token                string           `json:"token"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	IpAddress            *string          `json:"ip_address"`
	UserAgent            *string          `json:"user_agent"`
	UserID               string           `json:"user_id"`
	ImpersonatedBy       *string          `json:"impersonated_by"`
	ActiveOrganizationID *string          `json:"active_organization_id"`
}

type Shop struct {
	ID                   int32            `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	Name                 string           `json:"name"`
	Description          *string          `json:"description"`
	GitUrl               *string          `json:"git_url"`
	DefaultEnvironmentID *int32           `json:"default_environment_id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type ShopApiKey struct {
	ID         string           `json:"id"`
	ShopID     int32            `json:"shop_id"`
	Name       string           `json:"name"`
	Token      string           `json:"token"`
	Scopes     json.RawMessage  `json:"scopes"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

type SsoProvider struct {
	ID             string  `json:"id"`
	Issuer         string  `json:"issuer"`
	OidcConfig     *string `json:"oidc_config"`
	SamlConfig     *string `json:"saml_config"`
	UserID         *string `json:"user_id"`
	ProviderID     string  `json:"provider_id"`
	OrganizationID *string `json:"organization_id"`
	Domain         string  `json:"domain"`
}

type User struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"email_verified"`
	Image         *string          `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Role          string           `json:"role"`
	Banned        *bool            `json:"banned"`
	BanReason     *string          `json:"ban_reason"`
	BanExpires    pgtype.Timestamp `json:"ban_expires"`
	Notifications []byte           `json:"notifications"`
}

type UserNotification struct {
	ID        int32            `json:"id"`
	UserID    string           `json:"user_id"`
	Key       string           `json:"key"`
	Level     string           `json:"level"`
	Title     string           `json:"title"`
	Message   string           `json:"message"`
	Link      json.RawMessage  `json:"link"`
	Read      bool             `json:"read"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
