// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_preference.sql

package queries

import (
	"context"
	"encoding/json"
)

const deleteEnvironmentNotificationPreferences = `-- name: DeleteEnvironmentNotificationPreferences :exec
DELETE FROM notification_preference
WHERE scope_type = 'environment' AND scope_id = $1
`

// Removes all users' preferences scoped to a single environment (used when the
// environment is deleted). scope_id is text, so there is no FK to cascade on.
func (q *Queries) DeleteEnvironmentNotificationPreferences(ctx context.Context, scopeID string) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentNotificationPreferences, scopeID)
	return err
}

const deleteNotificationPreference = `-- name: DeleteNotificationPreference :exec
DELETE FROM notification_preference
WHERE user_id = $1 AND scope_type = $2 AND scope_id = $3 AND event_type = $4 AND channel = $5
`

type DeleteNotificationPreferenceParams struct {
	UserID    string `json:"user_id"`
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	EventType string `json:"event_type"`
	Channel   string `json:"channel"`
}

func (q *Queries) DeleteNotificationPreference(ctx context.Context, arg DeleteNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationPreference,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.EventType,
		arg.Channel,
	)
	return err
}

const deleteUserOrgNotificationPreferences = `-- name: DeleteUserOrgNotificationPreferences :exec
DELETE FROM notification_preference
WHERE user_id = $1
  AND scope_type = 'environment'
  AND scope_id IN (SELECT id::text FROM environment WHERE organization_id = $2)
`

type DeleteUserOrgNotificationPreferencesParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

// Removes a user's environment-scoped preferences for every environment in an
// organization (used when the user is removed from / leaves the org).
func (q *Queries) DeleteUserOrgNotificationPreferences(ctx context.Context, arg DeleteUserOrgNotificationPreferencesParams) error {
	_, err := q.db.Exec(ctx, deleteUserOrgNotificationPreferences, arg.UserID, arg.OrganizationID)
	return err
}

const isEnvironmentSubscribed = `-- name: IsEnvironmentSubscribed :one
SELECT EXISTS (
  SELECT 1 FROM notification_preference
  WHERE user_id = $1 AND scope_type = 'environment' AND scope_id = $2 AND channel = '' AND enabled = true
) AS subscribed
`

type IsEnvironmentSubscribedParams struct {
	UserID  string `json:"user_id"`
	ScopeID string `json:"scope_id"`
}

func (q *Queries) IsEnvironmentSubscribed(ctx context.Context, arg IsEnvironmentSubscribedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEnvironmentSubscribed, arg.UserID, arg.ScopeID)
	var subscribed bool
	err := row.Scan(&subscribed)
	return subscribed, err
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT id, user_id, scope_type, scope_id, event_type, channel, enabled, config
FROM notification_preference
WHERE user_id = $1
`

func (q *Queries) ListNotificationPreferences(ctx context.Context, userID string) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.EventType,
			&i.Channel,
			&i.Enabled,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribedEnvironmentIDs = `-- name: ListSubscribedEnvironmentIDs :many
SELECT scope_id FROM notification_preference
WHERE user_id = $1 AND scope_type = 'environment' AND channel = '' AND enabled = true
`

func (q *Queries) ListSubscribedEnvironmentIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSubscribedEnvironmentIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scope_id string
		if err := rows.Scan(&scope_id); err != nil {
			return nil, err
		}
		items = append(items, scope_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeEnvironment = `-- name: SubscribeEnvironment :exec
INSERT INTO notification_preference (user_id, scope_type, scope_id, event_type, channel, enabled)
VALUES ($1, 'environment', $2, '', '', true)
ON CONFLICT (user_id, scope_type, scope_id, event_type, channel)
DO UPDATE SET enabled = true
`

type SubscribeEnvironmentParams struct {
	UserID  string `json:"user_id"`
	ScopeID string `json:"scope_id"`
}

func (q *Queries) SubscribeEnvironment(ctx context.Context, arg SubscribeEnvironmentParams) error {
	_, err := q.db.Exec(ctx, subscribeEnvironment, arg.UserID, arg.ScopeID)
	return err
}

const unsubscribeEnvironment = `-- name: UnsubscribeEnvironment :exec
DELETE FROM notification_preference
WHERE user_id = $1 AND scope_type = 'environment' AND scope_id = $2
`

type UnsubscribeEnvironmentParams struct {
	UserID  string `json:"user_id"`
	ScopeID string `json:"scope_id"`
}

func (q *Queries) UnsubscribeEnvironment(ctx context.Context, arg UnsubscribeEnvironmentParams) error {
	_, err := q.db.Exec(ctx, unsubscribeEnvironment, arg.UserID, arg.ScopeID)
	return err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :exec
INSERT INTO notification_preference (user_id, scope_type, scope_id, event_type, channel, enabled, config)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, scope_type, scope_id, event_type, channel)
DO UPDATE SET enabled = $6, config = $7
`

type UpsertNotificationPreferenceParams struct {
	UserID    string          `json:"user_id"`
	ScopeType string          `json:"scope_type"`
	ScopeID   string          `json:"scope_id"`
	EventType string          `json:"event_type"`
	Channel   string          `json:"channel"`
	Enabled   bool            `json:"enabled"`
	Config    json.RawMessage `json:"config"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.EventType,
		arg.Channel,
		arg.Enabled,
		arg.Config,
	)
	return err
}
