// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package queries

import (
	"context"
	"encoding/json"
)

const deleteAllNotifications = `-- name: DeleteAllNotifications :exec
DELETE FROM user_notification WHERE user_id = $1
`

func (q *Queries) DeleteAllNotifications(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllNotifications, userID)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM user_notification WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, key, level, title, message, link, read, created_at
FROM user_notification WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNotifications(ctx context.Context, userID string) ([]UserNotification, error) {
	rows, err := q.db.Query(ctx, listNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Level,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE user_notification SET read = true WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const upsertNotification = `-- name: UpsertNotification :exec
INSERT INTO user_notification (user_id, key, level, title, message, link, read, created_at)
VALUES ($1, $2, $3, $4, $5, $6, false, NOW())
ON CONFLICT (user_id, key) DO UPDATE SET level = $3, title = $4, message = $5, link = $6, read = false, created_at = NOW()
`

type UpsertNotificationParams struct {
	UserID  string          `json:"user_id"`
	Key     string          `json:"key"`
	Level   string          `json:"level"`
	Title   string          `json:"title"`
	Message string          `json:"message"`
	Link    json.RawMessage `json:"link"`
}

func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) error {
	_, err := q.db.Exec(ctx, upsertNotification,
		arg.UserID,
		arg.Key,
		arg.Level,
		arg.Title,
		arg.Message,
		arg.Link,
	)
	return err
}
