// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package queries

import (
	"context"
	"encoding/json"
)

const deleteAllNotifications = `-- name: DeleteAllNotifications :exec
DELETE FROM user_notification WHERE user_id = $1
`

func (q *Queries) DeleteAllNotifications(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllNotifications, userID)
	return err
}

const deleteEnvironmentNotifications = `-- name: DeleteEnvironmentNotifications :exec
DELETE FROM user_notification
WHERE (link->'params'->>'environmentId') = $1::text
`

// Removes all users' inbox notifications tied to a single environment.
func (q *Queries) DeleteEnvironmentNotifications(ctx context.Context, environmentID string) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentNotifications, environmentID)
	return err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM user_notification WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     int32  `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteUserOrgNotifications = `-- name: DeleteUserOrgNotifications :exec
DELETE FROM user_notification
WHERE user_id = $1
  AND (link->'params'->>'environmentId') IN (
    SELECT id::text FROM environment WHERE organization_id = $2
  )
`

type DeleteUserOrgNotificationsParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

// Removes a user's inbox notifications tied to environments of an organization.
func (q *Queries) DeleteUserOrgNotifications(ctx context.Context, arg DeleteUserOrgNotificationsParams) error {
	_, err := q.db.Exec(ctx, deleteUserOrgNotifications, arg.UserID, arg.OrganizationID)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, key, level, title, message, title_key, message_key, params, link, read, created_at
FROM user_notification WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNotifications(ctx context.Context, userID string) ([]UserNotification, error) {
	rows, err := q.db.Query(ctx, listNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserNotification{}
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Key,
			&i.Level,
			&i.Title,
			&i.Message,
			&i.TitleKey,
			&i.MessageKey,
			&i.Params,
			&i.Link,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE user_notification SET read = true WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const upsertNotification = `-- name: UpsertNotification :exec
INSERT INTO user_notification (user_id, key, level, title, message, title_key, message_key, params, link, read, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, false, NOW())
ON CONFLICT (user_id, key) DO UPDATE SET
  level = $3, title = $4, message = $5, title_key = $6, message_key = $7, params = $8, link = $9, read = false, created_at = NOW()
`

type UpsertNotificationParams struct {
	UserID     string          `json:"user_id"`
	Key        string          `json:"key"`
	Level      string          `json:"level"`
	Title      string          `json:"title"`
	Message    string          `json:"message"`
	TitleKey   *string         `json:"title_key"`
	MessageKey *string         `json:"message_key"`
	Params     json.RawMessage `json:"params"`
	Link       json.RawMessage `json:"link"`
}

func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) error {
	_, err := q.db.Exec(ctx, upsertNotification,
		arg.UserID,
		arg.Key,
		arg.Level,
		arg.Title,
		arg.Message,
		arg.TitleKey,
		arg.MessageKey,
		arg.Params,
		arg.Link,
	)
	return err
}
