// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgMembers = `-- name: CountOrgMembers :one
SELECT COUNT(*)::int FROM member WHERE organization_id = $1
`

func (q *Queries) CountOrgMembers(ctx context.Context, organizationID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgMembers, organizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrgOwners = `-- name: CountOrgOwners :one
SELECT COUNT(*)::int FROM member WHERE organization_id = $1 AND role = 'owner'
`

func (q *Queries) CountOrgOwners(ctx context.Context, organizationID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgOwners, organizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitation (id, organization_id, email, role, status, expires_at, created_at, inviter_id)
VALUES ($1, $2, $3, $4, 'pending', $5, NOW(), $6)
RETURNING id
`

type CreateInvitationParams struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Email          string           `json:"email"`
	Role           *string          `json:"role"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	InviterID      string           `json:"inviter_id"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (string, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.ExpiresAt,
		arg.InviterID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createMember = `-- name: CreateMember :exec
INSERT INTO member (id, organization_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4, NOW())
`

type CreateMemberParams struct {
	ID             string `json:"id"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
	Role           string `json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.Exec(ctx, createMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (id, name, slug, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id
`

type CreateOrganizationParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (string, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name, arg.Slug)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitation WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM member WHERE organization_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.OrganizationID, arg.UserID)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organization WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT i.id, i.organization_id, i.email, i.role, i.status, i.expires_at, i.inviter_id,
       o.name AS organization_name,
       u.name AS inviter_name
FROM invitation i
JOIN organization o ON o.id = i.organization_id
JOIN "user" u ON u.id = i.inviter_id
WHERE i.id = $1 AND i.status = 'pending' AND i.expires_at > NOW()
`

type GetInvitationByIDRow struct {
	ID               string           `json:"id"`
	OrganizationID   string           `json:"organization_id"`
	Email            string           `json:"email"`
	Role             *string          `json:"role"`
	Status           string           `json:"status"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	InviterID        string           `json:"inviter_id"`
	OrganizationName string           `json:"organization_name"`
	InviterName      string           `json:"inviter_name"`
}

func (q *Queries) GetInvitationByID(ctx context.Context, id string) (GetInvitationByIDRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i GetInvitationByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.ExpiresAt,
		&i.InviterID,
		&i.OrganizationName,
		&i.InviterName,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM member WHERE organization_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.OrganizationID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, logo, created_at FROM organization WHERE id = $1
`

type GetOrganizationByIDRow struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Slug      string           `json:"slug"`
	Logo      *string          `json:"logo"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (GetOrganizationByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i GetOrganizationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Logo,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT i.id, i.organization_id, i.email, i.role, i.status, i.expires_at, i.created_at, i.inviter_id,
       u.name AS inviter_name
FROM invitation i
JOIN "user" u ON u.id = i.inviter_id
WHERE i.organization_id = $1 AND i.status = 'pending'
ORDER BY i.created_at DESC
`

type ListInvitationsRow struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Email          string           `json:"email"`
	Role           *string          `json:"role"`
	Status         string           `json:"status"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	InviterID      string           `json:"inviter_id"`
	InviterName    string           `json:"inviter_name"`
}

func (q *Queries) ListInvitations(ctx context.Context, organizationID string) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.InviterID,
			&i.InviterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.organization_id, m.user_id, m.role, m.created_at,
       u.name AS user_name, u.email AS user_email, u.image AS user_image
FROM member m
JOIN "user" u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY m.created_at
`

type ListMembersRow struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UserName       string           `json:"user_name"`
	UserEmail      string           `json:"user_email"`
	UserImage      *string          `json:"user_image"`
}

func (q *Queries) ListMembers(ctx context.Context, organizationID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :exec
UPDATE invitation SET status = $1 WHERE id = $2
`

type UpdateInvitationStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvitationStatus, arg.Status, arg.ID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE member SET role = $1 WHERE organization_id = $2 AND user_id = $3
`

type UpdateMemberRoleParams struct {
	Role           string `json:"role"`
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.Role, arg.OrganizationID, arg.UserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organization SET name = $1, slug = $2, logo = $3 WHERE id = $4
`

type UpdateOrganizationParams struct {
	Name string  `json:"name"`
	Slug string  `json:"slug"`
	Logo *string `json:"logo"`
	ID   string  `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization,
		arg.Name,
		arg.Slug,
		arg.Logo,
		arg.ID,
	)
	return err
}
