// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package queries

import (
	"context"
)

const countShopsInProject = `-- name: CountShopsInProject :one
SELECT COUNT(*)::int FROM shop WHERE project_id = $1
`

func (q *Queries) CountShopsInProject(ctx context.Context, projectID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countShopsInProject, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO project (organization_id, name, description, git_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id
`

type CreateProjectParams struct {
	OrganizationID string  `json:"organization_id"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	GitUrl         *string `json:"git_url"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (int32, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.GitUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project WHERE id = $1 AND organization_id = $2
`

type DeleteProjectParams struct {
	ID             int32  `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OrganizationID)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, name, description, git_url, created_at, updated_at
FROM project WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int32) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.GitUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectOrganizationID = `-- name: GetProjectOrganizationID :one
SELECT organization_id FROM project WHERE id = $1
`

func (q *Queries) GetProjectOrganizationID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getProjectOrganizationID, id)
	var organization_id string
	err := row.Scan(&organization_id)
	return organization_id, err
}

const listProjectsByOrganization = `-- name: ListProjectsByOrganization :many
SELECT id, organization_id, name, description, git_url, created_at, updated_at
FROM project WHERE organization_id = $1 ORDER BY name
`

func (q *Queries) ListProjectsByOrganization(ctx context.Context, organizationID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.GitUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :exec
UPDATE project SET name = $1, description = $2, git_url = $3, updated_at = NOW() WHERE id = $4 AND organization_id = $5
`

type UpdateProjectParams struct {
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	GitUrl         *string `json:"git_url"`
	ID             int32   `json:"id"`
	OrganizationID string  `json:"organization_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.GitUrl,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}
