// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_plugin.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSecurityPluginFixesNotIn = `-- name: DeleteSecurityPluginFixesNotIn :exec
DELETE FROM security_plugin_fix
WHERE plugin_branch = ANY($1::text[])
  AND ghsa_id != ALL($2::text[])
`

type DeleteSecurityPluginFixesNotInParams struct {
	Branches []string `json:"branches"`
	GhsaIds  []string `json:"ghsa_ids"`
}

// Rows for branches that were re-derived but no longer name the GHSA. Scoped to
// the observed branches so a partial sync never deletes another branch's map.
func (q *Queries) DeleteSecurityPluginFixesNotIn(ctx context.Context, arg DeleteSecurityPluginFixesNotInParams) error {
	_, err := q.db.Exec(ctx, deleteSecurityPluginFixesNotIn, arg.Branches, arg.GhsaIds)
	return err
}

const listSecurityPluginCoverage = `-- name: ListSecurityPluginCoverage :many
SELECT plugin_branch, min_parsed_version, max_parsed_version, ghsa_count, parsed_at, last_error FROM security_plugin_coverage ORDER BY plugin_branch
`

func (q *Queries) ListSecurityPluginCoverage(ctx context.Context) ([]SecurityPluginCoverage, error) {
	rows, err := q.db.Query(ctx, listSecurityPluginCoverage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityPluginCoverage{}
	for rows.Next() {
		var i SecurityPluginCoverage
		if err := rows.Scan(
			&i.PluginBranch,
			&i.MinParsedVersion,
			&i.MaxParsedVersion,
			&i.GhsaCount,
			&i.ParsedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurityPluginFixes = `-- name: ListSecurityPluginFixes :many
SELECT ghsa_id, plugin_branch, plugin_version, shopware_branch, released_at, synced_at FROM security_plugin_fix ORDER BY ghsa_id, plugin_branch
`

func (q *Queries) ListSecurityPluginFixes(ctx context.Context) ([]SecurityPluginFix, error) {
	rows, err := q.db.Query(ctx, listSecurityPluginFixes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityPluginFix{}
	for rows.Next() {
		var i SecurityPluginFix
		if err := rows.Scan(
			&i.GhsaID,
			&i.PluginBranch,
			&i.PluginVersion,
			&i.ShopwareBranch,
			&i.ReleasedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurityPluginFixesForGhsas = `-- name: ListSecurityPluginFixesForGhsas :many
SELECT ghsa_id, plugin_branch, plugin_version, shopware_branch, released_at, synced_at FROM security_plugin_fix
WHERE ghsa_id = ANY($1::text[])
ORDER BY ghsa_id, plugin_branch
`

func (q *Queries) ListSecurityPluginFixesForGhsas(ctx context.Context, ghsaIds []string) ([]SecurityPluginFix, error) {
	rows, err := q.db.Query(ctx, listSecurityPluginFixesForGhsas, ghsaIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityPluginFix{}
	for rows.Next() {
		var i SecurityPluginFix
		if err := rows.Scan(
			&i.GhsaID,
			&i.PluginBranch,
			&i.PluginVersion,
			&i.ShopwareBranch,
			&i.ReleasedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSecurityPluginCoverageError = `-- name: SetSecurityPluginCoverageError :exec
UPDATE security_plugin_coverage SET last_error = $2 WHERE plugin_branch = $1
`

type SetSecurityPluginCoverageErrorParams struct {
	PluginBranch string  `json:"plugin_branch"`
	LastError    *string `json:"last_error"`
}

// Records why a branch's parse result was rejected (e.g. the sharp-drop
// guard) without touching its accepted fixes or counters.
func (q *Queries) SetSecurityPluginCoverageError(ctx context.Context, arg SetSecurityPluginCoverageErrorParams) error {
	_, err := q.db.Exec(ctx, setSecurityPluginCoverageError, arg.PluginBranch, arg.LastError)
	return err
}

const upsertSecurityPluginCoverage = `-- name: UpsertSecurityPluginCoverage :exec
INSERT INTO security_plugin_coverage (
  plugin_branch, min_parsed_version, max_parsed_version, ghsa_count, parsed_at, last_error
) VALUES ($1, $2, $3, $4, NOW(), $5)
ON CONFLICT (plugin_branch) DO UPDATE SET
  min_parsed_version = EXCLUDED.min_parsed_version,
  max_parsed_version = EXCLUDED.max_parsed_version,
  ghsa_count = EXCLUDED.ghsa_count,
  parsed_at = NOW(),
  last_error = EXCLUDED.last_error
`

type UpsertSecurityPluginCoverageParams struct {
	PluginBranch     string  `json:"plugin_branch"`
	MinParsedVersion string  `json:"min_parsed_version"`
	MaxParsedVersion string  `json:"max_parsed_version"`
	GhsaCount        int32   `json:"ghsa_count"`
	LastError        *string `json:"last_error"`
}

func (q *Queries) UpsertSecurityPluginCoverage(ctx context.Context, arg UpsertSecurityPluginCoverageParams) error {
	_, err := q.db.Exec(ctx, upsertSecurityPluginCoverage,
		arg.PluginBranch,
		arg.MinParsedVersion,
		arg.MaxParsedVersion,
		arg.GhsaCount,
		arg.LastError,
	)
	return err
}

const upsertSecurityPluginFix = `-- name: UpsertSecurityPluginFix :exec

INSERT INTO security_plugin_fix (
  ghsa_id, plugin_branch, plugin_version, shopware_branch, released_at, synced_at
) VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (ghsa_id, plugin_branch) DO UPDATE SET
  plugin_version = EXCLUDED.plugin_version,
  shopware_branch = EXCLUDED.shopware_branch,
  released_at = EXCLUDED.released_at,
  synced_at = NOW()
`

type UpsertSecurityPluginFixParams struct {
	GhsaID         string           `json:"ghsa_id"`
	PluginBranch   string           `json:"plugin_branch"`
	PluginVersion  string           `json:"plugin_version"`
	ShopwareBranch string           `json:"shopware_branch"`
	ReleasedAt     pgtype.Timestamp `json:"released_at"`
}

// SwagPlatformSecurity backport map, derived from the store changelog.
func (q *Queries) UpsertSecurityPluginFix(ctx context.Context, arg UpsertSecurityPluginFixParams) error {
	_, err := q.db.Exec(ctx, upsertSecurityPluginFix,
		arg.GhsaID,
		arg.PluginBranch,
		arg.PluginVersion,
		arg.ShopwareBranch,
		arg.ReleasedAt,
	)
	return err
}
