// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_advisory.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSecurityAdvisory = `-- name: GetSecurityAdvisory :one
SELECT advisory_id, origin, package_name, title, link, cve,
       affected_versions, source_name, source_remote_id, severity, reported_at, created_at, updated_at
FROM security_advisory
WHERE advisory_id = $1
`

func (q *Queries) GetSecurityAdvisory(ctx context.Context, advisoryID string) (SecurityAdvisory, error) {
	row := q.db.QueryRow(ctx, getSecurityAdvisory, advisoryID)
	var i SecurityAdvisory
	err := row.Scan(
		&i.AdvisoryID,
		&i.Origin,
		&i.PackageName,
		&i.Title,
		&i.Link,
		&i.Cve,
		&i.AffectedVersions,
		&i.SourceName,
		&i.SourceRemoteID,
		&i.Severity,
		&i.ReportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecurityAdvisories = `-- name: ListSecurityAdvisories :many
SELECT advisory_id, origin, package_name, title, link, cve,
       affected_versions, source_name, source_remote_id, severity, reported_at, created_at, updated_at
FROM security_advisory
ORDER BY reported_at DESC NULLS LAST, advisory_id
`

func (q *Queries) ListSecurityAdvisories(ctx context.Context) ([]SecurityAdvisory, error) {
	rows, err := q.db.Query(ctx, listSecurityAdvisories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityAdvisory{}
	for rows.Next() {
		var i SecurityAdvisory
		if err := rows.Scan(
			&i.AdvisoryID,
			&i.Origin,
			&i.PackageName,
			&i.Title,
			&i.Link,
			&i.Cve,
			&i.AffectedVersions,
			&i.SourceName,
			&i.SourceRemoteID,
			&i.Severity,
			&i.ReportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecurityAdvisory = `-- name: UpsertSecurityAdvisory :exec
INSERT INTO security_advisory (
  advisory_id, origin, package_name, title, link, cve,
  affected_versions, source_name, source_remote_id, severity, reported_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
ON CONFLICT (advisory_id) DO UPDATE SET
  origin = EXCLUDED.origin,
  package_name = EXCLUDED.package_name,
  title = EXCLUDED.title,
  link = EXCLUDED.link,
  cve = EXCLUDED.cve,
  affected_versions = EXCLUDED.affected_versions,
  source_name = EXCLUDED.source_name,
  source_remote_id = EXCLUDED.source_remote_id,
  severity = EXCLUDED.severity,
  reported_at = EXCLUDED.reported_at,
  updated_at = NOW()
`

type UpsertSecurityAdvisoryParams struct {
	AdvisoryID       string           `json:"advisory_id"`
	Origin           string           `json:"origin"`
	PackageName      string           `json:"package_name"`
	Title            string           `json:"title"`
	Link             *string          `json:"link"`
	Cve              *string          `json:"cve"`
	AffectedVersions string           `json:"affected_versions"`
	SourceName       *string          `json:"source_name"`
	SourceRemoteID   *string          `json:"source_remote_id"`
	Severity         *string          `json:"severity"`
	ReportedAt       pgtype.Timestamp `json:"reported_at"`
}

func (q *Queries) UpsertSecurityAdvisory(ctx context.Context, arg UpsertSecurityAdvisoryParams) error {
	_, err := q.db.Exec(ctx, upsertSecurityAdvisory,
		arg.AdvisoryID,
		arg.Origin,
		arg.PackageName,
		arg.Title,
		arg.Link,
		arg.Cve,
		arg.AffectedVersions,
		arg.SourceName,
		arg.SourceRemoteID,
		arg.Severity,
		arg.ReportedAt,
	)
	return err
}
