// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop.sql

package queries

import (
	"context"
)

const countEnvironmentsInShop = `-- name: CountEnvironmentsInShop :one
SELECT COUNT(*)::int FROM environment WHERE shop_id = $1
`

func (q *Queries) CountEnvironmentsInShop(ctx context.Context, shopID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countEnvironmentsInShop, shopID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createShop = `-- name: CreateShop :one
INSERT INTO shop (organization_id, name, description, git_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id
`

type CreateShopParams struct {
	OrganizationID string  `json:"organization_id"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	GitUrl         *string `json:"git_url"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (int32, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.GitUrl,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteShop = `-- name: DeleteShop :exec
DELETE FROM shop WHERE id = $1 AND organization_id = $2
`

type DeleteShopParams struct {
	ID             int32  `json:"id"`
	OrganizationID string `json:"organization_id"`
}

func (q *Queries) DeleteShop(ctx context.Context, arg DeleteShopParams) error {
	_, err := q.db.Exec(ctx, deleteShop, arg.ID, arg.OrganizationID)
	return err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, organization_id, name, description, git_url, created_at, updated_at
FROM shop WHERE id = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id int32) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.GitUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopOrganizationID = `-- name: GetShopOrganizationID :one
SELECT organization_id FROM shop WHERE id = $1
`

func (q *Queries) GetShopOrganizationID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getShopOrganizationID, id)
	var organization_id string
	err := row.Scan(&organization_id)
	return organization_id, err
}

const listShopsByOrganization = `-- name: ListShopsByOrganization :many
SELECT id, organization_id, name, description, git_url, created_at, updated_at
FROM shop WHERE organization_id = $1 ORDER BY name
`

func (q *Queries) ListShopsByOrganization(ctx context.Context, organizationID string) ([]Shop, error) {
	rows, err := q.db.Query(ctx, listShopsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shop{}
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.GitUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateShop = `-- name: UpdateShop :exec
UPDATE shop SET name = $1, description = $2, git_url = $3, updated_at = NOW() WHERE id = $4 AND organization_id = $5
`

type UpdateShopParams struct {
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	GitUrl         *string `json:"git_url"`
	ID             int32   `json:"id"`
	OrganizationID string  `json:"organization_id"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) error {
	_, err := q.db.Exec(ctx, updateShop,
		arg.Name,
		arg.Description,
		arg.GitUrl,
		arg.ID,
		arg.OrganizationID,
	)
	return err
}
