// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopware_version.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getKnownShopwareVersions = `-- name: GetKnownShopwareVersions :many
SELECT version FROM shopware_version
`

func (q *Queries) GetKnownShopwareVersions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getKnownShopwareVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopwareVersions = `-- name: ListShopwareVersions :many
SELECT version, release_date, php_versions
FROM shopware_version
ORDER BY release_date DESC, version DESC
`

type ListShopwareVersionsRow struct {
	Version     string           `json:"version"`
	ReleaseDate pgtype.Timestamp `json:"release_date"`
	PhpVersions json.RawMessage  `json:"php_versions"`
}

func (q *Queries) ListShopwareVersions(ctx context.Context) ([]ListShopwareVersionsRow, error) {
	rows, err := q.db.Query(ctx, listShopwareVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShopwareVersionsRow{}
	for rows.Next() {
		var i ListShopwareVersionsRow
		if err := rows.Scan(&i.Version, &i.ReleaseDate, &i.PhpVersions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShopwareVersion = `-- name: UpsertShopwareVersion :exec
INSERT INTO shopware_version (version, release_date, php_versions, title, body, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (version) DO UPDATE SET
  release_date = EXCLUDED.release_date,
  php_versions = EXCLUDED.php_versions,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  updated_at = NOW()
`

type UpsertShopwareVersionParams struct {
	Version     string           `json:"version"`
	ReleaseDate pgtype.Timestamp `json:"release_date"`
	PhpVersions json.RawMessage  `json:"php_versions"`
	Title       string           `json:"title"`
	Body        string           `json:"body"`
}

func (q *Queries) UpsertShopwareVersion(ctx context.Context, arg UpsertShopwareVersionParams) error {
	_, err := q.db.Exec(ctx, upsertShopwareVersion,
		arg.Version,
		arg.ReleaseDate,
		arg.PhpVersions,
		arg.Title,
		arg.Body,
	)
	return err
}
