// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso.sql

package queries

import (
	"context"
)

const deleteSSOProvider = `-- name: DeleteSSOProvider :exec
DELETE FROM sso_provider WHERE provider_id = $1 AND organization_id = $2
`

type DeleteSSOProviderParams struct {
	ProviderID     string  `json:"provider_id"`
	OrganizationID *string `json:"organization_id"`
}

func (q *Queries) DeleteSSOProvider(ctx context.Context, arg DeleteSSOProviderParams) error {
	_, err := q.db.Exec(ctx, deleteSSOProvider, arg.ProviderID, arg.OrganizationID)
	return err
}

const listSSOProviders = `-- name: ListSSOProviders :many
SELECT id, issuer, oidc_config, saml_config, user_id, provider_id, organization_id, domain
FROM sso_provider WHERE organization_id = $1
`

func (q *Queries) ListSSOProviders(ctx context.Context, organizationID *string) ([]SsoProvider, error) {
	rows, err := q.db.Query(ctx, listSSOProviders, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoProvider{}
	for rows.Next() {
		var i SsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.OidcConfig,
			&i.SamlConfig,
			&i.UserID,
			&i.ProviderID,
			&i.OrganizationID,
			&i.Domain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSSOProvider = `-- name: UpdateSSOProvider :exec
UPDATE sso_provider SET issuer = $1, oidc_config = $2, domain = $3 WHERE provider_id = $4 AND organization_id = $5
`

type UpdateSSOProviderParams struct {
	Issuer         string  `json:"issuer"`
	OidcConfig     *string `json:"oidc_config"`
	Domain         string  `json:"domain"`
	ProviderID     string  `json:"provider_id"`
	OrganizationID *string `json:"organization_id"`
}

func (q *Queries) UpdateSSOProvider(ctx context.Context, arg UpdateSSOProviderParams) error {
	_, err := q.db.Exec(ctx, updateSSOProvider,
		arg.Issuer,
		arg.OidcConfig,
		arg.Domain,
		arg.ProviderID,
		arg.OrganizationID,
	)
	return err
}
