// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_extension.sql

package queries

import (
	"context"
)

const cleanupOrphanedStoreExtensionSyncStates = `-- name: CleanupOrphanedStoreExtensionSyncStates :exec
DELETE FROM store_extension_sync
WHERE last_synced_at < NOW() - INTERVAL '7 days'
  AND NOT EXISTS (
    SELECT 1 FROM environment_store_extension ese WHERE ese.extension_name = store_extension_sync.extension_name
  )
  AND NOT EXISTS (
    SELECT 1 FROM environment_extension ee WHERE ee.name = store_extension_sync.extension_name
  )
`

// Sync bookkeeping for names no environment has anymore.
func (q *Queries) CleanupOrphanedStoreExtensionSyncStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOrphanedStoreExtensionSyncStates)
	return err
}

const cleanupUnusedStoreExtensionCompatibility = `-- name: CleanupUnusedStoreExtensionCompatibility :exec
DELETE FROM store_extension_compatibility
WHERE shopware_version NOT IN (SELECT DISTINCT shopware_version FROM environment)
`

// Compatibility rows for Shopware versions no environment runs anymore.
func (q *Queries) CleanupUnusedStoreExtensionCompatibility(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupUnusedStoreExtensionCompatibility)
	return err
}

const getDistinctEnvironmentShopwareVersions = `-- name: GetDistinctEnvironmentShopwareVersions :many
SELECT DISTINCT shopware_version FROM environment WHERE shopware_version != ''
`

func (q *Queries) GetDistinctEnvironmentShopwareVersions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctEnvironmentShopwareVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var shopware_version string
		if err := rows.Scan(&shopware_version); err != nil {
			return nil, err
		}
		items = append(items, shopware_version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFreshStoreExtensionSyncNames = `-- name: GetFreshStoreExtensionSyncNames :many

SELECT extension_name FROM store_extension_sync
WHERE extension_name = ANY($1::text[]) AND last_synced_at > NOW() - INTERVAL '1 hour'
`

// Queries backing the store extension catalog sync job. The catalog is shared
// across environments and refreshed by a dedicated queue job, never by the
// environment scrapes themselves.
// Names among the given set whose store lookup happened within the last hour
// (hit or miss). These do not need another sync.
func (q *Queries) GetFreshStoreExtensionSyncNames(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getFreshStoreExtensionSyncNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var extension_name string
		if err := rows.Scan(&extension_name); err != nil {
			return nil, err
		}
		items = append(items, extension_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreExtensionChangelogs = `-- name: GetStoreExtensionChangelogs :many
SELECT sev.version, sev.released_at,
       en.changelog AS changelog_en, de.changelog AS changelog_de
FROM store_extension_version sev
LEFT JOIN store_extension_version_translation en ON en.extension_version_id = sev.id AND en.language = 'en'
LEFT JOIN store_extension_version_translation de ON de.extension_version_id = sev.id AND de.language = 'de'
WHERE sev.extension_name = $1
`

type GetStoreExtensionChangelogsRow struct {
	Version     string  `json:"version"`
	ReleasedAt  *string `json:"released_at"`
	ChangelogEn *string `json:"changelog_en"`
	ChangelogDe *string `json:"changelog_de"`
}

// All catalog versions of one extension with both changelog translations, used
// to attach update changelogs to extension diffs directly from the database.
func (q *Queries) GetStoreExtensionChangelogs(ctx context.Context, extensionName string) ([]GetStoreExtensionChangelogsRow, error) {
	rows, err := q.db.Query(ctx, getStoreExtensionChangelogs, extensionName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStoreExtensionChangelogsRow{}
	for rows.Next() {
		var i GetStoreExtensionChangelogsRow
		if err := rows.Scan(
			&i.Version,
			&i.ReleasedAt,
			&i.ChangelogEn,
			&i.ChangelogDe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreExtensionCompatibility = `-- name: GetStoreExtensionCompatibility :many
SELECT extension_name, latest_version FROM store_extension_compatibility
WHERE extension_name = ANY($1::text[]) AND shopware_version = $2
`

type GetStoreExtensionCompatibilityParams struct {
	Column1         []string `json:"column_1"`
	ShopwareVersion string   `json:"shopware_version"`
}

type GetStoreExtensionCompatibilityRow struct {
	ExtensionName string  `json:"extension_name"`
	LatestVersion *string `json:"latest_version"`
}

// Compatible latest versions for the given extensions on one Shopware version.
// A row with NULL latest_version means "checked, no compatible release".
func (q *Queries) GetStoreExtensionCompatibility(ctx context.Context, arg GetStoreExtensionCompatibilityParams) ([]GetStoreExtensionCompatibilityRow, error) {
	rows, err := q.db.Query(ctx, getStoreExtensionCompatibility, arg.Column1, arg.ShopwareVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStoreExtensionCompatibilityRow{}
	for rows.Next() {
		var i GetStoreExtensionCompatibilityRow
		if err := rows.Scan(&i.ExtensionName, &i.LatestVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreExtensionNamesIn = `-- name: GetStoreExtensionNamesIn :many
SELECT name FROM store_extension WHERE name = ANY($1::text[])
`

// Which of the given names exist in the shared store catalog. Membership here
// is what classifies a scraped extension as store-known.
func (q *Queries) GetStoreExtensionNamesIn(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getStoreExtensionNamesIn, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStoreExtensionCompatibility = `-- name: UpsertStoreExtensionCompatibility :exec
INSERT INTO store_extension_compatibility (extension_name, shopware_version, latest_version)
VALUES ($1, $2, $3)
ON CONFLICT (extension_name, shopware_version) DO UPDATE SET latest_version = $3
WHERE store_extension_compatibility.latest_version IS DISTINCT FROM $3
`

type UpsertStoreExtensionCompatibilityParams struct {
	ExtensionName   string  `json:"extension_name"`
	ShopwareVersion string  `json:"shopware_version"`
	LatestVersion   *string `json:"latest_version"`
}

func (q *Queries) UpsertStoreExtensionCompatibility(ctx context.Context, arg UpsertStoreExtensionCompatibilityParams) error {
	_, err := q.db.Exec(ctx, upsertStoreExtensionCompatibility, arg.ExtensionName, arg.ShopwareVersion, arg.LatestVersion)
	return err
}

const upsertStoreExtensionSyncStates = `-- name: UpsertStoreExtensionSyncStates :exec
INSERT INTO store_extension_sync (extension_name, last_synced_at)
SELECT unnest($1::text[]), NOW()
ON CONFLICT (extension_name) DO UPDATE SET last_synced_at = NOW()
`

// Marks all given names as looked up now, whether or not the store knew them.
func (q *Queries) UpsertStoreExtensionSyncStates(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, upsertStoreExtensionSyncStates, dollar_1)
	return err
}
