// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uptime.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueUptimeMonitors = `-- name: ClaimDueUptimeMonitors :many
UPDATE environment_uptime u SET
  next_check_at = NOW() + make_interval(secs => u.interval_seconds::int)
FROM environment e
WHERE e.id = u.environment_id
  AND u.enabled = true
  AND u.status <> 'paused'
  AND u.next_check_at IS NOT NULL
  AND u.next_check_at <= $1
  AND (u.environment_id % $2) = $3
RETURNING
  u.environment_id, u.url, u.interval_seconds, u.expected_status, u.content_match,
  u.failure_threshold, u.recovery_threshold, u.status,
  u.consecutive_failures, u.consecutive_successes,
  e.url AS environment_url, e.name AS environment_name, e.organization_id
`

type ClaimDueUptimeMonitorsParams struct {
	Now        pgtype.Timestamp `json:"now"`
	ShardTotal int32            `json:"shard_total"`
	ShardIndex int32            `json:"shard_index"`
}

type ClaimDueUptimeMonitorsRow struct {
	EnvironmentID        int32   `json:"environment_id"`
	Url                  *string `json:"url"`
	IntervalSeconds      int32   `json:"interval_seconds"`
	ExpectedStatus       int32   `json:"expected_status"`
	ContentMatch         *string `json:"content_match"`
	FailureThreshold     int32   `json:"failure_threshold"`
	RecoveryThreshold    int32   `json:"recovery_threshold"`
	Status               string  `json:"status"`
	ConsecutiveFailures  int32   `json:"consecutive_failures"`
	ConsecutiveSuccesses int32   `json:"consecutive_successes"`
	EnvironmentUrl       string  `json:"environment_url"`
	EnvironmentName      string  `json:"environment_name"`
	OrganizationID       string  `json:"organization_id"`
}

// Atomically claims due monitors by pushing next_check_at forward before they
// are probed, so concurrent ticks (or a slow probe overlapping the next tick)
// can never probe the same monitor twice.
func (q *Queries) ClaimDueUptimeMonitors(ctx context.Context, arg ClaimDueUptimeMonitorsParams) ([]ClaimDueUptimeMonitorsRow, error) {
	rows, err := q.db.Query(ctx, claimDueUptimeMonitors, arg.Now, arg.ShardTotal, arg.ShardIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimDueUptimeMonitorsRow{}
	for rows.Next() {
		var i ClaimDueUptimeMonitorsRow
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.Url,
			&i.IntervalSeconds,
			&i.ExpectedStatus,
			&i.ContentMatch,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.EnvironmentUrl,
			&i.EnvironmentName,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUptimeEventsOlderThan = `-- name: DeleteUptimeEventsOlderThan :exec
DELETE FROM environment_uptime_event WHERE started_at < $1 AND resolved_at IS NOT NULL
`

func (q *Queries) DeleteUptimeEventsOlderThan(ctx context.Context, startedAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteUptimeEventsOlderThan, startedAt)
	return err
}

const deleteUptimeHourlyRollupsOlderThan = `-- name: DeleteUptimeHourlyRollupsOlderThan :exec
DELETE FROM environment_uptime_rollup_hourly WHERE hour < $1
`

func (q *Queries) DeleteUptimeHourlyRollupsOlderThan(ctx context.Context, hour pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteUptimeHourlyRollupsOlderThan, hour)
	return err
}

const getOpenUptimeEvent = `-- name: GetOpenUptimeEvent :one
SELECT id, environment_id, started_at, resolved_at, status_code, latency_ms, error FROM environment_uptime_event
WHERE environment_id = $1 AND resolved_at IS NULL
ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetOpenUptimeEvent(ctx context.Context, environmentID int32) (EnvironmentUptimeEvent, error) {
	row := q.db.QueryRow(ctx, getOpenUptimeEvent, environmentID)
	var i EnvironmentUptimeEvent
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.StatusCode,
		&i.LatencyMs,
		&i.Error,
	)
	return i, err
}

const getUptimeSettings = `-- name: GetUptimeSettings :one
SELECT
  u.environment_id, u.enabled, u.url, u.interval_seconds, u.expected_status,
  u.content_match, u.failure_threshold, u.recovery_threshold, u.status,
  u.last_checked_at, u.last_status_code, u.last_latency_ms, u.last_error,
  e.url AS environment_url, e.name AS environment_name, e.organization_id
FROM environment_uptime u
JOIN environment e ON e.id = u.environment_id
WHERE u.environment_id = $1
`

type GetUptimeSettingsRow struct {
	EnvironmentID     int32            `json:"environment_id"`
	Enabled           bool             `json:"enabled"`
	Url               *string          `json:"url"`
	IntervalSeconds   int32            `json:"interval_seconds"`
	ExpectedStatus    int32            `json:"expected_status"`
	ContentMatch      *string          `json:"content_match"`
	FailureThreshold  int32            `json:"failure_threshold"`
	RecoveryThreshold int32            `json:"recovery_threshold"`
	Status            string           `json:"status"`
	LastCheckedAt     pgtype.Timestamp `json:"last_checked_at"`
	LastStatusCode    *int32           `json:"last_status_code"`
	LastLatencyMs     *int32           `json:"last_latency_ms"`
	LastError         *string          `json:"last_error"`
	EnvironmentUrl    string           `json:"environment_url"`
	EnvironmentName   string           `json:"environment_name"`
	OrganizationID    string           `json:"organization_id"`
}

func (q *Queries) GetUptimeSettings(ctx context.Context, environmentID int32) (GetUptimeSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUptimeSettings, environmentID)
	var i GetUptimeSettingsRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.Enabled,
		&i.Url,
		&i.IntervalSeconds,
		&i.ExpectedStatus,
		&i.ContentMatch,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.Status,
		&i.LastCheckedAt,
		&i.LastStatusCode,
		&i.LastLatencyMs,
		&i.LastError,
		&i.EnvironmentUrl,
		&i.EnvironmentName,
		&i.OrganizationID,
	)
	return i, err
}

const insertUptimeEvent = `-- name: InsertUptimeEvent :one
INSERT INTO environment_uptime_event (environment_id, started_at, status_code, latency_ms, error)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertUptimeEventParams struct {
	EnvironmentID int32            `json:"environment_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
	StatusCode    *int32           `json:"status_code"`
	LatencyMs     *int32           `json:"latency_ms"`
	Error         *string          `json:"error"`
}

func (q *Queries) InsertUptimeEvent(ctx context.Context, arg InsertUptimeEventParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertUptimeEvent,
		arg.EnvironmentID,
		arg.StartedAt,
		arg.StatusCode,
		arg.LatencyMs,
		arg.Error,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listUptimeDailyAggregateTargets = `-- name: ListUptimeDailyAggregateTargets :many
SELECT DISTINCT environment_id FROM (
  SELECT environment_id FROM environment_uptime_event
  WHERE started_at < $1 AND (resolved_at IS NULL OR resolved_at > $2)
  UNION
  SELECT environment_id FROM environment_uptime_rollup_hourly
  WHERE hour >= $2 AND hour < $1
) t
`

type ListUptimeDailyAggregateTargetsParams struct {
	RangeTo   pgtype.Timestamp `json:"range_to"`
	RangeFrom pgtype.Timestamp `json:"range_from"`
}

func (q *Queries) ListUptimeDailyAggregateTargets(ctx context.Context, arg ListUptimeDailyAggregateTargetsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listUptimeDailyAggregateTargets, arg.RangeTo, arg.RangeFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var environment_id int32
		if err := rows.Scan(&environment_id); err != nil {
			return nil, err
		}
		items = append(items, environment_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeDailyRollups = `-- name: ListUptimeDailyRollups :many
SELECT environment_id, day, up_seconds, down_seconds, paused_seconds, nodata_seconds, latency_avg_ms, latency_p95_ms FROM environment_uptime_rollup_daily
WHERE environment_id = $1 AND day >= $2 AND day <= $3
ORDER BY day
`

type ListUptimeDailyRollupsParams struct {
	EnvironmentID int32       `json:"environment_id"`
	Day           pgtype.Date `json:"day"`
	Day_2         pgtype.Date `json:"day_2"`
}

func (q *Queries) ListUptimeDailyRollups(ctx context.Context, arg ListUptimeDailyRollupsParams) ([]EnvironmentUptimeRollupDaily, error) {
	rows, err := q.db.Query(ctx, listUptimeDailyRollups, arg.EnvironmentID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentUptimeRollupDaily{}
	for rows.Next() {
		var i EnvironmentUptimeRollupDaily
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.Day,
			&i.UpSeconds,
			&i.DownSeconds,
			&i.PausedSeconds,
			&i.NodataSeconds,
			&i.LatencyAvgMs,
			&i.LatencyP95Ms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeEvents = `-- name: ListUptimeEvents :many
SELECT id, environment_id, started_at, resolved_at, status_code, latency_ms, error FROM environment_uptime_event
WHERE environment_id = $1 AND started_at >= $2
ORDER BY started_at DESC
`

type ListUptimeEventsParams struct {
	EnvironmentID int32            `json:"environment_id"`
	StartedAt     pgtype.Timestamp `json:"started_at"`
}

func (q *Queries) ListUptimeEvents(ctx context.Context, arg ListUptimeEventsParams) ([]EnvironmentUptimeEvent, error) {
	rows, err := q.db.Query(ctx, listUptimeEvents, arg.EnvironmentID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentUptimeEvent{}
	for rows.Next() {
		var i EnvironmentUptimeEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.StatusCode,
			&i.LatencyMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeEventsOverlapping = `-- name: ListUptimeEventsOverlapping :many
SELECT id, environment_id, started_at, resolved_at, status_code, latency_ms, error FROM environment_uptime_event
WHERE environment_id = $1
  AND started_at < $2
  AND (resolved_at IS NULL OR resolved_at > $3)
`

type ListUptimeEventsOverlappingParams struct {
	EnvironmentID int32            `json:"environment_id"`
	RangeTo       pgtype.Timestamp `json:"range_to"`
	RangeFrom     pgtype.Timestamp `json:"range_from"`
}

func (q *Queries) ListUptimeEventsOverlapping(ctx context.Context, arg ListUptimeEventsOverlappingParams) ([]EnvironmentUptimeEvent, error) {
	rows, err := q.db.Query(ctx, listUptimeEventsOverlapping, arg.EnvironmentID, arg.RangeTo, arg.RangeFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentUptimeEvent{}
	for rows.Next() {
		var i EnvironmentUptimeEvent
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.StatusCode,
			&i.LatencyMs,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeHourlyRollups = `-- name: ListUptimeHourlyRollups :many
SELECT environment_id, hour, probes_expected, probes_run, probes_ok, paused_seconds, latency_avg_ms, latency_p95_ms FROM environment_uptime_rollup_hourly
WHERE environment_id = $1 AND hour >= $2 AND hour < $3
ORDER BY hour
`

type ListUptimeHourlyRollupsParams struct {
	EnvironmentID int32            `json:"environment_id"`
	Hour          pgtype.Timestamp `json:"hour"`
	Hour_2        pgtype.Timestamp `json:"hour_2"`
}

func (q *Queries) ListUptimeHourlyRollups(ctx context.Context, arg ListUptimeHourlyRollupsParams) ([]EnvironmentUptimeRollupHourly, error) {
	rows, err := q.db.Query(ctx, listUptimeHourlyRollups, arg.EnvironmentID, arg.Hour, arg.Hour_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentUptimeRollupHourly{}
	for rows.Next() {
		var i EnvironmentUptimeRollupHourly
		if err := rows.Scan(
			&i.EnvironmentID,
			&i.Hour,
			&i.ProbesExpected,
			&i.ProbesRun,
			&i.ProbesOk,
			&i.PausedSeconds,
			&i.LatencyAvgMs,
			&i.LatencyP95Ms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseUptimeMonitor = `-- name: PauseUptimeMonitor :exec
UPDATE environment_uptime SET
  status = 'paused',
  next_check_at = NULL
WHERE environment_id = $1
`

func (q *Queries) PauseUptimeMonitor(ctx context.Context, environmentID int32) error {
	_, err := q.db.Exec(ctx, pauseUptimeMonitor, environmentID)
	return err
}

const resolveUptimeEvents = `-- name: ResolveUptimeEvents :exec
UPDATE environment_uptime_event SET resolved_at = $2
WHERE environment_id = $1 AND resolved_at IS NULL
`

type ResolveUptimeEventsParams struct {
	EnvironmentID int32            `json:"environment_id"`
	ResolvedAt    pgtype.Timestamp `json:"resolved_at"`
}

func (q *Queries) ResolveUptimeEvents(ctx context.Context, arg ResolveUptimeEventsParams) error {
	_, err := q.db.Exec(ctx, resolveUptimeEvents, arg.EnvironmentID, arg.ResolvedAt)
	return err
}

const resumeUptimeMonitor = `-- name: ResumeUptimeMonitor :exec
UPDATE environment_uptime SET
  status = 'unknown',
  consecutive_failures = 0,
  consecutive_successes = 0,
  next_check_at = NOW()
WHERE environment_id = $1 AND enabled = true
`

func (q *Queries) ResumeUptimeMonitor(ctx context.Context, environmentID int32) error {
	_, err := q.db.Exec(ctx, resumeUptimeMonitor, environmentID)
	return err
}

const updateUptimeProbeState = `-- name: UpdateUptimeProbeState :exec
UPDATE environment_uptime SET
  status = $2,
  consecutive_failures = $3,
  consecutive_successes = $4,
  last_checked_at = NOW(),
  last_status_code = $5,
  last_latency_ms = $6,
  last_error = $7
WHERE environment_id = $1
`

type UpdateUptimeProbeStateParams struct {
	EnvironmentID        int32   `json:"environment_id"`
	Status               string  `json:"status"`
	ConsecutiveFailures  int32   `json:"consecutive_failures"`
	ConsecutiveSuccesses int32   `json:"consecutive_successes"`
	LastStatusCode       *int32  `json:"last_status_code"`
	LastLatencyMs        *int32  `json:"last_latency_ms"`
	LastError            *string `json:"last_error"`
}

func (q *Queries) UpdateUptimeProbeState(ctx context.Context, arg UpdateUptimeProbeStateParams) error {
	_, err := q.db.Exec(ctx, updateUptimeProbeState,
		arg.EnvironmentID,
		arg.Status,
		arg.ConsecutiveFailures,
		arg.ConsecutiveSuccesses,
		arg.LastStatusCode,
		arg.LastLatencyMs,
		arg.LastError,
	)
	return err
}

const upsertUptimeDailyRollup = `-- name: UpsertUptimeDailyRollup :exec
INSERT INTO environment_uptime_rollup_daily (
  environment_id, day, up_seconds, down_seconds, paused_seconds, nodata_seconds,
  latency_avg_ms, latency_p95_ms
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (environment_id, day) DO UPDATE SET
  up_seconds = EXCLUDED.up_seconds,
  down_seconds = EXCLUDED.down_seconds,
  paused_seconds = EXCLUDED.paused_seconds,
  nodata_seconds = EXCLUDED.nodata_seconds,
  latency_avg_ms = EXCLUDED.latency_avg_ms,
  latency_p95_ms = EXCLUDED.latency_p95_ms
`

type UpsertUptimeDailyRollupParams struct {
	EnvironmentID int32       `json:"environment_id"`
	Day           pgtype.Date `json:"day"`
	UpSeconds     int32       `json:"up_seconds"`
	DownSeconds   int32       `json:"down_seconds"`
	PausedSeconds int32       `json:"paused_seconds"`
	NodataSeconds int32       `json:"nodata_seconds"`
	LatencyAvgMs  *int32      `json:"latency_avg_ms"`
	LatencyP95Ms  *int32      `json:"latency_p95_ms"`
}

func (q *Queries) UpsertUptimeDailyRollup(ctx context.Context, arg UpsertUptimeDailyRollupParams) error {
	_, err := q.db.Exec(ctx, upsertUptimeDailyRollup,
		arg.EnvironmentID,
		arg.Day,
		arg.UpSeconds,
		arg.DownSeconds,
		arg.PausedSeconds,
		arg.NodataSeconds,
		arg.LatencyAvgMs,
		arg.LatencyP95Ms,
	)
	return err
}

const upsertUptimeHourlyRollup = `-- name: UpsertUptimeHourlyRollup :exec
INSERT INTO environment_uptime_rollup_hourly (
  environment_id, hour, probes_expected, probes_run, probes_ok, paused_seconds,
  latency_avg_ms, latency_p95_ms
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (environment_id, hour) DO UPDATE SET
  probes_expected = GREATEST(environment_uptime_rollup_hourly.probes_expected, EXCLUDED.probes_expected),
  probes_run = environment_uptime_rollup_hourly.probes_run + EXCLUDED.probes_run,
  probes_ok = environment_uptime_rollup_hourly.probes_ok + EXCLUDED.probes_ok,
  paused_seconds = environment_uptime_rollup_hourly.paused_seconds + EXCLUDED.paused_seconds,
  latency_avg_ms = CASE
    WHEN environment_uptime_rollup_hourly.latency_avg_ms IS NULL THEN EXCLUDED.latency_avg_ms
    WHEN EXCLUDED.latency_avg_ms IS NULL THEN environment_uptime_rollup_hourly.latency_avg_ms
    ELSE (environment_uptime_rollup_hourly.latency_avg_ms * environment_uptime_rollup_hourly.probes_run
        + EXCLUDED.latency_avg_ms * EXCLUDED.probes_run)
        / (environment_uptime_rollup_hourly.probes_run + EXCLUDED.probes_run)
  END,
  latency_p95_ms = GREATEST(environment_uptime_rollup_hourly.latency_p95_ms, EXCLUDED.latency_p95_ms)
`

type UpsertUptimeHourlyRollupParams struct {
	EnvironmentID  int32            `json:"environment_id"`
	Hour           pgtype.Timestamp `json:"hour"`
	ProbesExpected int32            `json:"probes_expected"`
	ProbesRun      int32            `json:"probes_run"`
	ProbesOk       int32            `json:"probes_ok"`
	PausedSeconds  int32            `json:"paused_seconds"`
	LatencyAvgMs   *int32           `json:"latency_avg_ms"`
	LatencyP95Ms   *int32           `json:"latency_p95_ms"`
}

// Additive on conflict: the same hour can be flushed more than once when a
// probe started in hour H completes after H was already flushed; late samples
// must merge into the existing row, not replace it.
func (q *Queries) UpsertUptimeHourlyRollup(ctx context.Context, arg UpsertUptimeHourlyRollupParams) error {
	_, err := q.db.Exec(ctx, upsertUptimeHourlyRollup,
		arg.EnvironmentID,
		arg.Hour,
		arg.ProbesExpected,
		arg.ProbesRun,
		arg.ProbesOk,
		arg.PausedSeconds,
		arg.LatencyAvgMs,
		arg.LatencyP95Ms,
	)
	return err
}

const upsertUptimeSettings = `-- name: UpsertUptimeSettings :exec
INSERT INTO environment_uptime (
  environment_id, enabled, url, interval_seconds, expected_status, content_match,
  failure_threshold, recovery_threshold, status, next_check_at
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, 'unknown',
  CASE WHEN $2 THEN NOW() ELSE NULL END
)
ON CONFLICT (environment_id) DO UPDATE SET
  enabled = EXCLUDED.enabled,
  url = EXCLUDED.url,
  interval_seconds = EXCLUDED.interval_seconds,
  expected_status = EXCLUDED.expected_status,
  content_match = EXCLUDED.content_match,
  failure_threshold = EXCLUDED.failure_threshold,
  recovery_threshold = EXCLUDED.recovery_threshold,
  -- Enabling (re-)arms the monitor: fresh state, first probe immediately.
  status = 'unknown',
  consecutive_failures = 0,
  consecutive_successes = 0,
  next_check_at = CASE WHEN EXCLUDED.enabled THEN NOW() ELSE NULL END
`

type UpsertUptimeSettingsParams struct {
	EnvironmentID     int32   `json:"environment_id"`
	Enabled           bool    `json:"enabled"`
	Url               *string `json:"url"`
	IntervalSeconds   int32   `json:"interval_seconds"`
	ExpectedStatus    int32   `json:"expected_status"`
	ContentMatch      *string `json:"content_match"`
	FailureThreshold  int32   `json:"failure_threshold"`
	RecoveryThreshold int32   `json:"recovery_threshold"`
}

func (q *Queries) UpsertUptimeSettings(ctx context.Context, arg UpsertUptimeSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertUptimeSettings,
		arg.EnvironmentID,
		arg.Enabled,
		arg.Url,
		arg.IntervalSeconds,
		arg.ExpectedStatus,
		arg.ContentMatch,
		arg.FailureThreshold,
		arg.RecoveryThreshold,
	)
	return err
}
