// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.expires_at, s.token, s.user_id, s.active_organization_id, s.impersonated_by,
       u.id as user_id, u.name as user_name, u.email as user_email, u.role as user_role, u.notifications as user_notifications, u.image as user_image, u.banned as user_banned
FROM session s
JOIN "user" u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetSessionByTokenRow struct {
	ID                   string           `json:"id"`
	ExpiresAt            pgtype.Timestamp `json:"expires_at"`
	Token                string           `json:"token"`
	UserID               string           `json:"user_id"`
	ActiveOrganizationID *string          `json:"active_organization_id"`
	ImpersonatedBy       *string          `json:"impersonated_by"`
	UserID_2             string           `json:"user_id_2"`
	UserName             string           `json:"user_name"`
	UserEmail            string           `json:"user_email"`
	UserRole             string           `json:"user_role"`
	UserNotifications    []byte           `json:"user_notifications"`
	UserImage            *string          `json:"user_image"`
	UserBanned           *bool            `json:"user_banned"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.ImpersonatedBy,
		&i.UserID_2,
		&i.UserName,
		&i.UserEmail,
		&i.UserRole,
		&i.UserNotifications,
		&i.UserImage,
		&i.UserBanned,
	)
	return i, err
}

const getShopOrganizationID = `-- name: GetShopOrganizationID :one
SELECT organization_id FROM shop WHERE id = $1
`

func (q *Queries) GetShopOrganizationID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getShopOrganizationID, id)
	var organization_id string
	err := row.Scan(&organization_id)
	return organization_id, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, image, created_at, updated_at, role, banned, ban_reason, ban_expires, notifications FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.Notifications,
	)
	return i, err
}

const getUserChangelogs = `-- name: GetUserChangelogs :many
SELECT sc.id, sc.shop_id, sc.extensions, sc.old_shopware_version, sc.new_shopware_version, sc.date,
       s.name AS shop_name, o.name AS shop_organization_name, s.organization_id AS shop_organization_id
FROM shop_changelog sc
JOIN shop s ON s.id = sc.shop_id
JOIN organization o ON o.id = s.organization_id
JOIN member m ON m.organization_id = s.organization_id
WHERE m.user_id = $1
ORDER BY sc.date DESC
LIMIT 10
`

type GetUserChangelogsRow struct {
	ID                   int32            `json:"id"`
	ShopID               *int32           `json:"shop_id"`
	Extensions           json.RawMessage  `json:"extensions"`
	OldShopwareVersion   *string          `json:"old_shopware_version"`
	NewShopwareVersion   *string          `json:"new_shopware_version"`
	Date                 pgtype.Timestamp `json:"date"`
	ShopName             string           `json:"shop_name"`
	ShopOrganizationName string           `json:"shop_organization_name"`
	ShopOrganizationID   string           `json:"shop_organization_id"`
}

func (q *Queries) GetUserChangelogs(ctx context.Context, userID string) ([]GetUserChangelogsRow, error) {
	rows, err := q.db.Query(ctx, getUserChangelogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserChangelogsRow{}
	for rows.Next() {
		var i GetUserChangelogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Extensions,
			&i.OldShopwareVersion,
			&i.NewShopwareVersion,
			&i.Date,
			&i.ShopName,
			&i.ShopOrganizationName,
			&i.ShopOrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserExtensions = `-- name: GetUserExtensions :many
SELECT se.name, se.label, se.version, se.latest_version, se.active, se.installed,
       se.store_link, se.rating_average, se.installed_at, se.changelog,
       se.shop_id, s.name AS shop_name, s.url AS shop_url, o.name AS shop_organization_name, s.organization_id AS shop_organization_id
FROM shop_extension se
JOIN shop s ON s.id = se.shop_id
JOIN organization o ON o.id = s.organization_id
JOIN member m ON m.organization_id = s.organization_id
WHERE m.user_id = $1
ORDER BY se.name, s.name
`

type GetUserExtensionsRow struct {
	Name                 string  `json:"name"`
	Label                string  `json:"label"`
	Version              string  `json:"version"`
	LatestVersion        *string `json:"latest_version"`
	Active               bool    `json:"active"`
	Installed            bool    `json:"installed"`
	StoreLink            *string `json:"store_link"`
	RatingAverage        *int32  `json:"rating_average"`
	InstalledAt          *string `json:"installed_at"`
	Changelog            []byte  `json:"changelog"`
	ShopID               int32   `json:"shop_id"`
	ShopName             string  `json:"shop_name"`
	ShopUrl              string  `json:"shop_url"`
	ShopOrganizationName string  `json:"shop_organization_name"`
	ShopOrganizationID   string  `json:"shop_organization_id"`
}

func (q *Queries) GetUserExtensions(ctx context.Context, userID string) ([]GetUserExtensionsRow, error) {
	rows, err := q.db.Query(ctx, getUserExtensions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserExtensionsRow{}
	for rows.Next() {
		var i GetUserExtensionsRow
		if err := rows.Scan(
			&i.Name,
			&i.Label,
			&i.Version,
			&i.LatestVersion,
			&i.Active,
			&i.Installed,
			&i.StoreLink,
			&i.RatingAverage,
			&i.InstalledAt,
			&i.Changelog,
			&i.ShopID,
			&i.ShopName,
			&i.ShopUrl,
			&i.ShopOrganizationName,
			&i.ShopOrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotifications = `-- name: GetUserNotifications :one
SELECT notifications FROM "user" WHERE id = $1
`

func (q *Queries) GetUserNotifications(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserNotifications, id)
	var notifications []byte
	err := row.Scan(&notifications)
	return notifications, err
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT o.id, o.name, o.slug, o.logo, o.created_at,
       (SELECT COUNT(*) FROM shop WHERE organization_id = o.id)::int AS shop_count,
       (SELECT COUNT(*) FROM member WHERE organization_id = o.id)::int AS member_count
FROM organization o
JOIN member m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.name
`

type GetUserOrganizationsRow struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Slug        string           `json:"slug"`
	Logo        *string          `json:"logo"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ShopCount   int32            `json:"shop_count"`
	MemberCount int32            `json:"member_count"`
}

func (q *Queries) GetUserOrganizations(ctx context.Context, userID string) ([]GetUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserOrganizationsRow{}
	for rows.Next() {
		var i GetUserOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.ShopCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProjects = `-- name: GetUserProjects :many
SELECT p.id, p.name, p.description, p.git_url, p.organization_id, o.name AS organization_name
FROM project p
JOIN member m ON m.organization_id = p.organization_id
JOIN organization o ON o.id = p.organization_id
WHERE m.user_id = $1
ORDER BY p.name
`

type GetUserProjectsRow struct {
	ID               int32   `json:"id"`
	Name             string  `json:"name"`
	Description      *string `json:"description"`
	GitUrl           *string `json:"git_url"`
	OrganizationID   string  `json:"organization_id"`
	OrganizationName string  `json:"organization_name"`
}

func (q *Queries) GetUserProjects(ctx context.Context, userID string) ([]GetUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, getUserProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserProjectsRow{}
	for rows.Next() {
		var i GetUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GitUrl,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserShops = `-- name: GetUserShops :many
SELECT s.id, s.name, s.url, s.favicon, s.status, s.shopware_version, s.last_scraped_at, s.last_scraped_error,
       s.organization_id, o.name AS organization_name, p.id AS project_id, p.name AS project_name
FROM shop s
JOIN member m ON m.organization_id = s.organization_id
JOIN organization o ON o.id = s.organization_id
LEFT JOIN project p ON p.id = s.project_id
WHERE m.user_id = $1
ORDER BY s.name
`

type GetUserShopsRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Url              string           `json:"url"`
	Favicon          *string          `json:"favicon"`
	Status           string           `json:"status"`
	ShopwareVersion  string           `json:"shopware_version"`
	LastScrapedAt    pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError *string          `json:"last_scraped_error"`
	OrganizationID   string           `json:"organization_id"`
	OrganizationName string           `json:"organization_name"`
	ProjectID        *int32           `json:"project_id"`
	ProjectName      *string          `json:"project_name"`
}

func (q *Queries) GetUserShops(ctx context.Context, userID string) ([]GetUserShopsRow, error) {
	rows, err := q.db.Query(ctx, getUserShops, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserShopsRow{}
	for rows.Next() {
		var i GetUserShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Favicon,
			&i.Status,
			&i.ShopwareVersion,
			&i.LastScrapedAt,
			&i.LastScrapedError,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isOrganizationMember = `-- name: IsOrganizationMember :one
SELECT COUNT(*) > 0 AS is_member FROM member WHERE organization_id = $1 AND user_id = $2
`

type IsOrganizationMemberParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) IsOrganizationMember(ctx context.Context, arg IsOrganizationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOrganizationMember, arg.OrganizationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const updateUserNotifications = `-- name: UpdateUserNotifications :exec
UPDATE "user" SET notifications = $1 WHERE id = $2
`

type UpdateUserNotificationsParams struct {
	Notifications []byte `json:"notifications"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateUserNotifications(ctx context.Context, arg UpdateUserNotificationsParams) error {
	_, err := q.db.Exec(ctx, updateUserNotifications, arg.Notifications, arg.ID)
	return err
}
