// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnvironmentOrganizationID = `-- name: GetEnvironmentOrganizationID :one
SELECT organization_id FROM environment WHERE id = $1
`

func (q *Queries) GetEnvironmentOrganizationID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getEnvironmentOrganizationID, id)
	var organization_id string
	err := row.Scan(&organization_id)
	return organization_id, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.expires_at, s.token, s.user_id, s.active_organization_id, s.impersonated_by,
       u.id as user_id, u.name as user_name, u.email as user_email, u.role as user_role, u.notifications as user_notifications, u.image as user_image, u.banned as user_banned, u.ban_expires as user_ban_expires
FROM session s
JOIN "user" u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetSessionByTokenRow struct {
	ID                   string           `json:"id"`
	ExpiresAt            pgtype.Timestamp `json:"expires_at"`
	Token                string           `json:"token"`
	UserID               string           `json:"user_id"`
	ActiveOrganizationID *string          `json:"active_organization_id"`
	ImpersonatedBy       *string          `json:"impersonated_by"`
	UserID_2             string           `json:"user_id_2"`
	UserName             string           `json:"user_name"`
	UserEmail            string           `json:"user_email"`
	UserRole             string           `json:"user_role"`
	UserNotifications    []byte           `json:"user_notifications"`
	UserImage            *string          `json:"user_image"`
	UserBanned           *bool            `json:"user_banned"`
	UserBanExpires       pgtype.Timestamp `json:"user_ban_expires"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.UserID,
		&i.ActiveOrganizationID,
		&i.ImpersonatedBy,
		&i.UserID_2,
		&i.UserName,
		&i.UserEmail,
		&i.UserRole,
		&i.UserNotifications,
		&i.UserImage,
		&i.UserBanned,
		&i.UserBanExpires,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, image, created_at, updated_at, role, banned, ban_reason, ban_expires, notifications, locale FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.Notifications,
		&i.Locale,
	)
	return i, err
}

const getUserChangelogs = `-- name: GetUserChangelogs :many
SELECT ec.id, ec.environment_id, ec.extensions, ec.old_shopware_version, ec.new_shopware_version, ec.date,
       e.name AS environment_name, o.name AS environment_organization_name, e.organization_id AS environment_organization_id
FROM environment_changelog ec
JOIN environment e ON e.id = ec.environment_id
JOIN organization o ON o.id = e.organization_id
JOIN member m ON m.organization_id = e.organization_id
WHERE m.user_id = $1
ORDER BY ec.date DESC
LIMIT 10
`

type GetUserChangelogsRow struct {
	ID                          int32            `json:"id"`
	EnvironmentID               *int32           `json:"environment_id"`
	Extensions                  json.RawMessage  `json:"extensions"`
	OldShopwareVersion          *string          `json:"old_shopware_version"`
	NewShopwareVersion          *string          `json:"new_shopware_version"`
	Date                        pgtype.Timestamp `json:"date"`
	EnvironmentName             string           `json:"environment_name"`
	EnvironmentOrganizationName string           `json:"environment_organization_name"`
	EnvironmentOrganizationID   string           `json:"environment_organization_id"`
}

func (q *Queries) GetUserChangelogs(ctx context.Context, userID string) ([]GetUserChangelogsRow, error) {
	rows, err := q.db.Query(ctx, getUserChangelogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserChangelogsRow{}
	for rows.Next() {
		var i GetUserChangelogsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Extensions,
			&i.OldShopwareVersion,
			&i.NewShopwareVersion,
			&i.Date,
			&i.EnvironmentName,
			&i.EnvironmentOrganizationName,
			&i.EnvironmentOrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChangelogsByOrg = `-- name: GetUserChangelogsByOrg :many
SELECT ec.id, ec.environment_id, ec.extensions, ec.old_shopware_version, ec.new_shopware_version, ec.date,
       e.name AS environment_name, o.name AS environment_organization_name, e.organization_id AS environment_organization_id
FROM environment_changelog ec
JOIN environment e ON e.id = ec.environment_id
JOIN organization o ON o.id = e.organization_id
JOIN member m ON m.organization_id = e.organization_id
WHERE m.user_id = $1 AND e.organization_id = $2
ORDER BY ec.date DESC
LIMIT 10
`

type GetUserChangelogsByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

type GetUserChangelogsByOrgRow struct {
	ID                          int32            `json:"id"`
	EnvironmentID               *int32           `json:"environment_id"`
	Extensions                  json.RawMessage  `json:"extensions"`
	OldShopwareVersion          *string          `json:"old_shopware_version"`
	NewShopwareVersion          *string          `json:"new_shopware_version"`
	Date                        pgtype.Timestamp `json:"date"`
	EnvironmentName             string           `json:"environment_name"`
	EnvironmentOrganizationName string           `json:"environment_organization_name"`
	EnvironmentOrganizationID   string           `json:"environment_organization_id"`
}

func (q *Queries) GetUserChangelogsByOrg(ctx context.Context, arg GetUserChangelogsByOrgParams) ([]GetUserChangelogsByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUserChangelogsByOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserChangelogsByOrgRow{}
	for rows.Next() {
		var i GetUserChangelogsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Extensions,
			&i.OldShopwareVersion,
			&i.NewShopwareVersion,
			&i.Date,
			&i.EnvironmentName,
			&i.EnvironmentOrganizationName,
			&i.EnvironmentOrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEnvironments = `-- name: GetUserEnvironments :many
SELECT e.id, e.name, e.url, e.favicon, e.status, e.shopware_version, e.last_scraped_at, e.last_scraped_error,
       e.organization_id, o.name AS organization_name, s.id AS shop_id, s.name AS shop_name
FROM environment e
JOIN member m ON m.organization_id = e.organization_id
JOIN organization o ON o.id = e.organization_id
LEFT JOIN shop s ON s.id = e.shop_id
WHERE m.user_id = $1
ORDER BY e.name
`

type GetUserEnvironmentsRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Url              string           `json:"url"`
	Favicon          *string          `json:"favicon"`
	Status           string           `json:"status"`
	ShopwareVersion  string           `json:"shopware_version"`
	LastScrapedAt    pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError *string          `json:"last_scraped_error"`
	OrganizationID   string           `json:"organization_id"`
	OrganizationName string           `json:"organization_name"`
	ShopID           *int32           `json:"shop_id"`
	ShopName         *string          `json:"shop_name"`
}

func (q *Queries) GetUserEnvironments(ctx context.Context, userID string) ([]GetUserEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, getUserEnvironments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserEnvironmentsRow{}
	for rows.Next() {
		var i GetUserEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Favicon,
			&i.Status,
			&i.ShopwareVersion,
			&i.LastScrapedAt,
			&i.LastScrapedError,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.ShopID,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEnvironmentsByOrg = `-- name: GetUserEnvironmentsByOrg :many
SELECT e.id, e.name, e.url, e.favicon, e.status, e.shopware_version, e.last_scraped_at, e.last_scraped_error,
       e.organization_id, o.name AS organization_name, s.id AS shop_id, s.name AS shop_name
FROM environment e
JOIN member m ON m.organization_id = e.organization_id
JOIN organization o ON o.id = e.organization_id
LEFT JOIN shop s ON s.id = e.shop_id
WHERE m.user_id = $1 AND e.organization_id = $2
ORDER BY e.name
`

type GetUserEnvironmentsByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

type GetUserEnvironmentsByOrgRow struct {
	ID               int32            `json:"id"`
	Name             string           `json:"name"`
	Url              string           `json:"url"`
	Favicon          *string          `json:"favicon"`
	Status           string           `json:"status"`
	ShopwareVersion  string           `json:"shopware_version"`
	LastScrapedAt    pgtype.Timestamp `json:"last_scraped_at"`
	LastScrapedError *string          `json:"last_scraped_error"`
	OrganizationID   string           `json:"organization_id"`
	OrganizationName string           `json:"organization_name"`
	ShopID           *int32           `json:"shop_id"`
	ShopName         *string          `json:"shop_name"`
}

func (q *Queries) GetUserEnvironmentsByOrg(ctx context.Context, arg GetUserEnvironmentsByOrgParams) ([]GetUserEnvironmentsByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUserEnvironmentsByOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserEnvironmentsByOrgRow{}
	for rows.Next() {
		var i GetUserEnvironmentsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Favicon,
			&i.Status,
			&i.ShopwareVersion,
			&i.LastScrapedAt,
			&i.LastScrapedError,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.ShopID,
			&i.ShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotifications = `-- name: GetUserNotifications :one
SELECT notifications FROM "user" WHERE id = $1
`

func (q *Queries) GetUserNotifications(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserNotifications, id)
	var notifications []byte
	err := row.Scan(&notifications)
	return notifications, err
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT o.id, o.name, o.slug, o.logo, o.created_at,
       (SELECT COUNT(*) FROM environment WHERE organization_id = o.id)::int AS environment_count,
       (SELECT COUNT(*) FROM member WHERE organization_id = o.id)::int AS member_count
FROM organization o
JOIN member m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.name
`

type GetUserOrganizationsRow struct {
	ID               string           `json:"id"`
	Name             string           `json:"name"`
	Slug             string           `json:"slug"`
	Logo             *string          `json:"logo"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	EnvironmentCount int32            `json:"environment_count"`
	MemberCount      int32            `json:"member_count"`
}

func (q *Queries) GetUserOrganizations(ctx context.Context, userID string) ([]GetUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserOrganizationsRow{}
	for rows.Next() {
		var i GetUserOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Logo,
			&i.CreatedAt,
			&i.EnvironmentCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserShops = `-- name: GetUserShops :many
SELECT s.id, s.name, s.description, s.git_url, s.organization_id, o.name AS organization_name
FROM shop s
JOIN member m ON m.organization_id = s.organization_id
JOIN organization o ON o.id = s.organization_id
WHERE m.user_id = $1
ORDER BY s.name
`

type GetUserShopsRow struct {
	ID               int32   `json:"id"`
	Name             string  `json:"name"`
	Description      *string `json:"description"`
	GitUrl           *string `json:"git_url"`
	OrganizationID   string  `json:"organization_id"`
	OrganizationName string  `json:"organization_name"`
}

func (q *Queries) GetUserShops(ctx context.Context, userID string) ([]GetUserShopsRow, error) {
	rows, err := q.db.Query(ctx, getUserShops, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserShopsRow{}
	for rows.Next() {
		var i GetUserShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GitUrl,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserShopsByOrg = `-- name: GetUserShopsByOrg :many
SELECT s.id, s.name, s.description, s.git_url, s.default_environment_id, s.organization_id, o.name AS organization_name
FROM shop s
JOIN member m ON m.organization_id = s.organization_id
JOIN organization o ON o.id = s.organization_id
WHERE m.user_id = $1 AND s.organization_id = $2
ORDER BY s.name
`

type GetUserShopsByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

type GetUserShopsByOrgRow struct {
	ID                   int32   `json:"id"`
	Name                 string  `json:"name"`
	Description          *string `json:"description"`
	GitUrl               *string `json:"git_url"`
	DefaultEnvironmentID *int32  `json:"default_environment_id"`
	OrganizationID       string  `json:"organization_id"`
	OrganizationName     string  `json:"organization_name"`
}

func (q *Queries) GetUserShopsByOrg(ctx context.Context, arg GetUserShopsByOrgParams) ([]GetUserShopsByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUserShopsByOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserShopsByOrgRow{}
	for rows.Next() {
		var i GetUserShopsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.GitUrl,
			&i.DefaultEnvironmentID,
			&i.OrganizationID,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStoreExtensionByOrgAndName = `-- name: GetUserStoreExtensionByOrgAndName :many
SELECT ese.extension_name AS name, ese.label, ese.version, ese.latest_version, ese.active, ese.installed,
       se.store_link, se.rating_average, ese.installed_at,
       se.icon_url, se.producer_name, se.producer_website, se.release_date,
       COALESCE(t.short_description, ten.short_description) AS short_description,
       COALESCE(t.description, ten.description) AS description,
       COALESCE(t.installation_manual, ten.installation_manual) AS installation_manual,
       ese.environment_id, e.name AS environment_name, e.url AS environment_url,
       o.name AS environment_organization_name, e.organization_id AS environment_organization_id,
       e.shop_id AS environment_shop_id, sh.name AS environment_shop_name
FROM environment_store_extension ese
JOIN store_extension se ON se.name = ese.extension_name
LEFT JOIN store_extension_translation t ON t.extension_name = ese.extension_name AND t.language = $3
LEFT JOIN store_extension_translation ten ON ten.extension_name = ese.extension_name AND ten.language = 'en'
JOIN environment e ON e.id = ese.environment_id
JOIN shop sh ON sh.id = e.shop_id
JOIN organization o ON o.id = e.organization_id
JOIN member m ON m.organization_id = e.organization_id
WHERE m.user_id = $1 AND e.organization_id = $2 AND ese.extension_name = $4
ORDER BY e.name
`

type GetUserStoreExtensionByOrgAndNameParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	Language       string `json:"language"`
	ExtensionName  string `json:"extension_name"`
}

type GetUserStoreExtensionByOrgAndNameRow struct {
	Name                        string  `json:"name"`
	Label                       string  `json:"label"`
	Version                     string  `json:"version"`
	LatestVersion               *string `json:"latest_version"`
	Active                      bool    `json:"active"`
	Installed                   bool    `json:"installed"`
	StoreLink                   *string `json:"store_link"`
	RatingAverage               *int32  `json:"rating_average"`
	InstalledAt                 *string `json:"installed_at"`
	IconUrl                     *string `json:"icon_url"`
	ProducerName                *string `json:"producer_name"`
	ProducerWebsite             *string `json:"producer_website"`
	ReleaseDate                 *string `json:"release_date"`
	ShortDescription            *string `json:"short_description"`
	Description                 *string `json:"description"`
	InstallationManual          *string `json:"installation_manual"`
	EnvironmentID               int32   `json:"environment_id"`
	EnvironmentName             string  `json:"environment_name"`
	EnvironmentUrl              string  `json:"environment_url"`
	EnvironmentOrganizationName string  `json:"environment_organization_name"`
	EnvironmentOrganizationID   string  `json:"environment_organization_id"`
	EnvironmentShopID           int32   `json:"environment_shop_id"`
	EnvironmentShopName         string  `json:"environment_shop_name"`
}

// Single store extension by technical name ($4), scoped to the user's org.
func (q *Queries) GetUserStoreExtensionByOrgAndName(ctx context.Context, arg GetUserStoreExtensionByOrgAndNameParams) ([]GetUserStoreExtensionByOrgAndNameRow, error) {
	rows, err := q.db.Query(ctx, getUserStoreExtensionByOrgAndName,
		arg.UserID,
		arg.OrganizationID,
		arg.Language,
		arg.ExtensionName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStoreExtensionByOrgAndNameRow{}
	for rows.Next() {
		var i GetUserStoreExtensionByOrgAndNameRow
		if err := rows.Scan(
			&i.Name,
			&i.Label,
			&i.Version,
			&i.LatestVersion,
			&i.Active,
			&i.Installed,
			&i.StoreLink,
			&i.RatingAverage,
			&i.InstalledAt,
			&i.IconUrl,
			&i.ProducerName,
			&i.ProducerWebsite,
			&i.ReleaseDate,
			&i.ShortDescription,
			&i.Description,
			&i.InstallationManual,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentUrl,
			&i.EnvironmentOrganizationName,
			&i.EnvironmentOrganizationID,
			&i.EnvironmentShopID,
			&i.EnvironmentShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStoreExtensionChangelogsByOrg = `-- name: GetUserStoreExtensionChangelogsByOrg :many
SELECT DISTINCT sev.extension_name, sev.version,
       COALESCE(t.changelog, ten.changelog) AS changelog, sev.released_at
FROM store_extension_version sev
LEFT JOIN store_extension_version_translation t ON t.extension_version_id = sev.id AND t.language = $3
LEFT JOIN store_extension_version_translation ten ON ten.extension_version_id = sev.id AND ten.language = 'en'
WHERE sev.extension_name IN (
  SELECT ese.extension_name
  FROM environment_store_extension ese
  JOIN environment e ON e.id = ese.environment_id
  JOIN member m ON m.organization_id = e.organization_id
  WHERE m.user_id = $1 AND e.organization_id = $2
)
ORDER BY sev.extension_name, sev.version
`

type GetUserStoreExtensionChangelogsByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	Language       string `json:"language"`
}

type GetUserStoreExtensionChangelogsByOrgRow struct {
	ExtensionName string  `json:"extension_name"`
	Version       string  `json:"version"`
	Changelog     *string `json:"changelog"`
	ReleasedAt    *string `json:"released_at"`
}

// Changelog text resolves to the requested language ($3), falling back to en.
func (q *Queries) GetUserStoreExtensionChangelogsByOrg(ctx context.Context, arg GetUserStoreExtensionChangelogsByOrgParams) ([]GetUserStoreExtensionChangelogsByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUserStoreExtensionChangelogsByOrg, arg.UserID, arg.OrganizationID, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStoreExtensionChangelogsByOrgRow{}
	for rows.Next() {
		var i GetUserStoreExtensionChangelogsByOrgRow
		if err := rows.Scan(
			&i.ExtensionName,
			&i.Version,
			&i.Changelog,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStoreExtensionChangelogsByOrgAndName = `-- name: GetUserStoreExtensionChangelogsByOrgAndName :many
SELECT DISTINCT sev.extension_name, sev.version,
       COALESCE(t.changelog, ten.changelog) AS changelog, sev.released_at
FROM store_extension_version sev
LEFT JOIN store_extension_version_translation t ON t.extension_version_id = sev.id AND t.language = $3
LEFT JOIN store_extension_version_translation ten ON ten.extension_version_id = sev.id AND ten.language = 'en'
WHERE sev.extension_name = $4
  AND EXISTS (
    SELECT 1
    FROM environment_store_extension ese
    JOIN environment e ON e.id = ese.environment_id
    JOIN member m ON m.organization_id = e.organization_id
    WHERE m.user_id = $1 AND e.organization_id = $2 AND ese.extension_name = $4
  )
ORDER BY sev.version
`

type GetUserStoreExtensionChangelogsByOrgAndNameParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	Language       string `json:"language"`
	ExtensionName  string `json:"extension_name"`
}

type GetUserStoreExtensionChangelogsByOrgAndNameRow struct {
	ExtensionName string  `json:"extension_name"`
	Version       string  `json:"version"`
	Changelog     *string `json:"changelog"`
	ReleasedAt    *string `json:"released_at"`
}

// Changelog text resolves to the requested language ($3), falling back to en.
func (q *Queries) GetUserStoreExtensionChangelogsByOrgAndName(ctx context.Context, arg GetUserStoreExtensionChangelogsByOrgAndNameParams) ([]GetUserStoreExtensionChangelogsByOrgAndNameRow, error) {
	rows, err := q.db.Query(ctx, getUserStoreExtensionChangelogsByOrgAndName,
		arg.UserID,
		arg.OrganizationID,
		arg.Language,
		arg.ExtensionName,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStoreExtensionChangelogsByOrgAndNameRow{}
	for rows.Next() {
		var i GetUserStoreExtensionChangelogsByOrgAndNameRow
		if err := rows.Scan(
			&i.ExtensionName,
			&i.Version,
			&i.Changelog,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStoreExtensionImagesByOrg = `-- name: GetUserStoreExtensionImagesByOrg :many
SELECT sei.extension_name, sei.url, sei.preview
FROM store_extension_image sei
WHERE sei.extension_name IN (
  SELECT ese.extension_name
  FROM environment_store_extension ese
  JOIN environment e ON e.id = ese.environment_id
  JOIN member m ON m.organization_id = e.organization_id
  WHERE m.user_id = $1 AND e.organization_id = $2
)
ORDER BY sei.extension_name, sei.preview DESC, sei.priority, sei.id
`

type GetUserStoreExtensionImagesByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

type GetUserStoreExtensionImagesByOrgRow struct {
	ExtensionName string `json:"extension_name"`
	Url           string `json:"url"`
	Preview       bool   `json:"preview"`
}

func (q *Queries) GetUserStoreExtensionImagesByOrg(ctx context.Context, arg GetUserStoreExtensionImagesByOrgParams) ([]GetUserStoreExtensionImagesByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUserStoreExtensionImagesByOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStoreExtensionImagesByOrgRow{}
	for rows.Next() {
		var i GetUserStoreExtensionImagesByOrgRow
		if err := rows.Scan(&i.ExtensionName, &i.Url, &i.Preview); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStoreExtensionImagesByOrgAndName = `-- name: GetUserStoreExtensionImagesByOrgAndName :many
SELECT sei.extension_name, sei.url, sei.preview
FROM store_extension_image sei
WHERE sei.extension_name = $3
  AND EXISTS (
    SELECT 1
    FROM environment_store_extension ese
    JOIN environment e ON e.id = ese.environment_id
    JOIN member m ON m.organization_id = e.organization_id
    WHERE m.user_id = $1 AND e.organization_id = $2 AND ese.extension_name = $3
  )
ORDER BY sei.preview DESC, sei.priority, sei.id
`

type GetUserStoreExtensionImagesByOrgAndNameParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	ExtensionName  string `json:"extension_name"`
}

type GetUserStoreExtensionImagesByOrgAndNameRow struct {
	ExtensionName string `json:"extension_name"`
	Url           string `json:"url"`
	Preview       bool   `json:"preview"`
}

func (q *Queries) GetUserStoreExtensionImagesByOrgAndName(ctx context.Context, arg GetUserStoreExtensionImagesByOrgAndNameParams) ([]GetUserStoreExtensionImagesByOrgAndNameRow, error) {
	rows, err := q.db.Query(ctx, getUserStoreExtensionImagesByOrgAndName, arg.UserID, arg.OrganizationID, arg.ExtensionName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStoreExtensionImagesByOrgAndNameRow{}
	for rows.Next() {
		var i GetUserStoreExtensionImagesByOrgAndNameRow
		if err := rows.Scan(&i.ExtensionName, &i.Url, &i.Preview); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStoreExtensionsByOrg = `-- name: GetUserStoreExtensionsByOrg :many
SELECT ese.extension_name AS name, ese.label, ese.version, ese.latest_version, ese.active, ese.installed,
       se.store_link, se.rating_average, ese.installed_at,
       se.icon_url, se.producer_name, se.producer_website, se.release_date,
       COALESCE(t.short_description, ten.short_description) AS short_description,
       COALESCE(t.description, ten.description) AS description,
       COALESCE(t.installation_manual, ten.installation_manual) AS installation_manual,
       ese.environment_id, e.name AS environment_name, e.url AS environment_url,
       o.name AS environment_organization_name, e.organization_id AS environment_organization_id,
       e.shop_id AS environment_shop_id, sh.name AS environment_shop_name
FROM environment_store_extension ese
JOIN store_extension se ON se.name = ese.extension_name
LEFT JOIN store_extension_translation t ON t.extension_name = ese.extension_name AND t.language = $3
LEFT JOIN store_extension_translation ten ON ten.extension_name = ese.extension_name AND ten.language = 'en'
JOIN environment e ON e.id = ese.environment_id
JOIN shop sh ON sh.id = e.shop_id
JOIN organization o ON o.id = e.organization_id
JOIN member m ON m.organization_id = e.organization_id
WHERE m.user_id = $1 AND e.organization_id = $2
ORDER BY ese.extension_name, e.name
`

type GetUserStoreExtensionsByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	Language       string `json:"language"`
}

type GetUserStoreExtensionsByOrgRow struct {
	Name                        string  `json:"name"`
	Label                       string  `json:"label"`
	Version                     string  `json:"version"`
	LatestVersion               *string `json:"latest_version"`
	Active                      bool    `json:"active"`
	Installed                   bool    `json:"installed"`
	StoreLink                   *string `json:"store_link"`
	RatingAverage               *int32  `json:"rating_average"`
	InstalledAt                 *string `json:"installed_at"`
	IconUrl                     *string `json:"icon_url"`
	ProducerName                *string `json:"producer_name"`
	ProducerWebsite             *string `json:"producer_website"`
	ReleaseDate                 *string `json:"release_date"`
	ShortDescription            *string `json:"short_description"`
	Description                 *string `json:"description"`
	InstallationManual          *string `json:"installation_manual"`
	EnvironmentID               int32   `json:"environment_id"`
	EnvironmentName             string  `json:"environment_name"`
	EnvironmentUrl              string  `json:"environment_url"`
	EnvironmentOrganizationName string  `json:"environment_organization_name"`
	EnvironmentOrganizationID   string  `json:"environment_organization_id"`
	EnvironmentShopID           int32   `json:"environment_shop_id"`
	EnvironmentShopName         string  `json:"environment_shop_name"`
}

// Localized fields resolve to the requested language ($3), falling back to the
// English translation when that language is missing.
func (q *Queries) GetUserStoreExtensionsByOrg(ctx context.Context, arg GetUserStoreExtensionsByOrgParams) ([]GetUserStoreExtensionsByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUserStoreExtensionsByOrg, arg.UserID, arg.OrganizationID, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserStoreExtensionsByOrgRow{}
	for rows.Next() {
		var i GetUserStoreExtensionsByOrgRow
		if err := rows.Scan(
			&i.Name,
			&i.Label,
			&i.Version,
			&i.LatestVersion,
			&i.Active,
			&i.Installed,
			&i.StoreLink,
			&i.RatingAverage,
			&i.InstalledAt,
			&i.IconUrl,
			&i.ProducerName,
			&i.ProducerWebsite,
			&i.ReleaseDate,
			&i.ShortDescription,
			&i.Description,
			&i.InstallationManual,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentUrl,
			&i.EnvironmentOrganizationName,
			&i.EnvironmentOrganizationID,
			&i.EnvironmentShopID,
			&i.EnvironmentShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnknownExtensionByOrgAndName = `-- name: GetUserUnknownExtensionByOrgAndName :many
SELECT ee.name, ee.label, ee.version, ee.latest_version, ee.active, ee.installed,
       NULL::text AS store_link, NULL::integer AS rating_average, ee.installed_at,
       ee.environment_id, e.name AS environment_name, e.url AS environment_url,
       o.name AS environment_organization_name, e.organization_id AS environment_organization_id,
       e.shop_id AS environment_shop_id, sh.name AS environment_shop_name
FROM environment_extension ee
JOIN environment e ON e.id = ee.environment_id
JOIN shop sh ON sh.id = e.shop_id
JOIN organization o ON o.id = e.organization_id
JOIN member m ON m.organization_id = e.organization_id
WHERE m.user_id = $1 AND e.organization_id = $2 AND ee.name = $3
ORDER BY e.name
`

type GetUserUnknownExtensionByOrgAndNameParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
	Name           string `json:"name"`
}

type GetUserUnknownExtensionByOrgAndNameRow struct {
	Name                        string  `json:"name"`
	Label                       string  `json:"label"`
	Version                     string  `json:"version"`
	LatestVersion               *string `json:"latest_version"`
	Active                      bool    `json:"active"`
	Installed                   bool    `json:"installed"`
	StoreLink                   *string `json:"store_link"`
	RatingAverage               *int32  `json:"rating_average"`
	InstalledAt                 *string `json:"installed_at"`
	EnvironmentID               int32   `json:"environment_id"`
	EnvironmentName             string  `json:"environment_name"`
	EnvironmentUrl              string  `json:"environment_url"`
	EnvironmentOrganizationName string  `json:"environment_organization_name"`
	EnvironmentOrganizationID   string  `json:"environment_organization_id"`
	EnvironmentShopID           int32   `json:"environment_shop_id"`
	EnvironmentShopName         string  `json:"environment_shop_name"`
}

func (q *Queries) GetUserUnknownExtensionByOrgAndName(ctx context.Context, arg GetUserUnknownExtensionByOrgAndNameParams) ([]GetUserUnknownExtensionByOrgAndNameRow, error) {
	rows, err := q.db.Query(ctx, getUserUnknownExtensionByOrgAndName, arg.UserID, arg.OrganizationID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserUnknownExtensionByOrgAndNameRow{}
	for rows.Next() {
		var i GetUserUnknownExtensionByOrgAndNameRow
		if err := rows.Scan(
			&i.Name,
			&i.Label,
			&i.Version,
			&i.LatestVersion,
			&i.Active,
			&i.Installed,
			&i.StoreLink,
			&i.RatingAverage,
			&i.InstalledAt,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentUrl,
			&i.EnvironmentOrganizationName,
			&i.EnvironmentOrganizationID,
			&i.EnvironmentShopID,
			&i.EnvironmentShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnknownExtensionsByOrg = `-- name: GetUserUnknownExtensionsByOrg :many
SELECT ee.name, ee.label, ee.version, ee.latest_version, ee.active, ee.installed,
       NULL::text AS store_link, NULL::integer AS rating_average, ee.installed_at,
       ee.environment_id, e.name AS environment_name, e.url AS environment_url,
       o.name AS environment_organization_name, e.organization_id AS environment_organization_id,
       e.shop_id AS environment_shop_id, sh.name AS environment_shop_name
FROM environment_extension ee
JOIN environment e ON e.id = ee.environment_id
JOIN shop sh ON sh.id = e.shop_id
JOIN organization o ON o.id = e.organization_id
JOIN member m ON m.organization_id = e.organization_id
WHERE m.user_id = $1 AND e.organization_id = $2
ORDER BY ee.name, e.name
`

type GetUserUnknownExtensionsByOrgParams struct {
	UserID         string `json:"user_id"`
	OrganizationID string `json:"organization_id"`
}

type GetUserUnknownExtensionsByOrgRow struct {
	Name                        string  `json:"name"`
	Label                       string  `json:"label"`
	Version                     string  `json:"version"`
	LatestVersion               *string `json:"latest_version"`
	Active                      bool    `json:"active"`
	Installed                   bool    `json:"installed"`
	StoreLink                   *string `json:"store_link"`
	RatingAverage               *int32  `json:"rating_average"`
	InstalledAt                 *string `json:"installed_at"`
	EnvironmentID               int32   `json:"environment_id"`
	EnvironmentName             string  `json:"environment_name"`
	EnvironmentUrl              string  `json:"environment_url"`
	EnvironmentOrganizationName string  `json:"environment_organization_name"`
	EnvironmentOrganizationID   string  `json:"environment_organization_id"`
	EnvironmentShopID           int32   `json:"environment_shop_id"`
	EnvironmentShopName         string  `json:"environment_shop_name"`
}

func (q *Queries) GetUserUnknownExtensionsByOrg(ctx context.Context, arg GetUserUnknownExtensionsByOrgParams) ([]GetUserUnknownExtensionsByOrgRow, error) {
	rows, err := q.db.Query(ctx, getUserUnknownExtensionsByOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserUnknownExtensionsByOrgRow{}
	for rows.Next() {
		var i GetUserUnknownExtensionsByOrgRow
		if err := rows.Scan(
			&i.Name,
			&i.Label,
			&i.Version,
			&i.LatestVersion,
			&i.Active,
			&i.Installed,
			&i.StoreLink,
			&i.RatingAverage,
			&i.InstalledAt,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.EnvironmentUrl,
			&i.EnvironmentOrganizationName,
			&i.EnvironmentOrganizationID,
			&i.EnvironmentShopID,
			&i.EnvironmentShopName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isOrganizationMember = `-- name: IsOrganizationMember :one
SELECT COUNT(*) > 0 AS is_member FROM member WHERE organization_id = $1 AND user_id = $2
`

type IsOrganizationMemberParams struct {
	OrganizationID string `json:"organization_id"`
	UserID         string `json:"user_id"`
}

func (q *Queries) IsOrganizationMember(ctx context.Context, arg IsOrganizationMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOrganizationMember, arg.OrganizationID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const updateUserLocale = `-- name: UpdateUserLocale :exec
UPDATE "user" SET locale = $1, updated_at = NOW() WHERE id = $2
`

type UpdateUserLocaleParams struct {
	Locale string `json:"locale"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) error {
	_, err := q.db.Exec(ctx, updateUserLocale, arg.Locale, arg.ID)
	return err
}

const updateUserNotifications = `-- name: UpdateUserNotifications :exec
UPDATE "user" SET notifications = $1 WHERE id = $2
`

type UpdateUserNotificationsParams struct {
	Notifications []byte `json:"notifications"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateUserNotifications(ctx context.Context, arg UpdateUserNotificationsParams) error {
	_, err := q.db.Exec(ctx, updateUserNotifications, arg.Notifications, arg.ID)
	return err
}
