// Package authapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package authapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AdminSetUserRoleJSONBodyRole.
const (
	Admin AdminSetUserRoleJSONBodyRole = "admin"
	User  AdminSetUserRoleJSONBodyRole = "user"
)

// Valid indicates whether the value is a known member of the AdminSetUserRoleJSONBodyRole enum.
func (e AdminSetUserRoleJSONBodyRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for SignInSocialJSONBodyProvider.
const (
	Github SignInSocialJSONBodyProvider = "github"
)

// Valid indicates whether the value is a known member of the SignInSocialJSONBodyProvider enum.
func (e SignInSocialJSONBodyProvider) Valid() bool {
	switch e {
	case Github:
		return true
	default:
		return false
	}
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email         *openapi_types.Email `json:"email,omitempty"`
	EmailVerified *bool                `json:"emailVerified,omitempty"`
	Id            *string              `json:"id,omitempty"`
	Image         *string              `json:"image,omitempty"`
	Name          *string              `json:"name,omitempty"`
	Notifications *[]string            `json:"notifications,omitempty"`
	Role          *string              `json:"role,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	ActiveOrganizationId *string    `json:"activeOrganizationId,omitempty"`
	ExpiresAt            *time.Time `json:"expiresAt,omitempty"`
	Id                   *string    `json:"id,omitempty"`
	UserId               *string    `json:"userId,omitempty"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// AdminBanUserJSONBody defines parameters for AdminBanUser.
type AdminBanUserJSONBody struct {
	BanReason *string `json:"banReason,omitempty"`
}

// AdminSetUserRoleJSONBody defines parameters for AdminSetUserRole.
type AdminSetUserRoleJSONBody struct {
	Role AdminSetUserRoleJSONBodyRole `json:"role"`
}

// AdminSetUserRoleJSONBodyRole defines parameters for AdminSetUserRole.
type AdminSetUserRoleJSONBodyRole string

// CancelInvitationJSONBody defines parameters for CancelInvitation.
type CancelInvitationJSONBody struct {
	InvitationId string `json:"invitationId"`
}

// ChangeEmailJSONBody defines parameters for ChangeEmail.
type ChangeEmailJSONBody struct {
	CurrentPassword string              `json:"currentPassword"`
	NewEmail        openapi_types.Email `json:"newEmail"`
}

// ChangePasswordJSONBody defines parameters for ChangePassword.
type ChangePasswordJSONBody struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// ExchangeCodeJSONBody defines parameters for ExchangeCode.
type ExchangeCodeJSONBody struct {
	Code string `json:"code"`
}

// ForgetPasswordJSONBody defines parameters for ForgetPassword.
type ForgetPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// GetFullOrganizationParams defines parameters for GetFullOrganization.
type GetFullOrganizationParams struct {
	OrganizationId string `form:"organizationId" json:"organizationId"`
}

// HasPermissionJSONBody defines parameters for HasPermission.
type HasPermissionJSONBody struct {
	OrganizationId string `json:"organizationId"`
}

// LinkSocialJSONBody defines parameters for LinkSocial.
type LinkSocialJSONBody struct {
	CallbackURL *string `json:"callbackURL,omitempty"`
	Provider    string  `json:"provider"`
}

// CreateOrganizationJSONBody defines parameters for CreateOrganization.
type CreateOrganizationJSONBody struct {
	Name string `json:"name"`
}

// UpdateOrganizationJSONBody defines parameters for UpdateOrganization.
type UpdateOrganizationJSONBody struct {
	Logo *string `json:"logo,omitempty"`
	Name *string `json:"name,omitempty"`
}

// InviteMemberJSONBody defines parameters for InviteMember.
type InviteMemberJSONBody struct {
	Email openapi_types.Email `json:"email"`
	Role  *string             `json:"role,omitempty"`
}

// SetMemberRoleJSONBody defines parameters for SetMemberRole.
type SetMemberRoleJSONBody struct {
	Role string `json:"role"`
}

// DeletePasskeyJSONBody defines parameters for DeletePasskey.
type DeletePasskeyJSONBody struct {
	Id string `json:"id"`
}

// PasskeyLoginJSONBody defines parameters for PasskeyLogin.
type PasskeyLoginJSONBody struct {
	ChallengeKey string `json:"challengeKey"`
}

// PasskeyRegisterJSONBody defines parameters for PasskeyRegister.
type PasskeyRegisterJSONBody struct {
	ChallengeKey string  `json:"challengeKey"`
	Name         *string `json:"name,omitempty"`
}

// ResetPasswordJSONBody defines parameters for ResetPassword.
type ResetPasswordJSONBody struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// RevokeSessionJSONBody defines parameters for RevokeSession.
type RevokeSessionJSONBody struct {
	SessionId string `json:"sessionId"`
}

// SignInEmailJSONBody defines parameters for SignInEmail.
type SignInEmailJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignInSocialJSONBody defines parameters for SignInSocial.
type SignInSocialJSONBody struct {
	CallbackURL *string                      `json:"callbackURL,omitempty"`
	Provider    SignInSocialJSONBodyProvider `json:"provider"`
}

// SignInSocialJSONBodyProvider defines parameters for SignInSocial.
type SignInSocialJSONBodyProvider string

// SignInSSOJSONBody defines parameters for SignInSSO.
type SignInSSOJSONBody struct {
	CallbackURL *string             `json:"callbackURL,omitempty"`
	Email       openapi_types.Email `json:"email"`
}

// SignUpEmailJSONBody defines parameters for SignUpEmail.
type SignUpEmailJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// RegisterSSOProviderJSONBody defines parameters for RegisterSSOProvider.
type RegisterSSOProviderJSONBody struct {
	AuthorizationEndpoint string `json:"authorizationEndpoint"`
	ClientId              string `json:"clientId"`
	ClientSecret          string `json:"clientSecret"`
	Domain                string `json:"domain"`
	Issuer                string `json:"issuer"`
	JwksEndpoint          string `json:"jwksEndpoint"`
	OrganizationId        string `json:"organizationId"`
	TokenEndpoint         string `json:"tokenEndpoint"`
}

// UnlinkAccountJSONBody defines parameters for UnlinkAccount.
type UnlinkAccountJSONBody struct {
	ProviderId string `json:"providerId"`
}

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// VerifyEmailParams defines parameters for VerifyEmail.
type VerifyEmailParams struct {
	Token string `form:"token" json:"token"`
}

// AdminBanUserJSONRequestBody defines body for AdminBanUser for application/json ContentType.
type AdminBanUserJSONRequestBody AdminBanUserJSONBody

// AdminSetUserRoleJSONRequestBody defines body for AdminSetUserRole for application/json ContentType.
type AdminSetUserRoleJSONRequestBody AdminSetUserRoleJSONBody

// CancelInvitationJSONRequestBody defines body for CancelInvitation for application/json ContentType.
type CancelInvitationJSONRequestBody CancelInvitationJSONBody

// ChangeEmailJSONRequestBody defines body for ChangeEmail for application/json ContentType.
type ChangeEmailJSONRequestBody ChangeEmailJSONBody

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody ChangePasswordJSONBody

// ExchangeCodeJSONRequestBody defines body for ExchangeCode for application/json ContentType.
type ExchangeCodeJSONRequestBody ExchangeCodeJSONBody

// ForgetPasswordJSONRequestBody defines body for ForgetPassword for application/json ContentType.
type ForgetPasswordJSONRequestBody ForgetPasswordJSONBody

// HasPermissionJSONRequestBody defines body for HasPermission for application/json ContentType.
type HasPermissionJSONRequestBody HasPermissionJSONBody

// LinkSocialJSONRequestBody defines body for LinkSocial for application/json ContentType.
type LinkSocialJSONRequestBody LinkSocialJSONBody

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody CreateOrganizationJSONBody

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody UpdateOrganizationJSONBody

// InviteMemberJSONRequestBody defines body for InviteMember for application/json ContentType.
type InviteMemberJSONRequestBody InviteMemberJSONBody

// SetMemberRoleJSONRequestBody defines body for SetMemberRole for application/json ContentType.
type SetMemberRoleJSONRequestBody SetMemberRoleJSONBody

// DeletePasskeyJSONRequestBody defines body for DeletePasskey for application/json ContentType.
type DeletePasskeyJSONRequestBody DeletePasskeyJSONBody

// PasskeyLoginJSONRequestBody defines body for PasskeyLogin for application/json ContentType.
type PasskeyLoginJSONRequestBody PasskeyLoginJSONBody

// PasskeyRegisterJSONRequestBody defines body for PasskeyRegister for application/json ContentType.
type PasskeyRegisterJSONRequestBody PasskeyRegisterJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody ResetPasswordJSONBody

// RevokeSessionJSONRequestBody defines body for RevokeSession for application/json ContentType.
type RevokeSessionJSONRequestBody RevokeSessionJSONBody

// SignInEmailJSONRequestBody defines body for SignInEmail for application/json ContentType.
type SignInEmailJSONRequestBody SignInEmailJSONBody

// SignInSocialJSONRequestBody defines body for SignInSocial for application/json ContentType.
type SignInSocialJSONRequestBody SignInSocialJSONBody

// SignInSSOJSONRequestBody defines body for SignInSSO for application/json ContentType.
type SignInSSOJSONRequestBody SignInSSOJSONBody

// SignUpEmailJSONRequestBody defines body for SignUpEmail for application/json ContentType.
type SignUpEmailJSONRequestBody SignUpEmailJSONBody

// RegisterSSOProviderJSONRequestBody defines body for RegisterSSOProvider for application/json ContentType.
type RegisterSSOProviderJSONRequestBody RegisterSSOProviderJSONBody

// UnlinkAccountJSONRequestBody defines body for UnlinkAccount for application/json ContentType.
type UnlinkAccountJSONRequestBody UnlinkAccountJSONBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Stop impersonating a user
	// (POST /auth/admin/stop-impersonating)
	AdminStopImpersonating(w http.ResponseWriter, r *http.Request)
	// List all users (admin only)
	// (GET /auth/admin/users)
	AdminListUsers(w http.ResponseWriter, r *http.Request)
	// Ban a user
	// (POST /auth/admin/users/{userId}/ban)
	AdminBanUser(w http.ResponseWriter, r *http.Request, userId string)
	// Impersonate a user
	// (POST /auth/admin/users/{userId}/impersonate)
	AdminImpersonate(w http.ResponseWriter, r *http.Request, userId string)
	// Set a user's role
	// (PATCH /auth/admin/users/{userId}/role)
	AdminSetUserRole(w http.ResponseWriter, r *http.Request, userId string)
	// Unban a user
	// (POST /auth/admin/users/{userId}/unban)
	AdminUnbanUser(w http.ResponseWriter, r *http.Request, userId string)
	// Cancel a pending invitation
	// (POST /auth/cancel-invitation)
	CancelInvitation(w http.ResponseWriter, r *http.Request)
	// Change email address
	// (POST /auth/change-email)
	ChangeEmail(w http.ResponseWriter, r *http.Request)
	// Change password
	// (POST /auth/change-password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
	// Delete user account
	// (POST /auth/delete-user)
	DeleteUser(w http.ResponseWriter, r *http.Request)
	// Exchange one-time authorization code for session token
	// (POST /auth/exchange-code)
	ExchangeCode(w http.ResponseWriter, r *http.Request)
	// Request password reset email
	// (POST /auth/forget-password)
	ForgetPassword(w http.ResponseWriter, r *http.Request)
	// Get full organization details by ID
	// (GET /auth/get-full-organization)
	GetFullOrganization(w http.ResponseWriter, r *http.Request, params GetFullOrganizationParams)
	// Check organization permission
	// (POST /auth/has-permission)
	HasPermission(w http.ResponseWriter, r *http.Request)
	// Accept an invitation
	// (POST /auth/invitations/{invitationId}/accept)
	AcceptInvitation(w http.ResponseWriter, r *http.Request, invitationId string)
	// Reject an invitation
	// (POST /auth/invitations/{invitationId}/reject)
	RejectInvitation(w http.ResponseWriter, r *http.Request, invitationId string)
	// Link a social provider
	// (POST /auth/link-social)
	LinkSocial(w http.ResponseWriter, r *http.Request)
	// List linked auth providers
	// (GET /auth/list-accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request)
	// List user's organizations
	// (GET /auth/list-organizations)
	ListUserOrganizations(w http.ResponseWriter, r *http.Request)
	// List active sessions
	// (GET /auth/list-sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create an organization
	// (POST /auth/organizations)
	CreateOrganization(w http.ResponseWriter, r *http.Request)
	// Delete an organization
	// (DELETE /auth/organizations/{organizationId})
	DeleteOrganization(w http.ResponseWriter, r *http.Request, organizationId string)
	// Update an organization
	// (PATCH /auth/organizations/{organizationId})
	UpdateOrganization(w http.ResponseWriter, r *http.Request, organizationId string)
	// List pending invitations
	// (GET /auth/organizations/{organizationId}/invitations)
	ListOrganizationInvitations(w http.ResponseWriter, r *http.Request, organizationId string)
	// Invite a user to the organization
	// (POST /auth/organizations/{organizationId}/invitations)
	InviteMember(w http.ResponseWriter, r *http.Request, organizationId string)
	// Leave an organization
	// (POST /auth/organizations/{organizationId}/leave)
	LeaveOrganization(w http.ResponseWriter, r *http.Request, organizationId string)
	// List organization members
	// (GET /auth/organizations/{organizationId}/members)
	ListOrganizationMembers(w http.ResponseWriter, r *http.Request, organizationId string)
	// Remove a member from the organization
	// (DELETE /auth/organizations/{organizationId}/members/{userId})
	RemoveMember(w http.ResponseWriter, r *http.Request, organizationId string, userId string)
	// Change a member's role
	// (PATCH /auth/organizations/{organizationId}/members/{userId})
	SetMemberRole(w http.ResponseWriter, r *http.Request, organizationId string, userId string)
	// Delete a passkey
	// (POST /auth/passkey/delete-passkey)
	DeletePasskey(w http.ResponseWriter, r *http.Request)
	// List user's passkeys
	// (GET /auth/passkey/list-user-passkeys)
	ListUserPasskeys(w http.ResponseWriter, r *http.Request)
	// Complete passkey login
	// (POST /auth/passkey/login)
	PasskeyLogin(w http.ResponseWriter, r *http.Request)
	// Begin passkey login
	// (POST /auth/passkey/login-options)
	PasskeyLoginOptions(w http.ResponseWriter, r *http.Request)
	// Complete passkey registration
	// (POST /auth/passkey/register)
	PasskeyRegister(w http.ResponseWriter, r *http.Request)
	// Begin passkey registration
	// (POST /auth/passkey/register-options)
	PasskeyRegisterOptions(w http.ResponseWriter, r *http.Request)
	// Reset password with token
	// (POST /auth/reset-password)
	ResetPassword(w http.ResponseWriter, r *http.Request)
	// Revoke a session
	// (POST /auth/revoke-session)
	RevokeSession(w http.ResponseWriter, r *http.Request)
	// Get current session
	// (GET /auth/session)
	GetSession(w http.ResponseWriter, r *http.Request)
	// Sign in with email and password
	// (POST /auth/sign-in/email)
	SignInEmail(w http.ResponseWriter, r *http.Request)
	// Initiate OAuth sign-in (GitHub)
	// (POST /auth/sign-in/social)
	SignInSocial(w http.ResponseWriter, r *http.Request)
	// Initiate SSO sign-in
	// (POST /auth/sign-in/sso)
	SignInSSO(w http.ResponseWriter, r *http.Request)
	// Sign out
	// (POST /auth/sign-out)
	SignOut(w http.ResponseWriter, r *http.Request)
	// Register with email and password
	// (POST /auth/sign-up/email)
	SignUpEmail(w http.ResponseWriter, r *http.Request)
	// Register an SSO provider
	// (POST /auth/sso/register)
	RegisterSSOProvider(w http.ResponseWriter, r *http.Request)
	// Unlink an auth provider
	// (POST /auth/unlink-account)
	UnlinkAccount(w http.ResponseWriter, r *http.Request)
	// Update user profile
	// (POST /auth/update-user)
	UpdateUser(w http.ResponseWriter, r *http.Request)
	// Verify email address
	// (GET /auth/verify-email)
	VerifyEmail(w http.ResponseWriter, r *http.Request, params VerifyEmailParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Stop impersonating a user
// (POST /auth/admin/stop-impersonating)
func (_ Unimplemented) AdminStopImpersonating(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all users (admin only)
// (GET /auth/admin/users)
func (_ Unimplemented) AdminListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ban a user
// (POST /auth/admin/users/{userId}/ban)
func (_ Unimplemented) AdminBanUser(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Impersonate a user
// (POST /auth/admin/users/{userId}/impersonate)
func (_ Unimplemented) AdminImpersonate(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Set a user's role
// (PATCH /auth/admin/users/{userId}/role)
func (_ Unimplemented) AdminSetUserRole(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unban a user
// (POST /auth/admin/users/{userId}/unban)
func (_ Unimplemented) AdminUnbanUser(w http.ResponseWriter, r *http.Request, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel a pending invitation
// (POST /auth/cancel-invitation)
func (_ Unimplemented) CancelInvitation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change email address
// (POST /auth/change-email)
func (_ Unimplemented) ChangeEmail(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change password
// (POST /auth/change-password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete user account
// (POST /auth/delete-user)
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange one-time authorization code for session token
// (POST /auth/exchange-code)
func (_ Unimplemented) ExchangeCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request password reset email
// (POST /auth/forget-password)
func (_ Unimplemented) ForgetPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get full organization details by ID
// (GET /auth/get-full-organization)
func (_ Unimplemented) GetFullOrganization(w http.ResponseWriter, r *http.Request, params GetFullOrganizationParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check organization permission
// (POST /auth/has-permission)
func (_ Unimplemented) HasPermission(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Accept an invitation
// (POST /auth/invitations/{invitationId}/accept)
func (_ Unimplemented) AcceptInvitation(w http.ResponseWriter, r *http.Request, invitationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reject an invitation
// (POST /auth/invitations/{invitationId}/reject)
func (_ Unimplemented) RejectInvitation(w http.ResponseWriter, r *http.Request, invitationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Link a social provider
// (POST /auth/link-social)
func (_ Unimplemented) LinkSocial(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List linked auth providers
// (GET /auth/list-accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List user's organizations
// (GET /auth/list-organizations)
func (_ Unimplemented) ListUserOrganizations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List active sessions
// (GET /auth/list-sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an organization
// (POST /auth/organizations)
func (_ Unimplemented) CreateOrganization(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an organization
// (DELETE /auth/organizations/{organizationId})
func (_ Unimplemented) DeleteOrganization(w http.ResponseWriter, r *http.Request, organizationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an organization
// (PATCH /auth/organizations/{organizationId})
func (_ Unimplemented) UpdateOrganization(w http.ResponseWriter, r *http.Request, organizationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List pending invitations
// (GET /auth/organizations/{organizationId}/invitations)
func (_ Unimplemented) ListOrganizationInvitations(w http.ResponseWriter, r *http.Request, organizationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Invite a user to the organization
// (POST /auth/organizations/{organizationId}/invitations)
func (_ Unimplemented) InviteMember(w http.ResponseWriter, r *http.Request, organizationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Leave an organization
// (POST /auth/organizations/{organizationId}/leave)
func (_ Unimplemented) LeaveOrganization(w http.ResponseWriter, r *http.Request, organizationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List organization members
// (GET /auth/organizations/{organizationId}/members)
func (_ Unimplemented) ListOrganizationMembers(w http.ResponseWriter, r *http.Request, organizationId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a member from the organization
// (DELETE /auth/organizations/{organizationId}/members/{userId})
func (_ Unimplemented) RemoveMember(w http.ResponseWriter, r *http.Request, organizationId string, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change a member's role
// (PATCH /auth/organizations/{organizationId}/members/{userId})
func (_ Unimplemented) SetMemberRole(w http.ResponseWriter, r *http.Request, organizationId string, userId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a passkey
// (POST /auth/passkey/delete-passkey)
func (_ Unimplemented) DeletePasskey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List user's passkeys
// (GET /auth/passkey/list-user-passkeys)
func (_ Unimplemented) ListUserPasskeys(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Complete passkey login
// (POST /auth/passkey/login)
func (_ Unimplemented) PasskeyLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin passkey login
// (POST /auth/passkey/login-options)
func (_ Unimplemented) PasskeyLoginOptions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Complete passkey registration
// (POST /auth/passkey/register)
func (_ Unimplemented) PasskeyRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Begin passkey registration
// (POST /auth/passkey/register-options)
func (_ Unimplemented) PasskeyRegisterOptions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reset password with token
// (POST /auth/reset-password)
func (_ Unimplemented) ResetPassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke a session
// (POST /auth/revoke-session)
func (_ Unimplemented) RevokeSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current session
// (GET /auth/session)
func (_ Unimplemented) GetSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sign in with email and password
// (POST /auth/sign-in/email)
func (_ Unimplemented) SignInEmail(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initiate OAuth sign-in (GitHub)
// (POST /auth/sign-in/social)
func (_ Unimplemented) SignInSocial(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initiate SSO sign-in
// (POST /auth/sign-in/sso)
func (_ Unimplemented) SignInSSO(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sign out
// (POST /auth/sign-out)
func (_ Unimplemented) SignOut(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register with email and password
// (POST /auth/sign-up/email)
func (_ Unimplemented) SignUpEmail(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register an SSO provider
// (POST /auth/sso/register)
func (_ Unimplemented) RegisterSSOProvider(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unlink an auth provider
// (POST /auth/unlink-account)
func (_ Unimplemented) UnlinkAccount(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update user profile
// (POST /auth/update-user)
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify email address
// (GET /auth/verify-email)
func (_ Unimplemented) VerifyEmail(w http.ResponseWriter, r *http.Request, params VerifyEmailParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AdminStopImpersonating operation middleware
func (siw *ServerInterfaceWrapper) AdminStopImpersonating(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminStopImpersonating(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminListUsers operation middleware
func (siw *ServerInterfaceWrapper) AdminListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminBanUser operation middleware
func (siw *ServerInterfaceWrapper) AdminBanUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminBanUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminImpersonate operation middleware
func (siw *ServerInterfaceWrapper) AdminImpersonate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminImpersonate(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminSetUserRole operation middleware
func (siw *ServerInterfaceWrapper) AdminSetUserRole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminSetUserRole(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUnbanUser operation middleware
func (siw *ServerInterfaceWrapper) AdminUnbanUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUnbanUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelInvitation operation middleware
func (siw *ServerInterfaceWrapper) CancelInvitation(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeEmail operation middleware
func (siw *ServerInterfaceWrapper) ChangeEmail(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeCode operation middleware
func (siw *ServerInterfaceWrapper) ExchangeCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ForgetPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgetPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ForgetPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFullOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetFullOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFullOrganizationParams

	// ------------- Required query parameter "organizationId" -------------

	if paramValue := r.URL.Query().Get("organizationId"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "organizationId"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "organizationId", r.URL.Query(), &params.OrganizationId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFullOrganization(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HasPermission operation middleware
func (siw *ServerInterfaceWrapper) HasPermission(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HasPermission(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "invitationId" -------------
	var invitationId string

	err = runtime.BindStyledParameterWithOptions("simple", "invitationId", chi.URLParam(r, "invitationId"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invitationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInvitation(w, r, invitationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RejectInvitation operation middleware
func (siw *ServerInterfaceWrapper) RejectInvitation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "invitationId" -------------
	var invitationId string

	err = runtime.BindStyledParameterWithOptions("simple", "invitationId", chi.URLParam(r, "invitationId"), &invitationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invitationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RejectInvitation(w, r, invitationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LinkSocial operation middleware
func (siw *ServerInterfaceWrapper) LinkSocial(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LinkSocial(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserOrganizations operation middleware
func (siw *ServerInterfaceWrapper) ListUserOrganizations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserOrganizations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrganization operation middleware
func (siw *ServerInterfaceWrapper) CreateOrganization(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteOrganization operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteOrganization(w, r, organizationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrganization operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrganization(w, r, organizationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizationInvitations operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizationInvitations(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizationInvitations(w, r, organizationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InviteMember operation middleware
func (siw *ServerInterfaceWrapper) InviteMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InviteMember(w, r, organizationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LeaveOrganization operation middleware
func (siw *ServerInterfaceWrapper) LeaveOrganization(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LeaveOrganization(w, r, organizationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListOrganizationMembers operation middleware
func (siw *ServerInterfaceWrapper) ListOrganizationMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListOrganizationMembers(w, r, organizationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveMember(w, r, organizationId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetMemberRole operation middleware
func (siw *ServerInterfaceWrapper) SetMemberRole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationId" -------------
	var organizationId string

	err = runtime.BindStyledParameterWithOptions("simple", "organizationId", chi.URLParam(r, "organizationId"), &organizationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetMemberRole(w, r, organizationId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePasskey operation middleware
func (siw *ServerInterfaceWrapper) DeletePasskey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePasskey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserPasskeys operation middleware
func (siw *ServerInterfaceWrapper) ListUserPasskeys(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserPasskeys(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PasskeyLogin operation middleware
func (siw *ServerInterfaceWrapper) PasskeyLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PasskeyLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PasskeyLoginOptions operation middleware
func (siw *ServerInterfaceWrapper) PasskeyLoginOptions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PasskeyLoginOptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PasskeyRegister operation middleware
func (siw *ServerInterfaceWrapper) PasskeyRegister(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PasskeyRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PasskeyRegisterOptions operation middleware
func (siw *ServerInterfaceWrapper) PasskeyRegisterOptions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PasskeyRegisterOptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResetPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignInEmail operation middleware
func (siw *ServerInterfaceWrapper) SignInEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignInEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignInSocial operation middleware
func (siw *ServerInterfaceWrapper) SignInSocial(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignInSocial(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignInSSO operation middleware
func (siw *ServerInterfaceWrapper) SignInSSO(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignInSSO(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignOut(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SignUpEmail operation middleware
func (siw *ServerInterfaceWrapper) SignUpEmail(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SignUpEmail(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterSSOProvider operation middleware
func (siw *ServerInterfaceWrapper) RegisterSSOProvider(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterSSOProvider(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnlinkAccount operation middleware
func (siw *ServerInterfaceWrapper) UnlinkAccount(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnlinkAccount(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params VerifyEmailParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "token", r.URL.Query(), &params.Token, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyEmail(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/admin/stop-impersonating", wrapper.AdminStopImpersonating)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/admin/users", wrapper.AdminListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/admin/users/{userId}/ban", wrapper.AdminBanUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/admin/users/{userId}/impersonate", wrapper.AdminImpersonate)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/auth/admin/users/{userId}/role", wrapper.AdminSetUserRole)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/admin/users/{userId}/unban", wrapper.AdminUnbanUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/cancel-invitation", wrapper.CancelInvitation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/change-email", wrapper.ChangeEmail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/change-password", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/delete-user", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/exchange-code", wrapper.ExchangeCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/forget-password", wrapper.ForgetPassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/get-full-organization", wrapper.GetFullOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/has-permission", wrapper.HasPermission)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/invitations/{invitationId}/accept", wrapper.AcceptInvitation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/invitations/{invitationId}/reject", wrapper.RejectInvitation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/link-social", wrapper.LinkSocial)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/list-accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/list-organizations", wrapper.ListUserOrganizations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/list-sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/organizations", wrapper.CreateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/organizations/{organizationId}", wrapper.DeleteOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/auth/organizations/{organizationId}", wrapper.UpdateOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/organizations/{organizationId}/invitations", wrapper.ListOrganizationInvitations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/organizations/{organizationId}/invitations", wrapper.InviteMember)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/organizations/{organizationId}/leave", wrapper.LeaveOrganization)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/organizations/{organizationId}/members", wrapper.ListOrganizationMembers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/auth/organizations/{organizationId}/members/{userId}", wrapper.RemoveMember)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/auth/organizations/{organizationId}/members/{userId}", wrapper.SetMemberRole)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/passkey/delete-passkey", wrapper.DeletePasskey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/passkey/list-user-passkeys", wrapper.ListUserPasskeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/passkey/login", wrapper.PasskeyLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/passkey/login-options", wrapper.PasskeyLoginOptions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/passkey/register", wrapper.PasskeyRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/passkey/register-options", wrapper.PasskeyRegisterOptions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/revoke-session", wrapper.RevokeSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/session", wrapper.GetSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sign-in/email", wrapper.SignInEmail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sign-in/social", wrapper.SignInSocial)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sign-in/sso", wrapper.SignInSSO)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sign-out", wrapper.SignOut)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sign-up/email", wrapper.SignUpEmail)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/sso/register", wrapper.RegisterSSOProvider)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/unlink-account", wrapper.UnlinkAccount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/update-user", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/verify-email", wrapper.VerifyEmail)
	})

	return r
}
