terraform {
  required_version = ">= 1.9"

  required_providers {
    coder = {
      source  = "coder/coder"
      version = "~> 2.18"
    }
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 4.5"
    }
  }
}

variable "docker_socket" {
  description = "Optional Docker socket URI used by the Coder provisioner."
  type        = string
  default     = ""
}

variable "coder_wildcard_access_url" {
  description = <<-EOT
    Full Coder wildcard app URL, for example https://*.apps.coder.example.com.
    Leave empty to use http://localhost:3000 as Shopmon's FRONTEND_URL.
  EOT
  type        = string
  default     = ""

  validation {
    condition = (
      var.coder_wildcard_access_url == "" ||
      can(regex("^https?://\\*\\.[^/]+/?$", var.coder_wildcard_access_url))
    )
    error_message = "coder_wildcard_access_url must be empty or a full wildcard URL such as https://*.apps.coder.example.com."
  }
}

provider "docker" {
  host = var.docker_socket != "" ? var.docker_socket : null
}

data "coder_provisioner" "me" {}
data "coder_workspace" "me" {}
data "coder_workspace_owner" "me" {}

locals {
  repository_url = "https://github.com/FriendsOfShopware/shopmon.git"
  repository_dir = "/home/coder/shopmon"

  workspace_container_name = "coder-${data.coder_workspace.me.id}-shopmon"
  docker_container_name    = "coder-${data.coder_workspace.me.id}-docker"

  frontend_url = (
    var.coder_wildcard_access_url != ""
    ? replace(
      trimsuffix(var.coder_wildcard_access_url, "/"),
      "*",
      "shopmon--${lower(data.coder_workspace.me.name)}--${lower(data.coder_workspace_owner.me.name)}"
    )
    : "http://localhost:3000"
  )

  demo_shop_url = (
    var.coder_wildcard_access_url != ""
    ? replace(
      trimsuffix(var.coder_wildcard_access_url, "/"),
      "*",
      "demo-shop--${lower(data.coder_workspace.me.name)}--${lower(data.coder_workspace_owner.me.name)}"
    )
    : "http://localhost:3889"
  )

  app_forwarded_proto = startswith(var.coder_wildcard_access_url, "https://") ? "https" : "http"

  mise_local_config = <<-EOT
    # Generated by the Shopmon Coder template. Do not commit this file.
    [env]
    COMPOSE_FILE = "compose.yml:.coder.compose.yml"
    DATABASE_URL = "postgres://shopmon:shopmon@${local.docker_container_name}:5432/shopmon?sslmode=disable"
    REDIS_URL = "redis://${local.docker_container_name}:6379"
    FRONTEND_URL = "${local.frontend_url}"
    SHOPWARE_APP_URL = "${local.demo_shop_url}"
    SMTP_HOST = "${local.docker_container_name}"
    SMTP_PORT = "1025"
    APP_S3_ENDPOINT = "http://${local.docker_container_name}:9000"
    APP_S3_ACCESS_KEY_ID = "rustfsadmin"
    APP_S3_SECRET_ACCESS_KEY = "rustfsadmin"
    APP_S3_BUCKET = "shopmon"
    APP_S3_REGION = "auto"
    APP_SITESPEED_ENDPOINT = "http://${local.docker_container_name}:3001"
    APP_SITESPEED_API_KEY = "secret"
    PACKAGES_API_URL = "http://${local.docker_container_name}:8787"
    PACKAGES_API_TOKEN = "shopmon"
  EOT

  compose_override = <<-EOT
    # Generated by the Shopmon Coder template. Do not commit this file.
    services:
      demoshop:
        environment:
          APP_URL: "$${SHOPWARE_APP_URL}"
          TRUSTED_PROXIES: "REMOTE_ADDR"
  EOT

  proxy_config = <<-EOT
    worker_processes 1;
    pid /home/coder/.local/state/shopmon/proxies/nginx.pid;
    error_log /home/coder/.local/state/shopmon/proxies/error.log warn;

    events {
      worker_connections 1024;
    }

    http {
      access_log off;
      client_body_temp_path /home/coder/.local/state/shopmon/proxies/client_body_temp;
      proxy_temp_path /home/coder/.local/state/shopmon/proxies/proxy_temp;
      fastcgi_temp_path /home/coder/.local/state/shopmon/proxies/fastcgi_temp;
      uwsgi_temp_path /home/coder/.local/state/shopmon/proxies/uwsgi_temp;
      scgi_temp_path /home/coder/.local/state/shopmon/proxies/scgi_temp;
      proxy_buffering off;
      proxy_request_buffering off;
      client_max_body_size 0;

      map $http_upgrade $connection_upgrade {
        default upgrade;
        ""      close;
      }

      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto ${local.app_forwarded_proto};
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;

      server {
        listen 127.0.0.1:8025;

        location / {
          proxy_pass http://${local.docker_container_name}:8025;
        }
      }

      server {
        listen 127.0.0.1:3889;

        location / {
          proxy_pass http://${local.docker_container_name}:3889;
        }
      }

      server {
        listen 127.0.0.1:16686;

        location / {
          proxy_pass http://${local.docker_container_name}:16686;
        }
      }
    }
  EOT
}

resource "coder_agent" "main" {
  arch = data.coder_provisioner.me.arch
  os   = "linux"

  env = {
    DOCKER_HOST         = "tcp://${local.docker_container_name}:2375"
    GIT_AUTHOR_NAME     = coalesce(data.coder_workspace_owner.me.full_name, data.coder_workspace_owner.me.name)
    GIT_AUTHOR_EMAIL    = data.coder_workspace_owner.me.email
    GIT_COMMITTER_NAME  = coalesce(data.coder_workspace_owner.me.full_name, data.coder_workspace_owner.me.name)
    GIT_COMMITTER_EMAIL = data.coder_workspace_owner.me.email
    SHOPWARE_APP_URL    = local.demo_shop_url
  }

  display_apps {
    vscode          = false
    vscode_insiders = false
  }

  metadata {
    display_name = "CPU Usage"
    key          = "0_cpu_usage"
    script       = "coder stat cpu"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "RAM Usage"
    key          = "1_ram_usage"
    script       = "coder stat mem"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Home Disk"
    key          = "2_home_disk"
    script       = "coder stat disk --path $HOME"
    interval     = 60
    timeout      = 1
  }

  metadata {
    display_name = "Docker Disk"
    key          = "3_docker_disk"
    script       = "docker system df --format 'table {{.Type}}\\t{{.Size}}' 2>/dev/null | tail -n +2 | paste -sd ', ' - || true"
    interval     = 60
    timeout      = 5
  }
}

module "coder-login" {
  count = data.coder_workspace.me.start_count

  source  = "registry.coder.com/coder/coder-login/coder"
  version = "1.1.1"

  agent_id = coder_agent.main.id
}

module "git-clone" {
  count = data.coder_workspace.me.start_count

  source  = "registry.coder.com/coder/git-clone/coder"
  version = "2.0.2"

  agent_id    = coder_agent.main.id
  url         = local.repository_url
  base_dir    = "/home/coder"
  folder_name = "shopmon"

  post_clone_script = <<-EOT
    #!/usr/bin/env bash
    set -euo pipefail

    cd "${local.repository_dir}"

    printf '%s' '${base64encode(local.mise_local_config)}' | base64 --decode >.mise.local.toml
    printf '%s' '${base64encode(local.compose_override)}' | base64 --decode >.coder.compose.yml
    grep -qxF '/.mise.local.toml' .git/info/exclude || printf '%s\n' '/.mise.local.toml' >>.git/info/exclude
    grep -qxF '/.coder.compose.yml' .git/info/exclude || printf '%s\n' '/.coder.compose.yml' >>.git/info/exclude

    mise trust --yes .mise.toml
    mise trust --yes .mise.local.toml
    mise install

    echo "Waiting for the workspace Docker daemon..."
    for attempt in $(seq 1 90); do
      if docker info >/dev/null 2>&1; then
        break
      fi
      if [ "$attempt" -eq 90 ]; then
        echo "Docker did not become ready in time." >&2
        exit 1
      fi
      sleep 2
    done

    mise run setup
    mise run up

    proxy_state_dir="$HOME/.local/state/shopmon/proxies"
    mkdir -p \
      "$proxy_state_dir/client_body_temp" \
      "$proxy_state_dir/proxy_temp" \
      "$proxy_state_dir/fastcgi_temp" \
      "$proxy_state_dir/uwsgi_temp" \
      "$proxy_state_dir/scgi_temp"
    proxy_config_file="$proxy_state_dir/nginx.conf"
    printf '%s' '${base64encode(local.proxy_config)}' | base64 --decode >"$proxy_config_file"

    # Coder app tunnels connect to the agent's loopback interface. Proxy
    # Docker-backed web UIs from the sibling DinD container and restore the
    # forwarding headers stripped by the app tunnel.
    if [ -f "$proxy_state_dir/nginx.pid" ] && kill -0 "$(cat "$proxy_state_dir/nginx.pid")" 2>/dev/null; then
      nginx -c "$proxy_config_file" -s reload
    else
      nginx -c "$proxy_config_file"
    fi

    echo "Waiting for PostgreSQL..."
    for attempt in $(seq 1 90); do
      if mise exec -- docker compose exec -T db pg_isready -U shopmon -d shopmon >/dev/null 2>&1; then
        break
      fi
      if [ "$attempt" -eq 90 ]; then
        echo "PostgreSQL did not become ready in time." >&2
        exit 1
      fi
      sleep 2
    done

    state_dir="$HOME/.local/state/shopmon"
    mkdir -p "$state_dir"

    if [ ! -f "$state_dir/fixtures-loaded" ]; then
      mise run load-fixtures
      touch "$state_dir/fixtures-loaded"
    else
      mise run migrate
    fi

    log_file="$state_dir/dev.log"
    pid_file="$state_dir/dev.pid"
    if [ ! -f "$pid_file" ] || ! kill -0 "$(cat "$pid_file")" 2>/dev/null; then
      nohup mise run dev >"$log_file" 2>&1 </dev/null &
      echo "$!" >"$pid_file"
    fi

    echo "Shopmon is starting. Development logs: $log_file"
  EOT
}

module "vscode-desktop" {
  count = data.coder_workspace.me.start_count

  source  = "registry.coder.com/coder/vscode-desktop-core/coder"
  version = "1.0.2"

  agent_id = coder_agent.main.id

  coder_app_icon         = "/icon/code.svg"
  coder_app_slug         = "vscode-insiders"
  coder_app_display_name = "VS Code Insiders"
  coder_app_order        = 1

  folder   = local.repository_dir
  protocol = "vscode-insiders"
}

resource "coder_app" "shopmon" {
  agent_id = coder_agent.main.id
  slug     = "shopmon"

  display_name = "Shopmon"
  icon         = "/icon/docker.svg"
  url          = "http://localhost:3000"
  subdomain    = true
  share        = "owner"
  order        = 3

  healthcheck {
    url       = "http://localhost:3000"
    interval  = 5
    threshold = 120
  }
}

resource "coder_app" "api" {
  agent_id = coder_agent.main.id
  slug     = "shopmon-api"

  display_name = "API"
  icon         = "/icon/go.svg"
  url          = "http://localhost:5789"
  subdomain    = true
  share        = "owner"
  order        = 4

  healthcheck {
    url       = "http://localhost:5789/healthz"
    interval  = 5
    threshold = 120
  }
}

resource "coder_app" "mailpit" {
  agent_id = coder_agent.main.id
  slug     = "mailpit"

  display_name = "Mailpit"
  icon         = "/icon/container.svg"
  url          = "http://localhost:8025"
  subdomain    = true
  share        = "owner"
  order        = 5

  healthcheck {
    url       = "http://localhost:8025"
    interval  = 5
    threshold = 120
  }
}

resource "coder_app" "demo_shop" {
  agent_id = coder_agent.main.id
  slug     = "demo-shop"

  display_name = "Demo Shop"
  icon         = "/icon/docker.svg"
  url          = "http://localhost:3889"
  subdomain    = true
  share        = "owner"
  order        = 6

  healthcheck {
    url       = "http://localhost:3889/api/_info/health-check"
    interval  = 10
    threshold = 120
  }
}

resource "coder_app" "jaeger" {
  agent_id = coder_agent.main.id
  slug     = "jaeger"

  display_name = "Jaeger"
  icon         = "/icon/widgets.svg"
  url          = "http://localhost:16686"
  subdomain    = true
  share        = "owner"
  order        = 7

  healthcheck {
    url       = "http://localhost:16686"
    interval  = 5
    threshold = 120
  }
}

resource "coder_app" "dev_logs" {
  agent_id = coder_agent.main.id
  slug     = "dev-logs"

  display_name = "Development Logs"
  icon         = "/icon/terminal.svg"
  command      = "touch ~/.local/state/shopmon/dev.log && tail -n 200 -f ~/.local/state/shopmon/dev.log"
  order        = 8
}

resource "docker_image" "workspace" {
  name         = "shopmon-coder-workspace:${substr(filesha1("${path.module}/Dockerfile"), 0, 12)}"
  keep_locally = true

  build {
    context    = path.module
    dockerfile = "Dockerfile"
  }

  triggers = {
    dockerfile_sha1 = filesha1("${path.module}/Dockerfile")
  }
}

resource "docker_image" "dind" {
  name         = "docker:29.6.2-dind"
  keep_locally = true
}

resource "docker_volume" "home" {
  name = "coder-${data.coder_workspace.me.id}-home"

  lifecycle {
    ignore_changes = all
  }

  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace_owner.me.id
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
  labels {
    label = "coder.workspace_name_at_creation"
    value = data.coder_workspace.me.name
  }
}

resource "docker_volume" "docker" {
  name = "coder-${data.coder_workspace.me.id}-docker"

  lifecycle {
    ignore_changes = all
  }

  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace_owner.me.id
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
  labels {
    label = "coder.workspace_name_at_creation"
    value = data.coder_workspace.me.name
  }
}

resource "docker_network" "workspace" {
  count = data.coder_workspace.me.start_count

  name     = "coder-${data.coder_workspace.me.id}"
  internal = false
}

resource "docker_container" "dind" {
  count = data.coder_workspace.me.start_count

  image      = docker_image.dind.image_id
  name       = local.docker_container_name
  hostname   = local.docker_container_name
  privileged = true

  command = [
    "dockerd",
    "--host=tcp://0.0.0.0:2375",
    "--host=unix:///var/run/docker.sock",
  ]

  env = [
    "DOCKER_TLS_CERTDIR=",
  ]

  networks_advanced {
    name = docker_network.workspace[0].name
  }

  volumes {
    container_path = "/var/lib/docker"
    volume_name    = docker_volume.docker.name
    read_only      = false
  }

  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
}

resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count

  image    = docker_image.workspace.image_id
  name     = local.workspace_container_name
  hostname = lower(data.coder_workspace.me.name)

  entrypoint = [
    "sh",
    "-c",
    replace(coder_agent.main.init_script, "/localhost|127\\.0\\.0\\.1/", "host.docker.internal"),
  ]

  env = [
    "CODER_AGENT_TOKEN=${coder_agent.main.token}",
    "DOCKER_HOST=tcp://${local.docker_container_name}:2375",
  ]

  host {
    host = "host.docker.internal"
    ip   = "host-gateway"
  }

  networks_advanced {
    name = docker_network.workspace[0].name
  }

  volumes {
    container_path = "/home/coder"
    volume_name    = docker_volume.home.name
    read_only      = false
  }

  labels {
    label = "coder.owner"
    value = data.coder_workspace_owner.me.name
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace_owner.me.id
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
  labels {
    label = "coder.workspace_name"
    value = data.coder_workspace.me.name
  }

  depends_on = [
    docker_container.dind,
  ]
}
