name = "shopmon"
main = "worker.api.js"
workers_dev = false
compatibility_date = "2022-03-04"
routes = ["shopmon.fos.gg/api/*"]

minify = true
node_compat = false
logpush = true

[vars]
MAIL_ACTIVE = "true"
MAIL_DKIM_DOMAIN = "fos.gg"
MAIL_DKIM_SELECTOR = "cf"
MAIL_FROM = "shopmon@fos.gg"
MAIL_FROM_NAME = "Shopmon"
FRONTEND_URL = "https://shopmon.fos.gg"

[build]
command = "node esbuild.mjs"

[durable_objects]
bindings = [
  { name = "SHOPS_SCRAPE", class_name = "ShopScrape" },
  { name = "PAGESPEED_SCRAPE", class_name = "PagespeedScrape" },
  { name = "USER_SOCKET", class_name = "UserSocket" },
]

[[migrations]]
tag = "v1"
new_classes = ["ShopScrape"]

[[migrations]]
tag = "v2"
new_classes = ["PagespeedScrape"]

[[migrations]]
tag = "v3"
new_classes = ["UserSocket"]

[[kv_namespaces]]
binding = "kvStorage"
id = "61a260743f17482e92fa5cb2c340edec"
preview_id = "61a260743f17482e92fa5cb2c340edec"

[[r2_buckets]]
binding = "FILES"
bucket_name = "shopmon"
preview_bucket_name = "shopmon"

[[d1_databases]]
binding = "shopmonDB"
database_name = "shopmon"
database_id = "cb4155f9-ade9-4035-925a-e483b953c18d"
migrations_dir = "drizzle"
