name: Deploy Staging
on:
  workflow_dispatch:

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    build:
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ghcr.io/friendsofshopware/shopmon:staging

    deploy:
        runs-on: ubuntu-latest
        environment:
            name: staging
            url: https://shopmon-staging.fos.gg
        needs: build
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5

            - name: Install OpenPubKey SSH
              run: go install github.com/openpubkey/opkssh@main

            - name: Authenticate with OpenPubKey
              run: opkssh login github

            - name: Scan SSH Key
              run: ssh-keyscan shea.shyim.de >> ~/.ssh/known_hosts

            - name: Install 1Password CLI
              uses: 1password/install-cli-action@v1

            - name: Deploy to Staging
              run: op run --env-file .env.staging -- docker compose -f compose.deploy.yml up -d --pull=always
              env:
                OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
