name: API Deploy

on:
  push:
    branches: [ main ]
    paths:
      - api/**
  workflow_dispatch:
jobs:
  api:
    runs-on: ubuntu-latest
    concurrency: 'api-deploy'
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-api-pnpm-store-${{ hashFiles('api/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-api-pnpm-store-

    - name: Install dependencies
      working-directory: api
      run: pnpm install

    - name: Build API
      working-directory: api
      run: node esbuild.mjs

    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './api/'
        ignore_empty: true

    - name: Publish API
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        workingDirectory: 'api'
        command: 'deploy'
