name: Frontend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: |
        cd frontend
        npm install
        npm run build
    - name: Publish
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        workingDirectory: 'frontend'
        command: pages publish --project-name=shopmon dist
