name: Deploy Staging
on:
  workflow_dispatch:

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    build:
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ghcr.io/friendsofshopware/shopmon:staging
                build-args:
                  SENTRY_RELEASE=${{ github.sha }}

    deploy:
        runs-on: ubuntu-latest
        environment:
            name: staging
            url: https://shopmon-staging.fos.gg
        needs: build
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup opkssh
              uses: shyim/setup-opkssh@main
              with:
                ssh-hosts-to-scan: 'shea.shyim.de'

            - name: Install 1Password CLI
              uses: 1password/install-cli-action@v1

            - name: Deploy to Staging
              run: op run --env-file .env.staging -- docker compose -f compose.deploy.yml up -d --pull=always --remove-orphans
              env:
                OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
                DOCKER_HOST: ssh://github@shea.shyim.de
