name: Lint and Test
on:
  push:
    branches:
      - main
      - feat/go-port
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Mise
        uses: jdx/mise-action@v4

      - name: Install Dependencies
        run: mise run setup

      - name: Run Lint
        run: mise run lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Mise
        uses: jdx/mise-action@v4

      - name: Install Dependencies
        run: mise run setup

      - name: Run Tests
        run: mise run test
